### ISSUE TITLE
Font resizing/zoom through the mouse wheel should be allowed

### ISSUE THREAD

**Issue by thommierother** [thunderbird-conversations/thunderbird-conversations#1044]
Conversations currently blocks the functionality of font zooming through the mouse wheel (tested with 201511251059-master on TB 38.4.0). This makes it hard to read mails and forces users to switch between classic reader and conversations view, especially on larger screens.

**Comment by sahil48** [comment]
Has this issue ever been addressed? Ctrl-mousewheel to adjust font size in message being read is a very useful feature for me.

**Comment by thommierother** [comment]
still not solved in 2.14.7 with TB 60.7.2

**Comment by keunes** [comment]
Would be much appreciated indeed - some newsletters are hard to read. Giving my thumbs up to OP.

**Comment by Standard8** [comment]
The work around here is `ctrl +`, `ctrl -` and `ctrl 0` (or use cmd if you're on Mac).

The mouse wheel issue actually appears to be a Thunderbird issue. We're re-using one of the areas where messages get displayed, and without conversations, ctrl + mouse wheel doesn't work either. Therefore I've filed a [bug on Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1585559) for the issue.

Unfortunately it isn't obvious what is wrong, so might not be an easy fix.

**Comment by thommierother** [comment]
ok, thx for the clarification; I registered for this bug on the TB bugzilla

**Comment by Standard8** [comment]
Just an update here, whilst looking at the other zoom issue (#1600), I've managed to figure out what this is. I've put up a patch for review for Thunderbird. If all goes well, we should be able to get that out in TB 91 around August time.

**Comment by Standard8** [comment]
Thunderbird 91 is now out & is starting to roll out via automatic updates to some users, I believe it is available to all users using the manual update mechanism (via help -> about). If not, then it should be within the next couple of weeks.

**Comment by thommierother** [comment]
... will check this the next days but at first glance its looking good ;-) ...
