### ISSUE TITLE
Make conversations work with markdown-here plugin

### ISSUE THREAD

**Issue by andoks** [thunderbird-conversations/thunderbird-conversations#1063]
While trying to replace Outlook with thunderbird, I installed both markdown-here(http://markdown-here.com/) and conversations plugin.

I love markdown-here for sending code in mail, as it has support for things like syntax highlighting.

However, when using conversations plugin, the markdown-plugin does not work.

**Comment by rnc** [comment]
Already entered as an issue in markdown github: https://github.com/adam-p/markdown-here/issues/146 (and note a prior discussion re markdown https://github.com/protz/thunderbird-conversations/issues/636 )

**Comment by protz** [comment]
Shouldn't be too hard -- the enigmail plugin already rewrites the 
contents of the message before sending it out, so it's just about 
markdown-here exposing a text -> text function and Conversations calling it.

I assume the Conversations plugin would, somehow, have to force the 
quick reply editor to be plaintext, though.

~ jonathan

**Comment by andoks** [comment]
Sounds like this might not be straight-forward if there is a general issue in thunderbird with plugin-interactions not being "transparent" so to speak.

> Shouldn't be too hard -- the enigmail plugin already rewrites the contents of the message before sending it out, so it's just about

Do you mean that enigmail works with the conversations-plugin? If that's the case, it might be possible to look into how enigmail handles the interactions, and perhaps enhance markdown-here inspired by that (unless markdown-here's text-manipulation is vastly different from how enigmail does it)

**Comment by protz** [comment]
Yes, see `modules/plugins/enigmail.js` -- you should be able to reuse selected bits of this code. There's a plugin infrastructure for other addons to interact with Conversations.

**Comment by ctr26** [comment]
Any news on this?

**Comment by protz** [comment]
There's already basic support for formatting in Conversations; but no one has implemented support for that specific Markdown plugin, as far as I know.

**Comment by siefkenj** [comment]
It looks like Markdown-here is not supported in modern versions of TB. Should this issue be closed? @Standard8

**Comment by Standard8** [comment]
Yes, I think we can close this. If the Markdown plugin starts up again, I'd be happy for this to be re-opened or a new issue filed.
