### ISSUE TITLE
[Security] Thunderbird Conversations hides the Enigmail key information

### ISSUE THREAD

**Issue by marmistrz** [thunderbird-conversations/thunderbird-conversations#1120]
When a signed/encrypted message is opened in the classic viewer, the Enigmail addon displays information if the key has been verified or not. The Conversations add-on hides this important security info.

From emailselfdefense.fsf.org:

> Be wary of invalid keys
> 
> GnuPG makes email safer, but it's still important to watch out for invalid keys, which might have fallen into the wrong hands. Email encrypted with invalid keys might be readable by surveillance programs.
> 
> In your email program, go back to the first encrypted email that Edward sent you. Because Edward encrypted it with your public key, it will have a message from Enigmail at the top, which most likely says "Enigmail: Part of this message encrypted."
> 
> When using GnuPG, make a habit of glancing at that bar. The program will warn you there if you get an email encrypted with a key that can't be trusted.

**Comment by protz** [comment]
@shirosaki thoughts...?

**Comment by xi** [comment]
I actually do not understand that section from emailselfdefence: I guess by "invalid" key they mean one that still works (i.e. the keypair is still available) but the private key has been compromised. This does not imply a threat to the recipient, only to the sender.

Also note that as a recipient you can never be sure that an encrypted mail was actually encrypted by the sender. An attacker could intercept an unencrypted mail, encrypt it and then forward it. So infering anything from the fact that the mail is encrypted when I receive it is never a good idea. Knowing the key that was used does not change anything about that.

The information that is actually important is whether I trust the signature on a message. And this information is clearly displayed in Conversations.

I also think that the classic viewer works mostly the same. @marmistrz can you provide more details on the differences? Maybe a screenshot?

**Comment by MartinX3** [comment]
Same here:
FossaMail based on LTS Thunderbird v38.
There are some compatibility issues with conversations v2.10.2 and enigmail v1.9.6.1

Mails are sometimes not decrypted, instead, they are showing the encrypted stuff.
And the tags which are showing you if the mail is encrypted/signed are missing.
If i disable conversations, everything is working.

I already tried to deactivate the checkboxes in the wizard.
I think the problem is the conversation "view".

**Comment by xi** [comment]
Hi @MartinX3. I think what you are describing is not the same as this issue. Sounds more like #901. (Please do not answer in this issue in order to avoid disgression).

**Comment by MBurchard** [comment]
If you read the first post, it is quite clear what the problem is. Thunderbird Conversations only indicates that the message is encrypted or signed.
The important information about which key is misappropriated.
Will there be an improvement on this?

**Comment by irgendwie** [comment]
Can't reproduce, using Thunderbird 52.7.0 with Enigmail 1.9.9 (broken with 2.0.1 for me).

![screenshot from 2018-04-06 14-04-30](https://user-images.githubusercontent.com/8360698/38420447-0dafe108-39a4-11e8-8b12-3297dbf8e086.png)

After clicking on Details:
![screenshot from 2018-04-06 14-05-17](https://user-images.githubusercontent.com/8360698/38420448-0dcdf8be-39a4-11e8-9126-11adcb721c43.png)

**Comment by MartinX3** [comment]
I can reproduce this bug.
Thunderbird 52.7.0 x64
Enigmail 2.0.1
Conversations 2.13.4
Linux Ubuntu Mate 17.10 x64

![grafik](https://user-images.githubusercontent.com/4518092/38489154-d53b8842-3be5-11e8-8ed3-3f3e52fc5836.png)

**Comment by alexbarcelo** [comment]
When using conversations 3.x the enigmail is broken --even when using the "classic reader". I can only see the "green Enigmail bar" when I choose "Open in new window".

The conversation view never shows the enigmail information.

I have downgraded to the last conversations 2.x and, at least, I am able to see the enigmail information when opening it into classic reader.

Thunderbird 68.4.1 (64-bit)
Enigmail 2.1.2
Conversations 2.15.16 (I have tried with some 3.x with the previously discussed behaviour)
Ubuntu 18.04

**Comment by Standard8** [comment]
You should be able to click the encrypted tag to get the information. However, I should probably also see if I can work out how to add the notification bar back again.

**Comment by alexbarcelo** [comment]
I am not sure if I know what the "encrypted tag" is.

Here an example of the absence of enigmail stuff:
![encryptedtag](https://user-images.githubusercontent.com/665750/75246942-1f1d0b80-57d1-11ea-9686-086ec5a117e5.png)

**Comment by Crocmagnon** [comment]
I'm also facing this issue.

Here's a screenshot taken with conversations 2.15.16: it shows a "decrypted" pill on a message that I only sent signed (false information).
![image](https://user-images.githubusercontent.com/3630554/83121962-44bcf800-a0d3-11ea-8ff1-edc819ac0bad.png)

With the latest version the pill doesn't even appear. I can check the validity of the signature using the classic viewer but it would be useful to just report the enigmail bar in the conversation view, without trying to change anything from the output.

**Comment by Standard8** [comment]
> Here's a screenshot taken with conversations 2.15.16: it shows a "decrypted" pill on a message that I only sent signed (false information).
...
> I can check the validity of the signature using the classic viewer but it would be useful to just report the enigmail bar in the conversation view, without trying to change anything from the output.

You can click the pill to get the full information - a pop-up dialog will appear.

Unfortunately I don't have time to work on making this a notification bar at the moment - I'm working on rewriting a lot of the Conversations back end so that we can better integrate with the latest Thunderbird changes and have a better chance of supporting newer versions.

I'm quite happy to accept patches though - the code around this is in javascript/react.

> With the latest version the pill doesn't even appear.

This is indeed a bug, I've just fixed that in the latest master (2a517b0b5), I'm not sure I'm going to be able to release a 3.0.x version with that, as I don't quite know what's broken there, although I suspect it would likely need a fix that's already done on master that would be too much to backport. Hopefully we can get 3.1.x out in a week or so once we figure out some upgrade issues.

> Thunderbird 68.8.1

If you do start using 3.x then you'll want to upgrade this to the latest. There's a bug in the earlier versions of 68.8.x that affects marking messages in IMAP accounts as read.

**Comment by Crocmagnon** [comment]
> You can click the pill to get the full information - a pop-up dialog will appear.

Clicking on the pill didn't do anything.

> I'm quite happy to accept patches though

Good news 😀 I won't have time to develop them myself though but glad to know that 🙂 

> This is indeed a bug, I've just fixed that in the latest master

🎉 

> If you do start using 3.x then you'll want to upgrade this to the latest.

According to [Thunderbird website's](https://www.thunderbird.net/en-US/thunderbird/68.8.1/releasenotes/) I'm already at the latest version.

**Comment by Crocmagnon** [comment]
Weird, I'm trying the exact same setup on another macOS machine and I see the pills + I can click them.
![image](https://user-images.githubusercontent.com/3630554/83166974-f11ccf80-a10f-11ea-9e7a-f1585ee09dea.png)

Thunderbird 68.8.1
Thunderbird Conversations 3.0.18
Enigmail 2.1.6

**Comment by pchampin** [comment]
I don't see the pills :cry:

Thunderbird 68.10.0
Thundirbird Conversations 3.1.22
Enigmail 2.1.4
OS: Ubuntu 20.4

**Comment by Standard8** [comment]
By the three lines, I meant the application menu at the right hand end of toolbar - the app menu:
<img width="42" alt="Screenshot 2020-09-04 at 17 39 01" src="https://user-images.githubusercontent.com/520844/92264276-e2477500-eed5-11ea-8991-604c25b25029.png">

**Comment by Standard8** [comment]
Oh wait, sorry, wrong issue.

**Comment by Standard8** [comment]
I've just pushed Conversations 4.0.0 for review which should be approved in a couple of days. It includes changes where you can click on the signed/encrypted pills and get the same detail as you would when clicking on the S/MIME or OpenPGP buttons on the Thunderbird header as displayed in Thunderbird 91.

Hence calling this fixed.
