### ISSUE TITLE
gmail conversation reply not loading quoted text (trimmed text) when new message arrive

### ISSUE THREAD

**Issue by maykel-gh** [thunderbird-conversations/thunderbird-conversations#1128]
when I am on a conversation, and a new message arrive, and I click reply or reply all, the quoted text (also known as trimmed text in gmail) is not loaded, until I change the conversation and go back.

**Comment by protz** [comment]
Yes I have seen this issue as well... need to investigate

**Comment by Standard8** [comment]
As far as I know, this is no longer an issue, closing out.
