### ISSUE TITLE
Can "send" an email twice

### ISSUE THREAD

**Issue by 83bytes** [thunderbird-conversations/thunderbird-conversations#1250]
* **Thunderbird version : 52.4.0**
* **Thunderbird Conversation version: 2.13.3**
* **Operating System: Arch Linux**

Issue: We can send emails twice by clicking the "send" button back to back,

I discovered that in an email thread when I click "reply" or "reply all" i get this editor like box where i can type the message and after that I can send it by hitting the "send" button. 

Now after hitting the send button the button is decativated and a loading like animation shows up on the top right hand side of the small window.

After that if i wait long enough the window disappears and it shows that the message has been sent.

BUT if we do not wait long enough and keep clicking the deactivated send button.. then there is  slight delay between the time it sends the email and the time it closes the editor window and we can actually send the previous email again. 

I  have managed to replicate this twice.

**Comment by Standard8** [comment]
I believe this is fixed with the latest version of quick reply.
