### ISSUE TITLE
clippings addon

### ISSUE THREAD

**Issue by helmax22** [thunderbird-conversations/thunderbird-conversations#1253]
Is possible add or put compatible with addon clippings ?

**Comment by helmax22** [comment]
is not possible put clippings in quick replay ?

**Comment by Standard8** [comment]
I suspect that it the clippings add-on would need to be made compatible with conversations. I suspect the way conversations is changing the UI is what makes it incompatible. I could be wrong, so if the author of the add-on is interested in working on it, I'd be interested to here what is incompatible.

Unfortunately, we don't have time to work on this ourselves.

**Comment by helmax22** [comment]
author of clippings say yes want put working on conversations 
if join this 2 addons is a bomb
https://groups.google.com/forum/#!category-topic/aecreations-help/allquestions/m1m1NoC4jgM

**Comment by Standard8** [comment]
I believe the work here would be for Clippings to adapt how it is integrating. This might be easier once #1609 is fixed.

I think I'm going to close this out, as the [existing add-on compat issues](https://github.com/thunderbird-conversations/thunderbird-conversations/issues?q=is%3Aopen+is%3Aissue+label%3A%22add-on+compat%22) already cover possible integration issues, and generally it is the add-on authors that need to make sure they are compatible with standard Thunderbird WebExtension APIs.
