### ISSUE TITLE
Does not work together with Provider for Google Calendar

### ISSUE THREAD

**Issue by elhennig** [thunderbird-conversations/thunderbird-conversations#1266]
The Google calendars I have in Lightning were not displayed or updated anymore and the conversations view was gone. Only I disabled the Thunderbird Conversations addon the calendars worked again.
Since the calendars are more important to me, I cannot use the conversations addon anymore even if I like it very much.

**Comment by Standard8** [comment]
@elhennig Please can you include version information as was requested when you filed the PR, i.e.

* **Thunderbird version:**
* **Thunderbird Conversation version:**
* **Operating System:**

**Comment by elhennig** [comment]
Sorry, I missed that info. Here are the versions:
Thunderbird version: 52.6.0 (Linux, 64bit)
Thunderbird Conversation version: 2.13.4
Operating System: opensuse Leap 42.3
Provider for Google Calendar: 3.3

**Comment by Standard8** [comment]
We'd need someone to help investigate this, we don't have time at the moment. I think the calendar provider does some parsing of messages, so it could be that breaks this somehow.

**Comment by Standard8** [comment]
I'm not sure if this is still an issue or not - lots have changed in the calendar parts of Thunderbird since this was filed, the Conversations add-on has also changed a lot.

If this is still an issue please feel free to re-open.
