### ISSUE TITLE
Does not respect "automatically mark as read on display"

### ISSUE THREAD

**Issue by maximbaz** [thunderbird-conversations/thunderbird-conversations#1281]
* **Thunderbird version:** 52.8.0
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** Arch Linux

**Configuration**

Preferences > Display > Advanced > Automatically mark messages as read > Immediately on display

![image](https://user-images.githubusercontent.com/1177900/41089321-d87a9e5a-6a41-11e8-8bb8-0996c8d589ff.png)

**Description**

I have a bunch of unread emails in Inbox. I go through them one by one with arrows key, reviewing the content in the preview section. I expect the messages to be immediately marked as read, but this doesn't happen.

In fact, the result is inconsistent, sometimes an email is marked as read after 2-3 seconds, sometimes it is not marked as read at all.

I tried changing this setting to "after 1 second", same issue. I tried re-running the Wizard, restarting Thunderbird, disabling and enabling the extension — no luck.

As soon as I disable the extension and return to native preview screen, Thunderbird correctly marks emails as read as soon as they are rendered in preview section.

See how the selected email is bold, meaning "unread"? This should never happen with my settings:

![image](https://user-images.githubusercontent.com/1177900/41089789-f50be154-6a42-11e8-90ea-c10583690a0a.png)

**Comment by maximbaz** [comment]
I've just spotted that when the message is "stuck" in "unread" state as shown on the picture above, if I start moving mouse cursor (not clicking anything) it will get marked as read. But it should work without requiring users to grab the mouse 🙂

**Comment by Standard8** [comment]
Does this happen without the add-on installed? I'm wondering whether this could be a Thunderbird issue or not.

**Comment by maximbaz** [comment]
I think not, I was using Thunderbird for a while before I discovered this addon, and I didn't experience this issue. Disabling this addon immediately solves the issue, once I disable it and have the native preview screen again, Thunderbird correctly marks emails as read as soon as they are rendered in preview section.

**Comment by adefaria** [comment]
I get this occasionally with TB on Ubuntu. Didn't think to disable conversation view as I like that view. Note that this doesn't happen automatically rather TB will work for a while and then "break". IOW it starts failing to mark messages as read. I can select Mark to mark the message as read. Or I can restart TB and it starts working again for a while. Very frustrating!

**Comment by Standard8** [comment]
Is this still an issue in Thunderbird 68 / conversations 3.0.16? A lot has changed recently and I suspect we've improved things here.

**Comment by alexolog** [comment]
My problem is the opposite: the conversation emails get marked as read as soon as they are displayed in the preview pane, even though I set TB to never automatically mark them.

I am still using TB52 with an older (compatible) version of the add-on since some of my most needed extensions were not converted to WE.

Is it possible to backport a fix into a TB52-compatible version?

**Comment by Standard8** [comment]
@alexolog If you can find what the fix was, or is, then you'd be welcome to build the old version and use it yourself - the old release branches are all in the repository. We wouldn't support it nor publish it on the add-ons site as Thunderbird 52 is out of support for security fixes and there's less than 1% of Conversations users using those builds (probably no more than 400 users).

Additionally, back porting any fix could be complex - a lot of the code has been rewritten in the last couple of years, the code base is quite different to what it was back then. You might be lucky with the read handling, as some of that is still probably more-or-less the same.

**Comment by fhw72** [comment]
The problem still persists in V78.2.2

**Comment by Standard8** [comment]
@fhw72 Please can you confirm exactly what your mark as read settings are, and if you're seeing this all the time or just occasionally.

It would also be useful if you could go to the three-bar menu -> Tools -> Developer Tools -> Error Console and see if any error messages appear when you hit the issue.

**Comment by fhw72** [comment]
Here we go:

uncaught exception: ParserError: Missing parameter value in 'fn;quoted-printable:figaro=C2=B4s GmbH'

**Comment by Standard8** [comment]
Is there any file / line number information with that? or maybe a stack? (there's sometimes an expand triangle on the left).

Can you try without the add-on enabled? This seems like it might be something that affects Thunderbird as well.

**Comment by fhw72** [comment]
No... no file/Line number is given. I also don't have any add-ons installed. It's a fresh installation.

**Comment by fhw72** [comment]
I just took a look at the source of the message: The offending line is in the text/x-vcard

**Comment by fhw72** [comment]
The problem still persists with V78.3.0

**Comment by fhw72** [comment]
Seems to be fixed; I cannot reproduce it anymore in V78.3.2.

Thanks!

**Comment by Standard8** [comment]
The last comments imply this may be fixed, and I've never seen it. If this is still an issue, please feel free to open a new one.
