### ISSUE TITLE
Need to hit enter key twice to add a line feed in Quick Reply.

### ISSUE THREAD

**Issue by sahil48** [thunderbird-conversations/thunderbird-conversations#1303]
* **Thunderbird version:** 60.0
* **Thunderbird Conversation version:** 2.14.4
* **Operating System:** Windows 10

**What did you do?**
I hit the enter/return key twice using the Quick Reply Feature.

**What did you expect to happen?**
I expected to see two line feeds
**What actually happened?**
I only see one line feed and have to press enter a third time to add the second line feed.

**Comment by Standard8** [comment]
Yes, I see this as well.

**Comment by touch444719** [comment]
Any news regarding this issue ? 

The "quick reply" feature is the only feature that still block me to update to V60.
This issue as well as when you "clic" the quick reply field, it doesn't automatically put your cursor right on top to directly write your reply (with some spaces already fill in between your cursor and the last reply).

Basically exactly what I have right now with the 52.9.1 thunderbird and the 2.14.4 conversation addon.

Thank you for your work so far tho !

**Comment by ZizzyZizzy** [comment]
Ditto here. You have to hit enter twice for a CR+LF, and three times if you want a new paragraph.

This is new behavior with the new version from Jan. Very annoying.

**Comment by koolx** [comment]
Exactly. Why the hell would the dev make the addon behave this way?? 
I've never seen a program where you hit enter twice to produce a new 
sentence and 3 times to start a new paragraph. Could you correct this, 
its very damn annoying and causes many inexcusable typing errors.

**Comment by koolx** [comment]
Another issue: Please convert military time to standard time.

**Comment by Standard8** [comment]
Unfortunately "the dev" doesn't have much time to work on conversations, and this is the occasionally bit of time in the evenings after having done a day's work, decorating, looking after the kids etc. At the moment, "the dev" is working on a massive overhaul so there's at least a chance of it continuing to have basic functions for when Thunderbird 68 is released (soon).

I expect fixing this to be a multi-hour debugging session as the reason this is happening is not obvious - I expect it to be in the core of Thunderbird somewhere, in a component I'm not familiar with. I will try and fix it at some stage, but knowing it likely really needs a single deep session is something I can't allocate time for at the moment.

I would like to remind you that this is free and open source software. You are quite welcome to try and help fix it or find other people that might. If you continue with this attitude, I will be reporting you.

**Comment by koolx** [comment]
> 
> 
> Unfortunately "the dev" doesn't have much time to work on conversations, and this is the occasionally bit of time in the evenings after having done a day's work, decorating, looking after the kids etc. At the moment, "the dev" is working on a massive overhaul so there's at least a chance of it continuing to have basic functions for when Thunderbird 68 is released (soon).
> 
> I expect fixing this to be a multi-hour debugging session as the reason this is happening is not obvious - I expect it to be in the core of Thunderbird somewhere, in a component I'm not familiar with. I will try and fix it at some stage, but knowing it likely really needs a single deep session is something I can't allocate time for at the moment.
> 
> I would like to remind you that this is free and open source software. You are quite welcome to try and help fix it or find other people that might. If you continue with this attitude, I will be reporting you.

Well I'm glad the "dev" has finally made that clear since we havent heard from "him" in a long while and hasnt informed us about "his" life.

I have a friend who has contributed with a code to possibly format the time to standard time. The proposed code is here:
https://github.com/protz/thunderbird-conversations/compare/master...koolx:patch-1

Didnt mean to get you upset. Just that I like your addon which is why I sounded like that. But report if you want it dont bother me. You'll only waste your time with a warning or ban. I'll just return with a new account. Done it many times. Up to you.

**Comment by Standard8** [comment]
Note: at the moment Quick Reply is disabled in Thunderbird 68 (Issue #1361), from what I've seen a while ago the issue may be fixed once we can get the editor re-enabled.

**Comment by Standard8** [comment]
The new Quick Reply doesn't have this issue.

**Comment by sileeb** [comment]
> The new Quick Reply doesn't have this issue.

Actually it does have this issue. Theres no quick reply on the latest conversations.

Also, when can we be able to render conversations in dark mode? Its really about time. Looking forward to hearing from you.

**Comment by Standard8** [comment]
> > The new Quick Reply doesn't have this issue.
> 
> When can we be able to render conversations in dark mode? Its really about time. Looking forward to hearing from you.

As I have said multiple times elsewhere, it is not a priority for me at the moment. Fixing some of the more serious issues around just making it easier to maintain the add-on across various Thunderbird updates, fixing bugs that affect everyone, responding to demanding comments, etc has been what is taking up very limited time I get to work on this. I've just done one fairly major rework that has taken the last few months. The next piece is probably to see if I can address some of the more fundamental performance issues.

As I've also said elsewhere multiple times, I'd be quite happy to receive patches for supporting dark mode.

**Comment by sileeb** [comment]
On a few occasions I offered to assist in providing dark mode through my knowledge of CSS but that was met with no response. My offer is still open. If CSS can be applied to Conversations let me know so we can establish a base of communication. 

With all due respect, dark mode should be a priority since looking at white emails all day especially for those with vision issues would be beneficial and therapeutic. 

Let me know if I may still help you with CSS. Looking forward to hearing your response. Thanks.

**Comment by sileeb** [comment]
Mark, I almost forgot to mention that the addon, Dark Reader for thunderbird, works well. Perhaps that addon may make life easier to transition Conversations into dark mode. Just a thought. Thanks.

**Comment by Standard8** [comment]
> On a few occasions I offered to assist in providing dark mode through my knowledge of CSS but that was met with no response. My offer is still open.

I'm sorry if I've missed that offer in the past, I've just done a search and couldn't find it.

> If CSS can be applied to Conversations let me know so we can establish a base of communication.

There's an existing project with issues to fix within it: https://github.com/thunderbird-conversations/thunderbird-conversations/projects/5

Some of those may be out of date now, but conversations on those would be the best thing.

> I almost forgot to mention that the addon, Dark Reader for thunderbird, works well in rendering pages dark. Perhaps that addon may make life easier to transition Conversations into dark mode. Just a thought. Thanks.

Unfortunately the differences in licenses would probably make that difficult to handle. I think there is improved support coming to Thunderbird though, so we may be able to leverage that more.

**Comment by sileeb** [comment]
> I'm sorry if I've missed that offer in the past, I've just done a search and couldn't find it.

Just to reiterate about the thunderbird extension called Dark Reader which  renders emails in dark mode. Since youre the author of TC, it would be a great idea if you reach out to the author of that extension to have him adapt TC to dark mode, thereby saving you time and energy in building dark mode on your own from scratch.

Licenses may be worked out. Honestly, its a good idea to reach to him.
