### ISSUE TITLE
Respect background color for dark theme

### ISSUE THREAD

**Issue by Siggi0904** [thunderbird-conversations/thunderbird-conversations#1313]
With themes like "TT DEEPDARK" or Mozillas own dark theme the complete background of thunderbird could be in darker grey.

With these newer design points from mozilla thunderbird conversations should use or respect these backgrouund color for mail/conversations background.

Great thanks.

**Comment by amagit19** [comment]
I second this. I love TB Conversations but i sadly have to switch it off until dark mode support is fixed. I hope you'll change your mind and take a look at it :)

**Comment by parrenin** [comment]
Would be good indeed to have dark theme support in TB-conversations.

**Comment by Feichtmeier** [comment]
Yes all the icons do not respect the current text color.
Maybe you should switch to symbolic icons instead?
@Standard8

**Comment by Standard8** [comment]
@Feichtmeier as I already said, I'm happy to accept patches, but this isn't a priority for me at the moment.

**Comment by Standard8** [comment]
I've just set up a project for dark mode support:

https://github.com/thunderbird-conversations/thunderbird-conversations/projects/5

With that and #1510, I'm closing this one as I think we now have enough coverage of issues.

**Comment by pixelb** [comment]
Broken again on 95.0b1. I'm using dark mode, and message view pane background is white / light

**Comment by Standard8** [comment]
> Broken again on 95.0b1. I'm using dark mode, and message view pane background is white / light

This was never fixed, so it can't be "broken again". This is closed because I split it out into a project as referenced by my previous comment.

I guess there's a small chance something in Thunderbird "fixed" it briefly, but I've not made any changes here recently.
