### ISSUE TITLE
pdf preview for password protected files does not work

### ISSUE THREAD

**Issue by ogjerstad** [thunderbird-conversations/thunderbird-conversations#1339]
* **Thunderbird version:** 60.4.0
* **Thunderbird Conversation version:** 2.14.17
* **Operating System:** Linux (Fedora 29)

**What did you do?** Tried to preview a password protected file

**What did you expect to happen?** a password prompt

**What actually happened?** It shows the text "PasswordException: No password given" without any content or input fields

![image](https://user-images.githubusercontent.com/12524007/51468214-aeeebb80-1d6e-11e9-9f3c-8d180f728611.png)

**Comment by Standard8** [comment]
The pdf functionality has now moved to Thunderbird, and this works with the new functionality within Thunderbird.
