### ISSUE TITLE
Sender and receiver seems to be swaped with account with several identities when click reply

### ISSUE THREAD

**Issue by baluballa** [thunderbird-conversations/thunderbird-conversations#1350]
60.5.2
20190221150524 (I think or build ID)
Windows_NT 10.0

Try to reply email from "conversations"

I expected receiver to in to field, and sender be in from field

opposite of what I expected. I believe "thunderbird-conversations" might have problems having accounts with several identities.

**Comment by Standard8** [comment]
You might want to check the headers of an email you are replying to and see how they correlate to what conversations inserts. I'm fairly sure we follow what Thunderbird does but I could be wrong.

**Comment by Standard8** [comment]
I've been using multiple identities and I've not seen an issue in the latest versions. If this is still an issue please feel free to re-open.
