### ISSUE TITLE
Quick Reply is not available/disabled/not working in Thunderbird 68

### ISSUE THREAD

**Issue by Standard8** [thunderbird-conversations/thunderbird-conversations#1361]
Quick reply wasn't working at all in Thunderbird 68, so I disabled it for the time being. This issue is to track progress on re-enabling it.

Currently, there is a big rewrite in progress moving from jQuery to React (#1317). This was started due to the changes in Thunderbird 68, and hopefully providing us with a more solid base for the future and an easier to maintain code base.

At the moment, the rewrite has completed enough for Thunderbird 68 support. However, rewriting and fixing the quick reply display is not going to be possible until the message views are all rewritten in React. At the moment I have the basic message displays working, but there's a lot of mechanics missing.

My hope is to be able to re-enable it within a month, but this depends on what time I have, and how long the message displays take.

**Comment by Standard8** [comment]
Just an update here. Most of the move to React is done on the latest master. There's a few things broken at the moment - mainly Enigmail integration, which some people need. Once that's done, I can hopefully release that update, then start looking back at Quick Reply.

**Comment by ghalse** [comment]
The "Quick Reply is temporarily disabled due to needing more work for Thunderbird 68." message does not have the `.quickReply` CSS class, meaning that people using [this trick to disable quick reply](https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature) still see the error.

I understand that the aim is to get this feature working again as quickly as possible, but if it's still likely to take a while and there's going to be another interim release, could I request that the error at least re-gain the same CSS class :-)

**Comment by pawelpotoniec** [comment]
Any ETA? Can I help somehow?

**Comment by Standard8** [comment]
@pawelpotoniec I've been concentrating more on getting Conversations ready to work for the next version of Thunderbird as there's again more significant changes, and still quite a lot of work to do.

However, if someone is willing to help out here, that would be great.

What I'd like to get done first is to create a new compose widget that has just a very simple plain text editor, and no options for changing the to/cc/bcc lists (but indicate who it will be sent to).
Maybe not even quoting the original message to being with.

 This would restore most of the functionality, and we could add the extra bits back afterwards.

I can summarise in more details if anyone is interested - the front end is now developed in React.

**Comment by rnc** [comment]
@Standard8 (for future) ; if quick reply is restored can it still be optional please as I had it permanently disabled ;-)

**Comment by Standard8** [comment]
I've now created a new branch that has a very basic experimental compose function that is implemented under the old experimental ctrl-shift-N (or cmd-shift-N) functionality.

The idea is to get a compose widget going in the separate tab/window functionality, and get something good enough to ship for people to test out, then to integrate that back into the quick reply function.

The branch is the [compose-experiment branch](https://github.com/thunderbird-conversations/thunderbird-conversations/tree/compose-experiment).

The version in the branch currently uses the default account/identity and you can send a plain text message with it (I think the old quick reply was plain text as well). The UI isn't styled yet, and there's lots to do to get something that's good enough to ship, e.g. send notifications, error handling, autocomplete and lots of other parts.

I'll try and create a checklist over the next few days of what needs to be done, so if anyone wants to help out that would be a good starting point.

**Comment by Standard8** [comment]
I've just filed #1513 on getting the compose experiment to be functional enough to ship. If people want to help out, please see the list there.

**Comment by avatar-lavventura** [comment]
> The "Quick Reply is temporarily disabled due to needing more work for Thunderbird 68." message does not have the `.quickReply` CSS class, meaning that people using [this trick to disable quick reply](https://github.com/protz/thunderbird-conversations/wiki/Tips-and-tricks:-Disabling-the-%22Quick-Reply%22-feature) still see the error.
> 
> I understand that the aim is to get this feature working again as quickly as possible, but if it's still likely to take a while and there's going to be another interim release, could I request that the error at least re-gain the same CSS class :-)

I tired it but it does not help to remove the warning message

**Comment by Standard8** [comment]
I've updated the wiki page to reflect there's a preference that now needs toggling.

I've also just landed 9fc62ec94c9b9090a75c94aaec7c5d87607c8987 which adds an option to hide quick reply, since a reasonable amount of people seem to want it. I'll probably release that in a week or so.

**Comment by avatar-lavventura** [comment]
@Standard8 Is the realase on? Now I am having `Quick Reply is temporarily disabled due to needing rewriting for Thunderbird 78+.` message.

**Comment by Standard8** [comment]
Just to note, in the just shipped 3.2.7, ctrl-shift-N now opens an experimental compose window that I've been working on in #1513. It isn't fully functional yet, in particular, autocomplete and progress handling could be better. However, I'm planning that the code there will be re-used for the quick reply once it gets a little further along.

If you do give it a try and find issues, please check out #1513 and comment there or file a new issue.

**Comment by jsahil730** [comment]
Hi, what's the status on this feature right now? Have you had time to look at it and finish the styling etc?

**Comment by TheModernWizard** [comment]
I second jsahil - This feature would be awesome to see completed, or even just mostly functional.

**Comment by Standard8** [comment]
I've just pushed version 4.0.0 to the add-ons site for review, it should hopefully be approved in the next couple of days.

This includes the new quick reply. It is currently very basic, supporting plain text only, no autocomplete for fields and no signatures. It also will not support encryption at this time. I plan on adding more features soon, but for now this should get things going again.

I've tested what I can and it seems to work fine, but wider testing will tell.

**Comment by Razumain** [comment]
I was pleased to see the quick reply appear in conversations and just tested it. Unfortunately it didn't manage to handle international characters. There seems to be a conversion problem between UTF-8 and ISO 8859-1. 

![image](https://user-images.githubusercontent.com/1091141/136173046-061f6723-47de-4aa5-9570-aea507f6005f.png)
