### ISSUE TITLE
Move pdf handling into Thunderbird Core

### ISSUE THREAD

**Issue by Standard8** [thunderbird-conversations/thunderbird-conversations#1417]
Currently we're shipping a copy of pdfjs and providing our own wrapper to make loading pdfs work.

I'm currently looking at integrating this functionality directly into Thunderbird as it has been a desired function for a while: https://bugzilla.mozilla.org/show_bug.cgi?id=810815

This would give Thunderbird the facility to open pdf attachments in its own preview, and it would mean that we don't need to ship and maintain the extra code.

**Comment by Standard8** [comment]
The good news here is that I've now got patches up for Thunderbird being able to preview attachments as pdf files directly. Hopefully this will get into 78, and then we won't need the pdfviewer code nor the rest of the `addon/locale` files.

**Comment by Standard8** [comment]
I've now changed the pdfviewer so that it works with 78. It has also allowed me to move the remaining locale files across to be WebExtension based. Landed this in 2694512.

Hopefully we'll still get the patches in for 78, but if not we should be ok to keep the functionality.

**Comment by Standard8** [comment]
[Bug 810815](https://bugzilla.mozilla.org/show_bug.cgi?id=810815) has just landed in Daily's nightly builds for Thunderbird 81 versions. It is a shame we missed 78, but at least it is in there now.

Once we drop support for 78, we'll be able to remove the old built-in PDF code.

**Comment by samazer** [comment]
HELP !! 

How can I restore the previous behavior of Thunderbird? In the past I was able to set the PDF viewer that I wanted - now I'm forced to Save As and open the document via a file explorer. Is there a setting that I can use to disable the internal PDF viewer in Thunderbird? 

Thanks.

**Comment by Standard8** [comment]
You can go into Preferences -> File & Attachments and then change the option next to "Portable Document Format (PDF)".

**Comment by Standard8** [comment]
Also, please use https://support.mozilla.org for questions, especially as I suspect you're not using Conversations which has always opened in an internal viewer by default.

If you are using Conversations, then there's a download button right next to the attachment icon.
