### ISSUE TITLE
S/MIME messages in conversation view are shown empty when Enigmail is active

### ISSUE THREAD

**Issue by sleeksorrow** [thunderbird-conversations/thunderbird-conversations#1442]
* **Thunderbird version:** 68.5.0
* **Thunderbird Conversation version:** 3.0.11
* **Operating System:** Kubuntu 19.10 64-bit

**What did you do?**
Click a message in a thread

**What did you expect to happen?**
I see all messages in conversations view

**What actually happened?**
S/MIME signed emails are shown empty, mail body is not being rendered.

I only observe this with S/MIME signed mails when enigmail is active. As soon as I deactivate enigmail, it is working ok. Alternatively when I choose classical view, it is showing ok. I didn't have this issue with Thunderbird 60 in the past.

This might be related to #1098

**Comment by Standard8** [comment]
Thank you for reporting this. I've seen this as well. I'll see if I can dig back through the older code and see what I missed when I updated the enigmail handling part.

**Comment by Standard8** [comment]
@sleeksorrow Any chance you could send me an S/MIME based message? I don't have a set up for that at the moment. Send it to standard8 at thebanners.uk. Thanks.

**Comment by sleeksorrow** [comment]
As soon as I can find the time, I will create a self-signed s/mime cert (I think the howto in https://www.dalesandro.net/create-self-signed-smime-certificates/ will do). Might take a few days, tho.

**Comment by ghalse** [comment]
I have the same issue. In my case, the problem occurs after I launch Thunderbird. However, if I open any of the problematic messages in a new tab, I can see the message. Thereafter things work okay in conversation view -- the act of opening one message in a new tab "fixes" it. (This doesn't happen if I open in a new window; must be a new tab.)

Since I use S/MIME routinely, I've sent an S/MIME signed message to @Standard8 per the above.

**Comment by sleeksorrow** [comment]
Thanks for saving me work. Much appreciated.

**Comment by danielrocher** [comment]
Same issue with enigmail. When I send an email with attachment.
With *Thunderbird Conversation* (**attachment is not displayed**) :
![Capture d’écran_2020-04-16_08-30-07](https://user-images.githubusercontent.com/67567/79422642-c1c16180-7fac-11ea-82a4-9cc7b631f7bb.png)

Without *Thunderbird Conversation* :
![Capture d’écran_2020-04-16_08-30-51](https://user-images.githubusercontent.com/67567/79422644-c2f28e80-7fac-11ea-866f-6a1859122c39.png)

* Thunderbird Conversation 3.0.17
* Thunderbird 68.7.0

**Comment by jkuj6** [comment]
It seems i am having a similar issue to this, but most definitely relates to this: https://github.com/protz/thunderbird-conversations/issues/1338

If you see this person here at the end, JohnS, is having the same issue on this [thread](https://sourceforge.net/p/enigmail/forum/support/thread/ae64ef500d/):


When receiving an encrypted message, i can see the encrypted content, but it wont automatically get decrypted when clicking on the message.  Only when viewing this in "Classic Reader" will the content get decrypted automatically on display.

As soon as i disabled Thunderbird Conversations, i then was able to decrypt and view the decrypted content on click of the message.

This used to work fine, but im not sure which thunderbird version it was on.  One of the updates broke the automatic decrypted message view.

@Standard8 any way i can help?

**Comment by jkuj6** [comment]
Just after i typed the message above, I just noticed as i re-enabled Thunderbird Conversations addon, before exiting TB as i clicked over the encrypted message, it decrypted in message pane! Weird.. (again, seems similar to this: https://github.com/protz/thunderbird-conversations/issues/1338)
So i re-started TB and then clicked the message again and i started having the same problem, it wouldnt decrypt unless i click on the classic reader.

**Comment by Standard8** [comment]
Sorry for the delay here, I've just remembered to fix this. I've now posted a new version for approval (3.1.18) so hopefully that'll be approved in a few days.
