### ISSUE TITLE
Shift+reply/forward does not open the compose window in HTML mode

### ISSUE THREAD

**Issue by MLopez-Ibanez** [thunderbird-conversations/thunderbird-conversations#1456]
* **Thunderbird version:** 68.4.1
* **Thunderbird Conversation version:** 3.0.17
* **Operating System:** Ubuntu Linux 18.04

**What did you do?** Shift+click in reply or forward in the top line of a message in conversion view 

**What did you expect to happen?** Open a reply/forward compose window in HTML mode

**What actually happened?** The compose window uses the default text mode. Using the classical view or the right-click menu and pressing Shift does open the compose window in HTML mode.

**Comment by Standard8** [comment]
I have to admit, this was a bit of an experiment to see if people used it or not - the new Thunderbird APIs are slightly more restricted in functionality and I'm wondering if they would be sufficient or if we should get them opened up.

It would be useful to know your use case here, is this you normally compose emails in HTML mode, and you're just wanting to reply to plain text ones with HTML, or is there something else?

**Comment by MLopez-Ibanez** [comment]
> It would be useful to know your use case here, is this you normally compose emails in HTML mode, and you're just wanting to reply to plain text ones with HTML, or is there something else?

Maybe I'm doing something wrong, but typically when I reply to/foward an email, the compose window is by default plain-text. Yet, sometimes I need HTML just to keep the source email mostly intact (Thunderbird's HTML editor is really terrible...)

It still works when using the right-click menu but it is surprising to see a different behaviour in the conversation view.

Thunderbird should have a button to switch from plain-text to HTML. This will solve all these problems in one go...

**Comment by aseelye** [comment]
Checking on this one.  Regarding the use case, my default is plain text, but when replying to someone with html mail, I'll typically hit shift+reply to not obliterate their formatting.  It's also very helpful when forwarding html email, in that say a hotel or airline reservation comes through, I forward that to tripit or someone else, forwarding as text makes just a big mess.

**Comment by MLopez-Ibanez** [comment]
> Checking on this one. Regarding the use case, my default is plain text, but when replying to someone with html mail, I'll typically hit shift+reply to not obliterate their formatting. It's also very helpful when forwarding html email, in that say a hotel or airline reservation comes through, I forward that to tripit or someone else, forwarding as text makes just a big mess.

Exactly! I am doing this everyday. I cannot understand why this is not the default behavior: If you reply to or forward an HTML email, use HTML. 

Perhaps there is something wrong in my settings or everybody is already using HTML and we should just give up and stop trying to keep some emails in text.

**Comment by Standard8** [comment]
Just to note the Thunderbird issue is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1617377

If you want to add a couple of use cases there, please feel free to, but don't overload the bug, and please don't just add "metoo" or "We need this comments". I'm sure you won't but just a warning.

From the Conversations side, I'm going to probably have to stick with these APIs long term, so coming up with an acceptable solution there is what we would need to do.

**Comment by aseelye** [comment]
Not sure if it helps, but I've found that doing a right click on the reply, then shift+click does get the desired effect.  Not sure if that's easy/possible to trace down the difference there.

**Comment by MLopez-Ibanez** [comment]
> Not sure if it helps, but I've found that doing a right click on the reply, then shift+click does get the desired effect. Not sure if that's easy/possible to trace down the difference there.

Yes, the problem is with the Conversations interface. Switching to classical reader, right-click menu, Message top menu, etc. all behave correctly when using Shift+click (Shift+Ctrl+R does not work, but it never did)

**Comment by MLopez-Ibanez** [comment]
Also to note that the work-around is easily discoverable: Do not use the Conversations buttons/icons at all and instead use right-click menu. Thus, I would not be surprised if most users will just switch to right-click rather than reporting a bug. It doesn't take very long to forget that those buttons are there and, actually, I have noticed that they have started to annoy me because I never use them, take space, sometimes clicked them by mistake, ...

**Comment by ahsanhussain** [comment]
I normally use HTML but when replying, say to a mailinglist which uses text only I have to switch the composing mode.

**Comment by makeworld-the-better-one** [comment]
@MLopez-Ibanez thanks for the tip, right-click menu buttons work when I hold Shift. But it'd be nice if this addon fixed this, as the upstream issue appears to be resolved.

**Comment by hsandt** [comment]
Was the Shift+click on Reply button at the bottom of the thread preview fixed, or replaced with some alternative? Because it doesn't seem to work in:
- Thunderbird version: 115.6.0 (64-bit)
- Thunderbird Conversation version: 4.1.6
- Operating System: Ubuntu 22.04

 Currently I must click on the reply button at the *top-right* for an HTML reply in a new popup (right-click > Reply to... also works but it's longer).

Just want to be sure of new design because I open another issue.
