### ISSUE TITLE
Redux store should be serializable

### ISSUE THREAD

**Issue by siefkenj** [thunderbird-conversations/thunderbird-conversations#1461]
The Redux store currently contains circular references and non-serilizable objects. In particular, the payload to the `"REPLACE_CONVERSATION_DETAILS"` object includes

```
summary: {
    conversation: this,
    ...
}
```
where `this` is a reference to the `new Conversation` object. This particular object causes Thunderbird 68 (on my machine at least) to freeze when attempting to print the redux store to the console.

Additionally, `neckoUrl` appears not to be searilizable (is this a special thunderbird-native wrapped object?).

Not having a serilazable store means that a lot of Redux tools can't be used and in particular, it causes an error when using Redux Toolkit to introduce the redux-thunk middleware. It also seems that the `Conversation` does a lot of storage of its own that probably should be done directly by the Redux store instead.

Getting this all sorted out should also make testing a lot easier (and possible!). However, I do not really know what the `Conversation` object is for/does nor do I know what `necoUrl` is. An explanation would be appreciated :-)

**Comment by Standard8** [comment]
The `Conversation` object is currently the piece that I would say interfaces the back-end to the actual message display. Before the react-rewrite it used to drive the display and alter the DOM directly.

It currently acts as a kind of "gatherer" - gathering the conversation data and forwarding it to the message stub as needed. It also listens for updates and things like that.

We could probably start to think about if it is possible for this to be entirely driven from the stub page. I'm not quite sure yet, it'd need thinking about a bit, as the stub isn't always persistent, but that probably doesn't matter.

In the short term, I think that the `state.conversation` references in `reducer.js` could be replaced by `Conversations.currentConversation`, the `conversation` parameter can then be removed - this was probably a hang over from when I first started setting this up (or I just did it wrong for some reason).

The `neckoUrl` is slightly different to the `msgUri` that references messages, and lets us be able to stream the message. I forget what the exact differences are. In Thunderbird terms `neckoUrl` is currently a `nsIURI` object, but I don't think we need it to be - we can (and do) get the string form of it via `.spec`.

I think we can:

* In message.js in `toReactData`, change the line to get the .spec: `neckoUrl: msgHdrToNeckoURL(this._msgHdr).spec,`
* In messageIFrame.js, drop the `.spec` references.
* In the `MSG_STREAM_MSG` action we should probably also actually use the `neckoUrl` and pass it through to the `streamMessage` call and save having to get it again.

**Comment by siefkenj** [comment]
It sounds like the `Conversation` should be in `background.js`. I guess the issue would be that there is one `Conversation` object per window, and there might be multiple windows? I will look through the code more and see if I can wrap my head around it.

**Comment by siefkenj** [comment]
PR #1462 starts to address some of these issues. I think all of this streaming stuff should be handled by a background process. The store should really contain just the data needed for the UI. With the `redux-thunk` middleware, *async* functions can be passed to `dispatch` which would be capable of communicating with the background script, fetching the needed data, and then dispatching the appropriate action to save that data to the store. At that point, `reducer.js` could become a webextension script.

**Comment by Standard8** [comment]
I was wrong about what I said in #1462 about dropping the conversation object completely there. Seems there's some strange thing going on with `Conversations.currentConversation`, where it is maybe not set early enough.

I'm not sure if we should have `Conversation` in a background script or the stub. Most of `Conversation` (and `Message` for that matter) is basically just formulating the data to feed into the display based on which messages are selected.

It feels like we could do that from `stub.xhtml` if we just query which messages are selected when we load, or if the message selection changes. This is basically what we do when you expand a conversation into its own tab anyway (i.e. when we pass `urls` as a query parameter to `stub.xhtml`).

I'm definitely open to more ideas here.

**Comment by siefkenj** [comment]
It would be great to have a clean API for querying for messages/details. I'm not sure how much mangling needs to be done to get the data into a state for conversations. If it's very little, I think that should be done directly in the experimental API. If it's a lot, it should be done in the webextension via a (stateless) function. The thing that bothers me now is that `currentConversation` is storing state that really should only be stored in Redux.

In terms of performance, I'm not sure what the implications are, but I would index all emails in a thread by `msgUri`, fetch the one we're looking at first, and then fetch the rest of them. If redux stores the order of these and which one is currently viewed, they should automagically get filled in. (I'm not sure if this will incur network costs because thunderbird lazy-loads emails or not...)

A different question: what's the difference between `msgUri` and `id` that the the webextension API uses? It would be a good idea to standardize on just one of those.

**Comment by Standard8** [comment]
> It would be great to have a clean API for querying for messages/details. I'm not sure how much mangling needs to be done to get the data into a state for conversations. If it's very little, I think that should be done directly in the experimental API. If it's a lot, it should be done in the webextension via a (stateless) function. The thing that bothers me now is that `currentConversation` is storing state that really should only be stored in Redux.

Quite agreed, I'd certainly like to start looking at moving that across.

One place to start might be to look at moving some of the data from `Message.toReactData`. We could make it so that that returns only currently necessary information/not easily obtainable from WebExtension APIs like the `id`, `msgUri`, `hasRemoteContent` and `specialTags` fields (maybe a few others).

We could then have the action handler obtain the rest of the message information from the `browser.messages.get(id)` API. We'd probably need to add a listener for updates to the fields, though we'd have to implement our own experiment, as Thunderbird doesn't have an [API for those yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1627604).

In parallel to reducing the data passed to stub, we could also look at reducing references to `currentConversation` in the reducer, e.g. marking as read we could likely change to use `browser.messages.update(id, {read: true})`.

> In terms of performance, I'm not sure what the implications are, but I would index all emails in a thread by `msgUri`, fetch the one we're looking at first, and then fetch the rest of them. If redux stores the order of these and which one is currently viewed, they should automagically get filled in. (I'm not sure if this will incur network costs because thunderbird lazy-loads emails or not...)

This was always one of protz's regrets that he made it fetch them all first before loading them. So changing that shouldn't be an issue. The only thing to make sure of is that we end up with the message display in the right place. Some of that decision code could likely also be moved across now.

> A different question: what's the difference between `msgUri` and `id` that the the webextension API uses? It would be a good idea to standardize on just one of those.

I'd like to start moving across to the id, and I think as we start moving to use more WebExtension APIs, that's going to happen naturally, and as we add more experiment APIs, we should also use the id rather than the msgUri as well - we have easy ways to convert between the two for experiments.

One slight issue is that the id isn't [currently persistent](https://bugzilla.mozilla.org/show_bug.cgi?id=1606573). For most of Conversation's that isn't an issue, but it does break the "show conversation in new tab" functionality (namely when restarting Thunderbird with one of those tabs open, which people do use). However, we can get out of that by using msgUri for the stub query params, and just translating it as soon as possible to the ids with our existing experiment API.

**Comment by Standard8** [comment]
I've just pushed a bunch more changes to reduce what stub.js is depending on by quite a bit more. We're now getting to the harder part.

One though I did just have, was potentially looking at the open-in-tab functionality of stub.js, and seeing if we can experiment with replacing the Conversations object there, and forming the data of the required messages. We would need to add some message listening as well, but it might be interesting to see what that looks like.

**Comment by siefkenj** [comment]
The changes are looking good! With `Strings` gone, I can start separating out more of the components and getting them tested. Would you have a chance to look at #1464 before new merge conflicts are introduced?

**Comment by Standard8** [comment]
> The changes are looking good! With `Strings` gone, I can start separating out more of the components and getting them tested. Would you have a chance to look at #1464 before new merge conflicts are introduced?

Sorry about that. I had actually forgotten about it when I did the last lot of changes.

**Comment by Standard8** [comment]
@siefkenj I'm currently starting to ponder a change and I'd like some of your thoughts on the best way of doing it.

What I would like to do generally, is to move most (or maybe all, eventually) of the handling conversation.js & message.js modules into stub.xhtml.

My idea currently is to do this gradually. What I'm thinking about starting with is replacing some of the data that's created with the `toReactData` functions.

So for example, in `Message.toReactData` we currently fill out things like `isJunk`, `read` and probably more.

However, we also already have the message id. We could therefore use the `browser.message.get` async API to get the message header which [includes this information](https://thunderbird-webextensions.readthedocs.io/en/latest/messages.html#messageheader).

Any suggestions on the best way of doing this? I would guess we should trigger it in the `REPLACE_CONVERSATION_DETAILS` message, and iterate over all the messages. However, as these are async calls, my knowledge of how to deal with this is limited, and I guess you probably have some suggestions.

We might also want to be doing async things when we first load the stub page as well - e.g. getting the OS.

Generally I'd like to start dropping the direct calls to functions in stdlib/misc.js and stdlib/msgHdrUtils.js and replace them with API calls where we can, or experimental APIs if necessary. A lot of those functions seem to be already implemented in the message APIs, so they seem like a good next target.

**Comment by siefkenj** [comment]
This is exciting progress! It's also the reason I've been introducing the `actions` functions, because they can handle async :-).

My suggestion would be to have a `messageActions.initializeMessageThread` async action that is dispatched in the `onComponentDidMount` function. The `initializeMessageThread` (which would technically be a thunk, not an action) will get passed a copy of `dispatch`. It can then await all the message data and dispatch update commands. A short overview of thunks is here: https://github.com/reduxjs/redux-thunk

I would have to analyze a little more to know what the correct breakdown in terms of redux actions should be, but I would suggest something like:
  * Grab a list of all message IDs in the current thread, then dispatch `'UPDATE_THREAD_IDS'`
  * Grab the ID of the active message and dispatch `'UPDATE_ACTIVE_MESSAGE_ID'`
  * Grab the content of the active message and call `'UPDATE_MESSAGE'`
  * Grab the contents of the other messages in the thread and call `'UPDATE_MESSAGE'` on each of them.

We would then create a selector `messageListSelector` which would take the thread IDs list and the messages contents and put them together into a single datastructure. In this step, for messages that haven't been loaded yet, we can insert special "loading" properties and display appropriate spinners/whatever in the GUI. (Here is an example of selectors, near the bottom: https://redux-toolkit.js.org/tutorials/intermediate-tutorial/ )

What I'm not sure of is whether we should be maintaining separate data structures for message headers and message bodies. The only reason to do separate data structures is if there are major react performance issues (for example, if when we update the `starred` status, we rerender the message content iframe, that wouldn't be so good...).

Another nice thing about this approach is that the  `initializeMessageThread` could start a listener for message updates. This listener would also have access to dispatch and so it could be in charge of updating redux whenever new message data came in (and hopefully we can fix the annoying bug of where quick-edit stops working when a reply comes while you are typing!).

**Comment by Standard8** [comment]
>     * Grab the ID of the active message and dispatch `'UPDATE_ACTIVE_MESSAGE_ID'`

We might need to be a bit careful here - sometimes when we select a message we can have more than one message selected and more than one may be unread, in which case we should be expanding all of those - there isn't just one active message. See `_tellMeWhoToScroll` for more info.

> What I'm not sure of is whether we should be maintaining separate data structures for message headers and message bodies. The only reason to do separate data structures is if there are major react performance issues (for example, if when we update the `starred` status, we rerender the message content iframe, that wouldn't be so good...).

I suspect we really want these separate. Re-rendering the iframe is definitely not a good idea.

**Comment by siefkenj** [comment]
Ah, so `activeMessages` will have to be a list! That should be easy too.

I'd be tempted to keep everything together and see if it's really a performance issue. React keeps track of references to see if an object/array changed. If we make sure the reducers preserve the objects which didn't change, React shouldn't try to update. I think there's also some magic that goes on with the `key` property when rendering a list (since normally a change on any parent property causes a rerender of all the children, but I think React tries to do some optimization).
