### ISSUE TITLE
New received emails in the currently active thread show location that would not be there otherwise

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#1483]
* **Thunderbird version: 68.8.0**
* **Thunderbird Conversation version: 3.1.2**
* **Operating System: ArchLinux**

**What did you do?**
Have an email thread opened and receive new emails in this thread

**What did you expect to happen?**
The emails to be displayed as usually

**What actually happened?**
Those emails were correctly displayed, but addon added some additional visual piece about the folder (We currently are in the general inbox) the email arrived in. This information is not here usually, and won't be here if user select another thread and go back to the thread they were on.

See joined screenshot to see the kind of visual element it is.
![Screenshot from 2020-05-18 18-24-29](https://user-images.githubusercontent.com/709500/82237373-cffcf780-9935-11ea-9ffa-ab5e6f1ae866.png)

**Comment by Standard8** [comment]
Thanks for the report. I see this as well.

**Comment by Standard8** [comment]
Hmm, I think I fixed this a while ago and I forgot to close it.
