### ISSUE TITLE
Empty conversation / broken items after deleting attachment.

### ISSUE THREAD

**Issue by mgenet** [thunderbird-conversations/thunderbird-conversations#1496]
* **Thunderbird version: 68.9.0**
* **Thunderbird Conversation version: 3.1.6**
* **Operating System: MacOS**

**What did you do?**

Deleted an attachment.

**What did you expect to happen?**

See an email with deleted attachment.

**What actually happened?**

The emails are still visible in the list pane (i.e., subject, correspondents, date, etc), but the conversation pane is empty. Basically I cannot see the content of the emails anymore. If I move to another thread it is ok. But when I come back to this thread the conversation pane is still empty.

**Comment by Standard8** [comment]
Please can you check the error console for any messages appearing when you select the message? You can find it under the three-bar menu -> Tools -> Developer Tools -> Error Console.

**Comment by Standard8** [comment]
I think I just reproduced this. If you're seeing something like:
```
Error: "Message no longer exists"
    toReactData chrome://conversations/content/modules/message.js:384
```
then it is the same thing.

Restarting Thunderbird should allow you to access the messages again.

Unfortunately, this is a Thunderbird bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1645595

**Comment by mgenet** [comment]
Thank you!

Yes, I am getting the same message. One thing though, is that if I revert to 3.0.18 I don't have this problem.

**Comment by Standard8** [comment]
> Yes, I am getting the same message. One thing though, is that if I revert to 3.0.18 I don't have this problem. (Problem is present with 3.1.6 and 3.1.9.)

3.1.9 is starting to use dedicated APIs that Thunderbird is now providing for add-ons to use. These are going to be a lot better for long-term stability and reduced maintenance, unfortunately there's still a few bugs in them that we're discovering as we go.

**Comment by Buratinator** [comment]
This problem briefly went away for me a few weeks ago, but came back today, after Conversation updated to 3.2.33.

**Comment by Standard8** [comment]
The [main Thunderbird issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1645595) has now been fixed in Thunderbird 91. Thunderbird 91 has just been released, but it'll likely be a month or two before updates are released to it.

With Thunderbird 91, you should now be able to de-select and re-select a different message and it should start working again. There's still an issue that Thunderbird doesn't notify WebExtensions of the change, so immediate updates will still be broken for the time being.

**Comment by Standard8** [comment]
Actually with Thunderbird 91, this should be properly fixed now. The extra issue I thought was still there, has been resolved in the fix in Thunderbird 91, and from a quick test it seems like this works properly now.

**Comment by Standard8** [comment]
Thunderbird 91 is now out & is starting to roll out via automatic updates to some users, I believe it is available to all users using the manual update mechanism (via help -> about). If not, then it should be within the next couple of weeks.
