### ISSUE TITLE
Is it possible to apply 1-line compact header?

### ISSUE THREAD

**Issue by avatar-lavventura** [thunderbird-conversations/thunderbird-conversations#1500]
Is it possible to apply 1-line compact header like this one does (https://addons.mozilla.org/thunderbird/addon/compactheader/)? and also remove the circle next to each sender that contains their initial name

<img width="165" alt="image" src="https://user-images.githubusercontent.com/18537398/84761308-f021e400-afd1-11ea-8167-6c5f7a943d78.png">

For example, I don't want to see circle contains KM

**Comment by Standard8** [comment]
> Is it possible to apply 1-line compact header like this one does (https://addons.mozilla.org/thunderbird/addon/compactheader/)?

Conversations' message headers are already a single line, so I don't see why you need that as well. Is there something you're missing? (or I'm missing?)

> <img alt="image" width="165" src="https://user-images.githubusercontent.com/18537398/84761308-f021e400-afd1-11ea-8167-6c5f7a943d78.png">
> 
> For example, I don't want to see circle contains KM

You could possibly do this with a userChrome.css modification. I'm not sure if I would accept an option for it or not. I don't remember seeing many requests for that and I prefer to keep the options as simple as possible.

**Comment by avatar-lavventura** [comment]
Sorry for misguiding, to be clear I just don't want to see `KM` in a circle on the example image I shared, which takes more space. I get used to compact view like without the initial letters inside a circle.

Ex:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/18537398/87252245-2429e100-c47a-11ea-9ee0-2e4519562926.png">

**Comment by Standard8** [comment]
Sorry, I don't think I'm going to provide an option for this. At best it'd save at most around 8 or 9 pixels.

Given that we haven't had any other complaints about it, I don't think it is worth it.
