### ISSUE TITLE
Wrong display of senders

### ISSUE THREAD

**Issue by Poreb** [thunderbird-conversations/thunderbird-conversations#1506]
* **Thunderbird version: 68.9.0 **
* **Thunderbird Conversation version: 3.1.13**
* **Operating System: Windows 10 family**

**What did you do?**
Read my emails with thunderbird conversations.

**What did you expect to happen?**
Expected classical display

**What actually happened?**
Sometimes wrong senders are displayed in the header : a long list of senders not related with email is displayed, even when there is only one sender for this email. (see snapshot)

![capture_thunderbird](https://user-images.githubusercontent.com/67378028/85573968-a327b880-b636-11ea-852f-b89f20f1972d.png)

**Comment by Standard8** [comment]
Please can you give a bit more detail? I'm struggling to understand the issue here, though the `mailto` does look wrong.

If you go to the three dots menu at the side of the message, and click `View in Classic Reader` do they display correctly there?

If they do, can you try viewing the message source, and look for the to/from lines. Please can you paste them here - after changing the names and email addresses. The structure of those is what I would need to see.

**Comment by Standard8** [comment]
@Poreb, please check with the just released 3.1.17, if that doesn't work, please provide more detail, I'm sorry but I really can't understand the issue you are attempting to report.

**Comment by Poreb** [comment]
Sorry for the delay in answering your message.

It seems to do the same with the 3.1.17 version.

When I view in classic reader, senders are displayed correctly. 

Here are the two/from lines : 

```
To: P***** Name <p.name@mycompany.fr>
References: <de801041-beb4-514c-47a2-bccc91a76b24@mycompany.fr>
 <6cc50bae-7bf5-9f44-4f53-477458fff01a@mycompany.fr>
 <48540865-a8c6-89b6-9403-50b478dfd07a@mycompany.fr>
 <aba750d4-8c74-4701-8048-f5d1583f71dc@localhost>
From: E***** Name <e.name@mycompany.fr>
```
We sometimes use alias for different groups, for example team1@mycompany.fr, which redirects to all the persons in team1, and I have a ldap adress book connected in thunderbird. 
Maybe these elements could explain ?

Thanks a lot for your answer,

**Comment by Standard8** [comment]
The only sender in that email you've shown is the From: field. The To: line is who it is sent to.

The References line is just references to other emails that were replied to - they're not senders. You should be able to see the references if you click the "i" (show details) button on the message header bar.

If that doesn't explain it, please could you attach a couple of screenshots that show a message in the classic reader and in the Conversation view - that might help my understanding a bit more.

**Comment by Poreb** [comment]
I found out where the problem came from, it seemed to be linked to wrong parameters in my adress books in thunderbird.

Thank you a lot for your help!

**Comment by Standard8** [comment]
Glad you found the issue, thank you for letting me know.
