### ISSUE TITLE
Always show remote content does not persist. 

### ISSUE THREAD

**Issue by hyhugh** [thunderbird-conversations/thunderbird-conversations#1511]
* **Thunderbird version:** 68.10.0 (64-bit)
* **Thunderbird Conversation version:** 3.1.17
* **Operating System:** Windows 10 64bit

this issue is the same as https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1236
As the old one is closed (and it's been nearly three years), so I raise this one.

**What did you do?**
In the default version of Thunderbird when you select an email as safe it will load the content from that domain/user from that point on. The same function while using this addon does not work.

**What did you expect to happen?**
Anytime that you select always show remote content from `user@example.com` it should save that choice for future emails.

**What actually happened?**
This preference is never actually saved. It prompts to show content and always show content every time you view the email or future emails from the same users.

**Comment by Standard8** [comment]
Thank you for filing, I've found the issue - looks like a copy and paste error. Completely different to #1236 and it is always worth filing a new issue rather than commenting on old closed ones.

I'm working on fixing this - I'm taking the opportunity to clean up the code a bit as well.

**Comment by hyhugh** [comment]
thanks a lot!
