### ISSUE TITLE
Missing avatars

### ISSUE THREAD

**Issue by roughnecks** [thunderbird-conversations/thunderbird-conversations#1512]
* **Thunderbird version:**
68.10.0 (32 bit)

* **Thunderbird Conversation version:**
3.1.19

* **Operating System:**
Windows 10 Pro x64 Ita

**What did you do?**
I opened some old messages in archive between me and people in my address book

**What did you expect to happen?**
I expected to see their avatars

**What actually happened?**
I can see avatars in my address book but TB-Conversations doesn't show them, it just shows the placeholder for a missing image.
Most of the avatars in my address book are saved on disk and selected manually from the edit contact sheet in TB.

If I set a new image for any contact in address book, TB-Conversions starts displaying it without issue.

**Comment by Standard8** [comment]
> I can see avatars in my address book but TB-Conversations doesn't show them, it just shows the placeholder for a missing image.
> Most of the avatars in my address book are saved on disk and selected manually from the edit contact sheet in TB.

If you look at the avatar in the photo pane for the contact on the address book, what does it display there? Just the filename or a path as well?
 
> If I set a new image for any contact in address book, TB-Conversions starts displaying it without issue.

Is that setting the image as a file from disk? Does that still persist after a restart?

**Comment by roughnecks** [comment]
I'm not sure what you mean, but I can see this in each contact's Photo tab: https://i.imgur.com/r5PzDLK.jpeg
And yes, I'm setting the image from pictures on my disk (several are fetched by "gContactSync" tho).

**Comment by Standard8** [comment]
@roughnecks Please could you try and get some debug from some of the broken versions? Here's what to do:

1) Download and install this version: https://www.thebanners.uk/conversations-3.1.19-debug.xpi
2) From the add-ons page, select Options (or Preferences) next to Thunderbird Conversations.
3) Near the bottom, turn on the Debugging option.
4) Restart Thunderbird
5) Go to the three-bar menu -> Tools -> Developer Tools -> Error Console (this will open a new window)
6) Select a message where you're seeing the contact photo is displayed wrongly
7) Go back to the error console and look for lines like:

```
Conversations.Contact: phototype file contact.js:153:11
Conversations.Contact: PhotoURI is: file:///Users/standard8/Downloads/myphoto.png contact.js:155:13
```

Copy and paste a couple of the failing examples here.

I think I might now know what this is, but having the extra debug would help confirm it.

**Comment by roughnecks** [comment]
> @roughnecks Please could you try and get some debug from some of the broken versions? Here's what to do:
> 
> 1. Download and install this version: https://www.thebanners.uk/conversations-3.1.19-debug.xpi

What do I need to do to go back to "standard" Conversation release version then?

**Comment by Standard8** [comment]
> What do I need to do to go back to "standard" Conversation release version then?

The debug bit here only adds a few extra logging statements, so you won't really notice any difference. If you want to revert to the standard release, then you can do that via re-downloading from the [main page](https://addons.thunderbird.net/thunderbird/addon/gmail-conversation-view/) and installing again, or you can just wait for the next release to come out.

**Comment by roughnecks** [comment]
I believe I found something:

`Array(3) [ "GF", "GF", "GF" ]
conversation.js:679:9
Conversations.Contact: phototype file contact.js:153:11
Conversations.Contact: PhotoURI is: file:///C:/Users/roughnecks/AppData/Roaming/Thunderbird/Profiles/5u2aehxv.roughnecks/gcontactsync/photos/57dc639189a82649_1562507262780.jpg contact.js:155:13
Conversations.Contact: phototype file contact.js:153:11
Conversations.Contact: PhotoURI is: file:///C:/Users/simca/Pictures/Avatar/9422d92ab9436282f21e3febb689f94b1758070d_full_256.jpg contact.js:155:13
Conversations.Contact: phototype file contact.js:153:11
Conversations.Contact: PhotoURI is: file:///C:/Users/simca/Pictures/Avatar/9422d92ab9436282f21e3febb689f94b1758070d_full_256.jpg contact.js:155:13
Conversations.Contact: phototype file contact.js:153:11
Conversations.Contact: PhotoURI is: file:///C:/Users/roughnecks/AppData/Roaming/Thunderbird/Profiles/5u2aehxv.roughnecks/gcontactsync/photos/57dc639189a82649_1562507262780.jpg contact.js:155:13
Conversations.Contact: phototype file contact.js:153:11`

Some images have a path with my old username (in Windows), since I installed Windows in this new PC and copied over TB's profile... So the correct one should be "file:///C:/Users/simca/" instead of "file:///C:/Users/roughnecks/".

**Comment by roughnecks** [comment]
Also, sorry for that paste, not sure why it's not returning.

**Comment by Standard8** [comment]
Ah that would be it. It would probably be hard for us in this case to fall back, at least for the short term. Once we resolve #1475 then we'd like end up falling back to the placeholder.

**Comment by roughnecks** [comment]
Ok, so I just need to wait? Thanks btw

**Comment by Standard8** [comment]
The easiest way to change the path would be this.

- Back up your profile (just in case, the *.mab files are the most important here).
- Open up the Error Console again
- Enter the following as one line in the Error Console:

```
for (let ab of MailServices.ab.directories) { for (let card of ab.childCards) { let photouri = card.getProperty("PhotoURI", ""); if (photouri) { photouri = photouri.replace("file:///C:/Users/simca/", "file:///C:/Users/roughnecks/"); console.log(photouri); card.setProperty("PhotoURI", photouri); ab.modifyCard(card) } } }
```

This will go through all your address books and cards, replacing `file:///C:/Users/simca/` with `file:///C:/Users/roughnecks/`.

Assuming all the photos are still in the same relative sub-directories, that should work.

**Comment by roughnecks** [comment]
> This will go through all your address books and cards, replacing `file:///C:/Users/simca/` with `file:///C:/Users/roughnecks/`.

It was the reverse, replace roughnecks with simca, so I adjusted it...

> Assuming all the photos are still in the same relative sub-directories, that should work.

It seems to have done the trick. Thanks a bunch @Standard8

**Comment by Standard8** [comment]
Excellent, I'm glad that worked.
