### ISSUE TITLE
Top right button to edit a message does nothing

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#1514]
* **Thunderbird version:** 68.10.0
* **Thunderbird Conversation version:** 3.1.19
* **Operating System:** ArchLinux

**What did you do?**
Tried to click the edit button of a draft within a thread

**What did you expect to happen?**
To open up the edition window.

**What actually happened?**
Nothing

The button with the issue is the top-right one of the email, as visible on the screenshot joined. There's another edit button on bottom right that do work. It's also visible on the screenshot.

![Screenshot from 2020-07-26 17-00-17](https://user-images.githubusercontent.com/709500/88482456-92ce6a80-cf61-11ea-9801-020f36fd504c.png)

**Comment by Standard8** [comment]
Thank you for the report. I found the issue, and I'll push out a new version soon.
