### ISSUE TITLE
Message Window Positioning

### ISSUE THREAD

**Issue by GwentLarry** [thunderbird-conversations/thunderbird-conversations#1515]
Just moving from Apple Mail to Thunderbird for the first time.

* **Thunderbird version: 78.0.1
* **Thunderbird Conversation version: 3.1.19
* **Operating System: MacOS 10.15.6

**What did you do?**
Open threaded message by double click on message.

**What did you expect to happen?**
Message window to open where last message window was positioned.

**What actually happened?**
Message window always opens on the left side of the screen, at the same width and full screen height. It does, however, show the threaded conversation as expected.

However, if I open a message from either the keyboard (Command-O) or menu -> Message -> Open Message the message window opens where it was last positioned. But, it does not show the threaded conversation.

I would supply screenshots to show more clearly what is happening, however, something (Thunderbird or Conversations ?)seems to have killed the Screenshot app ...

**Comment by Standard8** [comment]
I've taken a look at this, but at the current time it unfortunately isn't going to be easy to solve. It appears to be a combination of things, mainly how we're loading the new window (tech: with a custom API using a chrome url, rather than a webextension url).

Once we get a bit further along with some of the current rewrite we might be able to use some of the newer APIs which would hopefully solve this.

**Comment by dbio26** [comment]
Hi,

I am in the same situation but with different OS

    **Thunderbird version: 78.2.1
    **Thunderbird Conversation version: 3.1.22
    **Operating System: Win 10 home 1903

messagges open at full-screen heigh, left side with fixed width, meawhile if I disable this exstension messagges opens "normally" with same dimensions and position of the last message.

**Comment by Standard8** [comment]
I've just pushed a fix for this, which will be in the next version of Conversations, but will only apply to Thunderbird 91 builds and later.

Thunderbird 91 is currently in beta, due to be released in just under two weeks time.
