### ISSUE TITLE
Disabled on start of Thunderbird

### ISSUE THREAD

**Issue by conchra** [thunderbird-conversations/thunderbird-conversations#1516]
* **Thunderbird version:** 78.0.1
* **Thunderbird Conversation version:** 3.1.19
* **Operating System:** Windows 10 Pro (1909)

**What did you do?**
1. Create new TB profile
1. Setup email (Office 365)
1. Install TB conversations

**What did you expect to happen?**
1. TB conversations will work each time TB is launched

**What actually happened?**
1. After a few times closing and restarting TB, TB conversations no longer starts
1. In Addon-Ons Manger, disable and enable TB conversations and it will work for the duration that TB is open
1. I have tried with TB conversations as the only add-on and with other add-ons enabled/disabled
    * Lightning Calendar Tabs 2.5
    * Mail Merge 7.1
    * TbSync 2.16; Provider for EAS 1.16; Provider for CalDAV & CardDAV 1.16
    * QuickText 3.1
    * ThunderHTMLedit 3.1.5

**Comment by Standard8** [comment]
Please could you try turning on debugging under Conversation's preferences (near the bottom), then when this fails, please do this:

* Go to the three-bar menu -> Tools -> Developer Tools -> Error Console.
* In that console, right-click and select All, then right-click again and select "Copy message".
* Then paste that output into a comment here.

I'd expect this needs to be done straight away after startup - as soon as you notice. It is likely the earlier messages on the console will be the useful ones, and leaving it too long may loose those.

**Comment by conchra** [comment]
I turned on TB conversation debugging and re-started TB. The error console output is (BTW you can get the error console to start with TB using the command line argument `-jsconsole`):

```js
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
Conversations.api: startup api.js:255:17
[OverlayManager] Reading file: chrome://quicktext/content/quicktext.xul
[OverlayManager] Reading file: chrome://quicktext/content/skin/quicktext.css
[OverlayManager] Reading file: chrome://quicktext/content/main.xul
[OverlayManager] Reading file: chrome://quicktext/content/skin/quicktext.css
[OverlayManager] Reading file: chrome://quicktext/content/quicktext.xul
[OverlayManager] Reading file: chrome://quicktext/content/skin/quicktext.css
[OverlayManager] Reading file: chrome://quicktext/content/main.xul
[OverlayManager] Reading file: chrome://quicktext/content/skin/quicktext.css
[OverlayManager] Injecting into new window: chrome://global/content/commonDialog.xhtml
[OverlayManager] Injecting into new window: chrome://devtools/content/webconsole/index.html
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 658"  data: no] 2 L10nRegistry.jsm:658:19
[OverlayManager] Injecting into new window: chrome://messenger/content/messenger.xhtml
[OverlayManager] Loading: chrome://quicktext/content/main.js
[OverlayManager] Loading: chrome://quicktext/content/scripts/locales.js
[OverlayManager] Injecting: chrome://quicktext/content/main.xul
[OverlayManager] Stylesheet: chrome://quicktext/content/skin/quicktext.css
[OverlayManager] Adding <quicktext-settings-sep> (menuseparator)  insertbefore <prefSep>
[OverlayManager] Adding <quicktext-settings> (menuitem)  insertbefore <prefSep>
Successfully loaded OTR library libotr-5.dll from C:\Data\__Apps\Thunderbird\App\libotr-5.dll OTRLib.jsm:43:13
Request to access cookie or storage on “https://addons.thunderbird.net/user-media/addon_icons/702/702920-64.png?modified=1596280494” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.
Unknown localization message status.default timezone has been found. ExtensionCommon.jsm:2005
Unknown localization message helplink.default timezone has been found. ExtensionCommon.jsm:2005
Unknown localization message status.the iana timezone <america/nuuk> cannot be mapped to any exchange timezone. ExtensionCommon.jsm:2005
Unknown localization message helplink.the iana timezone <america/nuuk> cannot be mapped to any exchange timezone. ExtensionCommon.jsm:2005
Unknown localization message status.the iana timezone <antarctica/troll> cannot be mapped to any exchange timezone. ExtensionCommon.jsm:2005
Unknown localization message helplink.the iana timezone <antarctica/troll> cannot be mapped to any exchange timezone. ExtensionCommon.jsm:2005
```

Disabling and re-enabling TB Conversation results in the error console output:

```js
Conversations.msgWindowApi: shutdown, isApp= false api.js:226:9
sendRemoveListener on closed conduit gconversation@xulforum.org.16 ConduitsChild.jsm:108
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIMsgDBView.removeColumnHandler] contactsApi.js:240
TypeError: win.conversationUndoFuncs is undefined msgWindowApi.js:235:36
Conversations.api: startup api.js:255:17
Conversations.api: monkey-patching... api.js:118:7
No chrome package registered for chrome://enigmail/content/modules/constants.jsm
Conversations.msgWindowApi: Intercepted message load, 1 message(s) selected msgWindowApi.js:618:11
Conversations.msgWindowApi: New conversation: 1 Old conversation: null msgWindowApi.js:510:15
Conversations.Conversation: Outputting 
Array(3) [ "GF", "GF", "GF" ]
conversation.js:679:9
Conversations.Message: A message is selected: imap-message://XXXXX%40XXXXX@localhost/INBOX#138121 message.js:573:9
```

**Comment by conchra** [comment]
I have done a little more investigating. TB 78+ on Windows asks for the master password _before_ the main screen opens whereas previously the master password was entered _after_ the main screen opened.

**Steps to reproduce**
1. Disable TB master password
1. Re-start TB
1. TB Conversations loads as expected with TB 
1. Enable master password
1. Re-start TB
1. TB Conversations fails to load.

**Comment by Standard8** [comment]
Thank you for finding that. I'll try it out later, my suspicion is that the master password dialog is breaking how we hook into the main window on startup.

One thing that might be interesting to try is this: when you're in the failed state, open a new window and see if Conversations kicks in - it'll only kick in for the new window most likely though.

**Comment by conchra** [comment]
Thanks for the quick reply.

I can open a single message (not a thread) in a new window, which looks like a 'normal' TB message. This is the case whether TB Conversations is in a failed state or working.

I can move the Calendar to a new window (right click on Calendar tab, select 'Move to New Window'), which also opens the Inbox as a tab in that new window.

**TB Conversations in failed state**
1. Move calendar to new window
1. Old window, remains in failed state
1. New window, Inbox is in failed state.

**TB Conversations working (after disable/enable)**
1. Move calendar to new window
1. Old window, TB Conversations remains working as expected
1. New window, Inbox is in **failed** state.

**Comment by Standard8** [comment]
Thank you for that. Some of Thunderbird's internal window handling had changed in-between 68 and 78 and I'd missed that. I've got a patch for this now, there's something else I'm looking at first, but I'll cut a new version soon and hopefully it'll be out in a few days.
