### ISSUE TITLE
Conversations regularly stops working and cannot expand conversations

### ISSUE THREAD

**Issue by kobaz** [thunderbird-conversations/thunderbird-conversations#1520]
* **Thunderbird version:**  68.9.0
* **Thunderbird Conversation version:** 3.1.19
* **Operating System:** Linux Debian Buster

**What did you do?** 
Open email

**What did you expect to happen?**
Conversations list shows for selected email/conversation

**What actually happened?**
Previous email still shows.

1) Previous email clicked hilighed in red.
2) Previous email loaded correctly
3) Switched to the top-most email
4) Previous email still showing

![image](https://user-images.githubusercontent.com/1695852/89430154-6c9c8d80-d70c-11ea-8753-6098811ff241.png)

**Comment by Standard8** [comment]
Please can you go to Tools -> Developer Tools -> Error Console and check for any errors around the time you select a new message and it doesn't switch to it?

It might be useful to turn on Debugging in Conversations' add-on preferences before doing so as well (and restart).

**Comment by Standard8** [comment]
Unfortunately without more information, there's not much we can do here.
