### ISSUE TITLE
Treat Fwd and FW as the same, and group messages

### ISSUE THREAD

**Issue by evolverine** [thunderbird-conversations/thunderbird-conversations#1521]
* **Thunderbird version:** 68.10.0
* **Thunderbird Conversation version:** 3.1.19
* **Operating System:** Ubuntu 20.04.1 LTS

**What did you do?**
Installed the add-on, and have been using it for a few weeks

**What did you expect to happen?**
Two emails with the subject "FW: Scrisoare de indexare" and "Fwd: Scrisoare de indexare" to be grouped into a conversation

**What actually happened?**
they are displayed separately

I don't know if the "FW" came from the user's locale settings, or some peculiar email client's forward label, but they are clearly the same in this situation. I can imagine there might be a lot of variation in this in various locales, so I'm not assuming it's a trivial fix.

**Comment by Standard8** [comment]
Are you seeing this separation in the message list or in the message pane where the message is displayed?

If this is the message list, then you need to [file a bug on Thunderbird](https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird) - Conversations only groups the messages in the message pane, it doesn't handle deciding which messages should be grouped.

**Comment by evolverine** [comment]
indeed it's in the list. Thank you, I will open a bug with Thunderbird.
