### ISSUE TITLE
PGP-Inline not working with TB Conversations

### ISSUE THREAD

**Issue by fdellwing** [thunderbird-conversations/thunderbird-conversations#1523]
* **Thunderbird version:** 68.10.0 x64
* **Thunderbird Conversation version:** 3.1.20
* **Operating System:** Kubuntu 18.04 x64

**What did you do?**

Opened an encrypted mail (Inline-PGP)

**What did you expect to happen?**

The message being decrypted and shown.

**What actually happened?**

No decryption happens and ciphertext is shown.

**How to reproduce?**

Send yourself a new mail and choose `Protocol: Inline-PGP` instead of default `Protocol: PGP/MIME` for encryption.

**Comment by manicmarvin** [comment]
Same issue in **Thunderbird 78.2.2 (64-bit)** with Thunderbird Conversations **v3.1.22**.
Do you think this is a critical issue?

**Comment by fdellwing** [comment]
Do you have any insights on how many Conversation users, use Enigmail?

**Comment by Standard8** [comment]
The TB 78.x issue is #1529 

I've not looked into this issue. I suspect it is a case that just hasn't been covered.

If anyone has javascript experience, I'm quite happy to accept patches.

**Comment by fdellwing** [comment]
The problem is quite substantial in communication with non Enigmail users, for me #1524 is much more worse. I'm sadly not able to provide a patch for this or the other issue.

**Comment by manicmarvin** [comment]
For me 3.2.2 has resolved this. Perhaps for others as well. Thanks @Standard8

**Comment by fdellwing** [comment]
This is working with TB Conversations 3.1.24, thanks :)
