### ISSUE TITLE
PGP/MIME + Attachment not working with TB Conversations

### ISSUE THREAD

**Issue by fdellwing** [thunderbird-conversations/thunderbird-conversations#1524]
* **Thunderbird version:** 68.10.0 x64
* **Thunderbird Conversation version:** 3.1.20
* **Operating System:** Kubuntu 18.04 x64

**What did you do?**

Opened an encrypted mail (PGP/MIME) with attachement.

**What did you expect to happen?**

The message being decrypted, shown and attachment being shown as with unencrypted mail.

**What actually happened?**

The message is decrypted and the content is shown, but no attachment is shown.

**How to reproduce?**

Send yourself a new mail (`Protocol: PGP/MIME`) with any attachment.

**Comment by Standard8** [comment]
testssdsfsdfsdfsdfsfsfsfsfssfd

**Comment by roblem** [comment]
If I need to open a new issue, I am happy to do so but this seems to be related:

If I send an **unencrypted** message with an attachment and additionally add my pgp signature from the options menu in the composer window, the attachment fails to appear in the conversation after I send it.  The message is marked as "signed" but not attachment is visible.  This is with the conversation's "I Love Attachment's" mode on (or off).

**Comment by stratosjl** [comment]
> If I need to open a new issue, I am happy to do so but this seems to be related:
> 
> If I send an **unencrypted** message with an attachment and additionally add my pgp signature from the options menu in the composer window, the attachment fails to appear in the conversation after I send it. The message is added to the conversation, and is marked as "signed", with viewable body but the attachment is not visible. This is with the conversation's "I Love Attachment's" mode on (or off).

I have the exact same problem

**Comment by Standard8** [comment]
> I have the exact same problem @Standard8

Unfortunately I don't have much time at the moment, and I'm concentrating on bigger issues that affect more people.

I'm quite happy to accept patches (and point people at where to look if they are interesting in fixing), but commenting with "me too" style comments really does not help.

**Comment by Standard8** [comment]
4.0.17 has now been released with some fixes which should mean encrypted attachments are displayed more of the time.

If you're still having an issue after this, please file a new issue.
