### ISSUE TITLE
Certain characters displayed weirdly

### ISSUE THREAD

**Issue by mcab** [thunderbird-conversations/thunderbird-conversations#1525]
* **Thunderbird version:** 80.0b3
* **Thunderbird Conversation version:** 3.1.20
* **Operating System:** Windows 10, Version 2004, OS build 19041.450.

**What did you do?**
Opened up an email.

**What did you expect to happen?**
Quotes and emojis to be properly escaped.

**What actually happened?**
![Thunderbird Conversations with weirdly escaped characters](https://user-images.githubusercontent.com/4522043/90297259-bdb22d00-de42-11ea-8471-62227bb482ee.png)

Note the `â€™`.

Switching to the Classic Reader / disabling the extension has it render properly:

![Classic Reader renders properly](https://user-images.githubusercontent.com/4522043/90297293-dcb0bf00-de42-11ea-8332-50d01274e21a.png)

**Comment by Standard8** [comment]
Thank you for filing this. Thunderbird changed something with character sets in TB 79, and I thought I had fixed it, obviously not. Having poked around a bit more, I've just found the fix.

That will get pushed out in the next week or so.

**Comment by mcab** [comment]
Thanks for fixing it promptly, and giving a timeline around the next release! Cheers.

**Comment by ikirudennis** [comment]
It doesn't seem like this is fixed.

**Comment by jacob2512** [comment]
Same issue for me as well with TB 81.0b2 and TBC 3.1.22.
Checked the Debug Console, and this message appears every time I get garbled text in my Preview pane:

The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

NOTE:
This seems to be an issue only in the Message preview pane.
When I open the same mail on a new tab or use the 'view using the classic reader' option,
then close that tab and come back to the mail, the text is magically fixed. BUT, when i click on
any other mail, then come back to the same mail, it is garbled once again.

**Comment by jacob2512** [comment]
Opened new issue #1528.
