### ISSUE TITLE
Quoted text not being collapsed

### ISSUE THREAD

**Issue by eyrewiut** [thunderbird-conversations/thunderbird-conversations#1527]
* **Thunderbird version:** Thunderbird 78.2.0 (64-bit)
* **Thunderbird Conversation version:** 3.1.22
* **Operating System:** Mac OSX High Sierra 10.13.6

**What did you do?**
When reading emails, quoted parts of the email (the message history) isn't collapsed. I had originally thought this wasn't a feature of the addon but reading the addon page recently I realised it is, 

I wondered if this was because I am using gmail? I don't see anything gmail specific in the quoting.js code while some other providers are in there...

**What did you expect to happen?**
The quoted text would be hidden at first with a toggle or button or something like in gmail or outlook etc to show/hide it if  needed.

**What actually happened?**
The full quoted message history is shown at the bottom of my email (which is quite long in some conversations)

**Comment by Standard8** [comment]
Thank you for filing, definitely an issue and regression when Conversations is running with 78.

Not quite sure what yet, will investigate.

**Comment by hellman** [comment]
Same bug, Thunderbird 78.3.1 (64-bit), conversations 3.1.22, Ubuntu 20.04

Nested quotes have colored bars on the left but nothing is collapsed.

**Comment by Standard8** [comment]
I've just found the fix. Hopefully will release it sometime next week.
