### ISSUE TITLE
Message Preview pane displays garbled text (broken encoding in daily/beta builds of Thunderbird)

### ISSUE THREAD

**Issue by jacob2512** [thunderbird-conversations/thunderbird-conversations#1528]
* **Thunderbird version:** 82.0b1
* **Thunderbird Conversation version:** 3.1.22
* **Operating System:** Win 10 Pro, Version 1903, Build 18362.1016

**What did you do?**

1. Clicked on a mail and observed the mail text when it showed up in the Message Preview pane,
    and also after clicking on another mail, then clicking back to the same mail.
    In all these cases, some of the text was garbled:
![mail_on_preview_pane](https://user-images.githubusercontent.com/2695126/91673452-03c8eb00-eae9-11ea-98e2-2f74b1f9037a.png)

2. Observed the same mail text after double clicking on it to open it in a new tab,
    and also after using the 'view using the classic reader' to display it in a new tab.
    Closed the new tab and observed it again in the main tab.
    Disabled the extension and observed it again in the main tab.
    In all these cases, the text was non-garbled:
![mail_on_new_tab](https://user-images.githubusercontent.com/2695126/91673487-2fe46c00-eae9-11ea-89d4-fdc16f7361a0.png)

3. Inspected the extension in the Debug Add-ons console, and 
    observed that this warning was displayed every time garbled text came up in a mail, which may be relevant:

   The character encoding of the HTML document was not declared. The document will render with garbled text in some browser 
   configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must 
   be declared in the document or in the transfer protocol.

**What did you expect to happen?**
All text should have been displayed properly.

**What actually happened?**
Some of the text was garbled.

**Comment by Standard8** [comment]
3.2.2 was released earlier today and I believe this is now fully fixed.

**Comment by jacob2512** [comment]
Been monitoring for recurrence - not seeing it, even for previous extreme cases... thanks!
