### ISSUE TITLE
Can we have the option to sort newest to oldest pls?

### ISSUE THREAD

**Issue by stibinator** [thunderbird-conversations/thunderbird-conversations#1531]
Great extension, but can we have the option of sorting so the newest message is at the top. That would be ace.

**Comment by Standard8** [comment]
Per the [FAQ on the wiki](https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/FAQ#message-display), the added complexity of supporting that is not something we want to implement/support at this time, as we are trying to keep up with (and get ahead of) all the recent changes in Thunderbird.

It is possible we might do this in a year or two, but until the maintenance issues are sorted, we're not going to be moving far forward with different display features.
