### ISSUE TITLE
 openpgp-broken-exchange-info dialog not shown

### ISSUE THREAD

**Issue by riedel** [thunderbird-conversations/thunderbird-conversations#1533]
* **Thunderbird version: 78.2.1**
* **Thunderbird Conversation version: 3.1.22**
* **Operating System: Windows 10**

**What did you do?**
I display an encrypted message forwarded through an MS-Exchange server

**What did you expect to happen?**
As in classic view I would expect the following banner dialog: "This is an OpenPGP message that was apparently corrupted by MS-Exchange. If the message contents isn't shown as expected, you can try an automatic repair." with a clickable "Repair message"
![grafik](https://user-images.githubusercontent.com/566485/92964421-5654c080-f474-11ea-8788-dd9bee01e2b6.png)

**What actually happened?**
There is no option to repair the message.

**Comment by Standard8** [comment]
This might now be fixed with Thunderbird 91 & Conversations 4.0.0 that I've just published for review (should be approved in the next few days).

If it isn't please check again the Thunderbird classic view behaviour & feel free to reopen if it is still broken.
