### ISSUE TITLE
Attachment list not showing with keep messages turned off.

### ISSUE THREAD

**Issue by GrupoWebex** [thunderbird-conversations/thunderbird-conversations#1534]
Attachment list is not showing when "Sync and storage" > "Keep messages" is OFF.
"Classic view" show it correctly.
Same problem on Windows 7.

* **Thunderbird version:** 68.10.0
* **Thunderbird Conversation version:** 3.1.22
* **Operating System:**
Kernel: 5.4.0-47-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
base: Ubuntu 18.04 bionic

**Comment by Standard8** [comment]
Conversations depends on the messages being downloaded for offline use. If you don't have the full message, then you won't get the full information.

It is possible we might be able to change this in the future, but that's quite a bit of work to do at the moment.

**Comment by GrupoWebex** [comment]
Ok thanks for fast response.
Dude i have is about why it works on classic/base functions but not with this extension? I dont want download full message, only see attachment list.
Thank you.
