### ISSUE TITLE
Message pane is empty if Exquilla is enabled

### ISSUE THREAD

**Issue by ZTHawk** [thunderbird-conversations/thunderbird-conversations#1536]
* **Thunderbird version:** 78.2.2 (32 bit), 78.3.1 (32 bit) and 78.3.1 (64 bit)
* **Thunderbird Conversation version:** 3.1.22
* **Operating System:** Win10

**What did you do?**
Click any email to view its content.

**What did you expect to happen?**
See the content of that email.

**What actually happened?**
Empty pane (like #1495)

Error:
NS_ERROR_FAILURE: Malformed query -- AddrBookManager.jsm:113 (''exquilla@mesquilla.com.xpi!/modules/AddrBookManager.jsm'')
Function: function parseExpression(aQuery)

With Conversations disabled this functions seems not to be called.

Without exquilla Conversations works fine, but Exquilla is more important to me.

**Comment by Standard8** [comment]
Hi, please can you report this to Exquilla - you can find their support email on https://addons.thunderbird.net/en-us/thunderbird/addon/exquilla-exchange-web-services/

Conversations is using standard WebExtension APIs to query the contact database, and it looks like Exquilla isn't supporting those queries. Exquilla will likely be broken alongside any other add-on that uses those APIs as well.

If I've missed something, I'll happily work with them to put it right, but as far as I can tell without access myself, it is an Exquilla problem.

**Comment by Standard8** [comment]
Just an update, I've just (literally just now), sent an email to Exquilla support detailing the issue and letting them know. Hopefully they can fix it soon. I'll update if I hear anything.

**Comment by karagkiozhs** [comment]
> Just an update, I've just (literally just now), sent an email to Exquilla support detailing the issue and letting them know. Hopefully they can fix it soon. I'll update if I hear anything.

I just did too. Let's see.

**Comment by Standard8** [comment]
Update: I've had a response from one of the developers and they've said they'll look into the issue.

**Comment by Standard8** [comment]
Another update: Exquilla don't seem to have released a new version yet, but we did find an issue around the time of the last comment which was in the core of Thunderbird and that Exquilla was triggering it.

We landed a fix for that a couple of weeks ago, I've just requested uplift of it (I was hoping the Exquilla fix was going to come out by now) - I'm not sure if Thunderbird will have that in the next update, it might be the mid-Jan update before we get it.

**Comment by Standard8** [comment]
For reference, the Thunderbird fix being: https://bugzilla.mozilla.org/show_bug.cgi?id=1679464

**Comment by karagkiozhs** [comment]
So, just to be clear (because I got a bit lost): There was an underlying bug that Exquilla uncovered. Now TB is fixed but not yet in an official release, so we wait till January. Meanwhile, did Exquilla fix this problem or not on their end? Or was this totally TB-caused?

**Comment by Standard8** [comment]
78.0.6 of Exquilla is now out, which I think has a fix for this issue.
