### ISSUE TITLE
Reply All Button Present but no Reply or Forward

### ISSUE THREAD

**Issue by madranet** [thunderbird-conversations/thunderbird-conversations#1540]
Thunderbird 78,3,2
MacOSX 10,14,4
Conversations 3,1,24

----

Whenever I have an email selected in conversations view, the only visible response option is Reply All'.  

![SS 2020-10-12 at 20 24 50](https://user-images.githubusercontent.com/669658/95783567-0adb3f80-0cca-11eb-902e-1d90c6c8e2d7.png)

If I want to access simple 'Reply' or 'Forward', I have to get to them through the 3-dots menu.  

![SS 2020-10-12 at 20 25 12](https://user-images.githubusercontent.com/669658/95783543-fbf48d00-0cc9-11eb-8ec8-20e870744904.png)

Is this the normal behaviour?  I seem to remember having at least the 'Reply' button visible too, before Thunderbird's latest update, the other week.

**Comment by Standard8** [comment]
I've just had a look back and this is the normal behaviour for Conversations. You also have extra reply options available at the bottom of the message.

I think Thunderbird does offer multiple options. I wouldn't be keen on that here due to taking up extra space.
