### ISSUE TITLE
Email to Myself Appears Twice in a Thread

### ISSUE THREAD

**Issue by madranet** [thunderbird-conversations/thunderbird-conversations#1541]
Thunderbird 78,3,2
MacOSX 10,14,4
Conversations 3,1,24

----

If I send an email to myself [as I often do, to remind myself to do something later], it appears twice in the messages pane, as a thread containing the same message as a response to itself.

![2020-10-13_12-07-12](https://user-images.githubusercontent.com/669658/95853401-44a15a00-0d4d-11eb-88a3-9492fef24819.png)

**Comment by Standard8** [comment]
The message list pane is controlled by Thunderbird itself, not by Conversations. Please file a bug against Thunderbird at https://bugzilla.mozilla.org/ - you'll want to include which folder view you're using as well.
