### ISSUE TITLE
eMail content disapeard

### ISSUE THREAD

**Issue by m-busch** [thunderbird-conversations/thunderbird-conversations#1542]
* **Thunderbird version: 78.3.3 (32-Bit)
* **Thunderbird Conversation version: 3.1.24
* **Operating System: Windows 10.0.17134.1726

**What did you do?
    I want to read a eMail.

**What did you expect to happen?**
   Display the eMail content.

**What actually happened?**
    Blank Window.
    Only a Text "forward Conversation" is displayed.
    This applies to the PreviewPane as well as the seperate eMail Window.

![Thunderbird_Conversation](https://user-images.githubusercontent.com/63190194/96449304-ed9bf900-1214-11eb-8046-a2a4b9d5b241.png)

**Comment by Standard8** [comment]
Could this be an email where you've started replying to it and have a saved draft?

Could you go to Tools -> Developer Tools -> Error Console and see if any messages get displayed when you reselect the message?

**Comment by m-busch** [comment]
No nothing todo with draft eMails.
None of my eMails are displayed when I enable the "Thunderbird Conversations" AddOn.
The ErrorLog shows new Errors always right in the moment when i click an eMail.
![Thunderbird_Conversation_DevLog](https://user-images.githubusercontent.com/63190194/96466998-c5b79000-122a-11eb-9c78-d4447972f182.png)

**Comment by Standard8** [comment]
Oh, it looks like you have Exquilla installed. Their add-on is not managing the address book correctly, and as a result, is breaking it for other add-ons.

This has already been reported in #1536, but I'll try and contact them direct and get them to fix it.

**Comment by Standard8** [comment]
(Please follow along on #1536 for updates).
