### ISSUE TITLE
S/MIME status not displayed in TB78

### ISSUE THREAD

**Issue by ghalse** [thunderbird-conversations/thunderbird-conversations#1545]
* **Thunderbird version:** 78.4.0
* **Thunderbird Conversation version:** 3.2.3
* **Operating System:** Windows 10 64-bit

**What did you do?**

View an S/MIME signed and/or encrypted email.

**What did you expect to happen?**

I expected some indication that the message was signed and/or encrypted, and that the signature was valid.

This appears along with the PGP equivalent as a rosette and/or lock on the top righthand side of the classic reader.

It also used to appear in conversations prior to TB78, at least if the Enigmail extension was also installed (I can't recall if it appeared without Enigmail). Thus on the surface, it appears at least partly related to #1529.

**What actually happened?**

There's no indication that S/MIME is being used. Worse, there's no indication when a signature fails validation.

**Comment by Standard8** [comment]
I thought there was already an issue on this, but it appears not. If you update to the latest (currently 3.2.6) then encrypted and PGP signed emails should be displayed consistently.

For S/MIME I've had a look at that a few times already, and haven't quite figured it out yet. I will try and have another look sometime soon.

**Comment by OsadaP** [comment]
In Thunderbird Conversations 3.2.22 there is no S/MIME indicator:

![Thunderbird_Conversations - wiadomość z certyfikatem podpisu](https://user-images.githubusercontent.com/86242069/122772490-bac86a00-d2a7-11eb-8ba2-cf06eb6b42d6.png)

Classic view:
![Thunderbird_widok klasyczny - wiadomość z certyfikatem podpisu](https://user-images.githubusercontent.com/86242069/122772503-be5bf100-d2a7-11eb-9785-787384582540.png)

**Comment by WalZyl** [comment]
This was just to mention my observation. At least only view of my correspondents are using SMIME. 
I acknowledge your great work and contributions. Thank you.

**Comment by Standard8** [comment]
This should now be fixed in the 4.0.0 version that I've just put up for review by the add-ons team. You'll need to have Thunderbird 91 to pick up that fix as well - they are starting to roll out automatic updates at the moment.
