### ISSUE TITLE
How did you obtain thread info for a message

### ISSUE THREAD

**Issue by StefanFabian** [thunderbird-conversations/thunderbird-conversations#1548]
Greetings,
I'm trying to write a small add-on that puts messages of one conversation into the same folder even if a filter only applies to one of the messages in the thread.
However, it's unclear to me how I can obtain the messages of a thread without going through every single mail in an account.
Could you point me to how you obtain the messages for a thread in Thunderbird 78+?
The codebase is rather large and I wasn't able to locate that functionality.

Thank you for any help and for this absolutely essential Thunderbird Add-On!

**Comment by Standard8** [comment]
This is done via fetchMessages: https://github.com/thunderbird-conversations/thunderbird-conversations/blob/361226ae06a062fe6a180bb8a8f69d95b46fae3d/addon/content/modules/conversation.js#L278

It probably needs to be converted to a WebExtension API at some stage, but I haven't looked at that yet.
