### ISSUE TITLE
[Feature] Is it possible to change the background color ?

### ISSUE THREAD

**Issue by avatar-lavventura** [thunderbird-conversations/thunderbird-conversations#1550]
Example view:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/18537398/98450676-9c19c680-214f-11eb-879b-54dc9ce841b3.png">

If possible I want to change the background colour from white to darker one like dark blue. If yes, I would like to change also the font color into white. 

=> How could I achieve this?

**Comment by Standard8** [comment]
You can go into Thunderbird's options, select General, then look for Language & Appearance. Under Fonts & Colours select the "Colours..." button, and change the Text & Background colours as you prefer.

If you've already got a message selected, you'll need to deselect messages completely (or switch to a different folder), and then select a message.

**Comment by avatar-lavventura** [comment]
I have actuallly done that but as you can see on the image I shared, it only affects to the mail section and does not affect all the remaining parts.

**Comment by Standard8** [comment]
That would be covered by #1510

**Comment by Standard8** [comment]
There's no work around at the moment, but I would accept patches.

**Comment by avatar-lavventura** [comment]
Thanks anyways,  I will manage to work with white color in the background even it burns my eyes at night time :-)
