### ISSUE TITLE
How can I disable "Quick Reply is not available/disabled/not working in Thunderbird 68" warning message

### ISSUE THREAD

**Issue by avatar-lavventura** [thunderbird-conversations/thunderbird-conversations#1551]
I believe this issue is related to https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1361.

I keep seeing following warning message bottom of the page:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/18537398/98464381-949c0100-21d3-11eb-89eb-2703e42ff241.png">

[Q] Is there any way to disable/hide this message ?

**Comment by Standard8** [comment]
I've updated the wiki page to reflect there's a preference that now needs toggling.

I've also just landed 9fc62ec94c9b9090a75c94aaec7c5d87607c8987 which adds an option to hide quick reply, since a reasonable amount of people seem to want it.
