### ISSUE TITLE
Opened thread is automatically scrolled back to the first unfolded email once receiving a new one

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#1552]
* **Thunderbird version:** 68.12.0
* **Thunderbird Conversation version:** 3.1.24
* **Operating System:** Linux

**What did you do?** Receive an email in an open thread

**What did you expect to happen?** To just have it added to the thread

**What actually happened?** Once receiving a new email in the currently opened thread, scrollbar automatically goes back to the first unfolded email, which is clearly annoying.

**Comment by Standard8** [comment]
Thank you for the report. This was broken sometime in the recent changes, but I've just fixed it. I'm hoping to release a new version later this week - though you'll need to update to Thunderbird 78.x to get it, as backwards compatibility support was too complicated to handle.
