### ISSUE TITLE
"Thunderbird Conversations" prevents the Thunderbird start page from being displayed

### ISSUE THREAD

**Issue by gadfeldan** [thunderbird-conversations/thunderbird-conversations#1565]
"Thunderbird Conversations" prevents the Thunderbird start page from being displayed. When I use "Thunderbird Conversations" I get a blank page instead of the start page. My Thunderbird version : 78.5.1 ,  My Thunderbird Conversation version: 3.2.8 , My Operating System: Windows 10 64 bit.
![2020-12-08 19_28_01-Greenshot png](https://user-images.githubusercontent.com/75246555/101519453-de6f3700-398b-11eb-9c1b-0f2d03cca00c.png)
![2020-12-08 19_28_03-Greenshot](https://user-images.githubusercontent.com/75246555/101519496-e7f89f00-398b-11eb-901d-4deba416cbf2.png)

**Comment by Standard8** [comment]
Thanks for the report, I thought we had an issue on this already, but I can't find one. In any case, I've just found what the simple fix for it is, so I'll push that out in the next release.

**Comment by gadfeldan** [comment]
Thank you very much.

**Comment by gadfeldan** [comment]
Thank you very much for the important update that fixed the issue I described.

**Comment by gadfeldan** [comment]
![Snipaste_2021-01-03_08-06-39](https://user-images.githubusercontent.com/75246555/103479748-69e7b680-4dd8-11eb-9a48-7757eb052834.png)
Thanks again for the update. I wanted to note that starting with update 3.2.10 I am starting to get (when I first run Thunderbird) what I have attached in the image.

**Comment by Standard8** [comment]
I have no idea what that is, that looks like you've customised the mail start page or something, to something that Thunderbird doesn't support.

Conversations doesn't do anything with the mail start page, so if there's an issue, then you need to try disabling Conversations, and if it is still there, please file it with the Thunderbird team.

**Comment by gadfeldan** [comment]
Thank you very much for the quick answer. I checked and apparently the one that caused the problem is another add-on called BrowseInTab that I removed.
