### ISSUE TITLE
Show sent messages in the above pane

### ISSUE THREAD

**Issue by raffaem** [thunderbird-conversations/thunderbird-conversations#1581]
In the 3 pane view, I can see Sent messages in the bottom right pane. But not in the upper right pane (the one with all the messages).

Is it possible to have this feature? Or can I enable it within Thunderbird somehow?

**Comment by Standard8** [comment]
This would be too complex for Conversations to do.

You might be able to simulate it via a saved search folder that searches for your email across multiple folders in the from/to fields. Though I suspect that might miss a few cases, like when you're bcc'ed and not included in the email.
