### ISSUE TITLE
Generate thread by contact instead of subject (or whatever it is)

### ISSUE THREAD

**Issue by Reiszecke** [thunderbird-conversations/thunderbird-conversations#1589]
Thank you so much for developing this add-on. I don't know if I can't find the option or if that feature is missing:

I don't want the conversations to get grouped via the subject line but instead I want to click a contact and get a list of all emails (sent and received) to and from that contact.

If this feature is available already I'm sorry I couldn't find it. 

If this feature is not available, could you point me to the class that manages this so I could fork and make it match the email addresses?

**Comment by Standard8** [comment]
If you hover over a contact in the email preview, then click the second button from the left ("recent conversations"), you can get a list of the recent conversations you've had with that user.

**Comment by Reiszecke** [comment]
Hey Standard8, thank you for your response. But I'd like to have that behavior by default which is why I want to make a fork for that. Also I think that many people would enjoy having this feature

**Comment by Standard8** [comment]
You don't need to fork the add-on for something like that - you probably just want some UI that when you click on a contact in the message header, you can have an option for viewing all conversations by that user.

There is already a feature request in Thunderbird for this, so you could probably even just implement it in Thunderbird direct:

https://bugzilla.mozilla.org/show_bug.cgi?id=1627907

I'll leave a couple of comments there about how this could be done.
