### ISSUE TITLE
DKIM Verifier not working with Conversations in Thunderbird 78+

### ISSUE THREAD

**Issue by farfallosa** [thunderbird-conversations/thunderbird-conversations#1590]
Thunderbird version: 78.6.1 
Thunderbird Conversation version: 3.2.11
Operating System: Windows 8.1, Firefox 84.0.2 

in former versions of TC there was a information within TC mail view, wheter DKIM is used or not.
In classic view of the mail I'll find this information. It would be great to have this info in TC back!

**Comment by Standard8** [comment]
You probably also have the DKIM verifier add-on installed. Due to changes in Thunderbird, the two add-ons are not currently compatible. We have started discussing it here, but still need to do the work to get it running again:

https://github.com/lieser/dkim_verifier/issues/203

**Comment by farfallosa** [comment]
@Standard8 Yes, I have DKIM verifier add-on installed. But even after deactivating that add-on (and restarting TB) the DKIM Label in TC does not appear. I tried it for several times, but it seems that the bug persists even after deactivating DKIM verifier Add-on.
Yes, absolutely, I would appreciate DKIM running on TC again.

**Comment by Standard8** [comment]
We've just landed the Conversations side of this fix on main branch. It'll probably be a few weeks before it is released.

There is also a DKIM side of the fix, the release period is unknown at the moment (see https://github.com/lieser/dkim_verifier/issues/203)
