### ISSUE TITLE
Quoted messages in the body of the email have stopped collapsing

### ISSUE THREAD

**Issue by lahvi13** [thunderbird-conversations/thunderbird-conversations#1591]
* **Thunderbird version: 78.6.1**
* **Thunderbird Conversation version:3.2.11**
* **Operating System:Windows 10**

Previous messages in the body of the email have stopped hiding, I don't see any option for collapse/expand previous mails in the same thread, then the messages become very long and I overlook the attachement, which is only at the end of all messages.

It used to work well for me before, I don't know where the problem came from. don't you have any recommendations?

**Comment by Standard8** [comment]
This is still working for me, do you have an example email body that you could post? We'd need the raw html, so you could select "View Message Source" to view it. You could change the text within the message if you want.

**Comment by lahvi13** [comment]
thanks a lot for the reply
would it be possible to find out something from the attached file? 
[raw_html.txt](https://github.com/thunderbird-conversations/thunderbird-conversations/files/5872040/raw_html.txt)

**Comment by Standard8** [comment]
@siefkenj do you want to look at this? I've not had an in-depth look yet.

**Comment by siefkenj** [comment]
@Standard8 Do you have an easy way to convert the attached raw email into HTML?

**Comment by Standard8** [comment]
Got it:
[raw_html.txt](https://github.com/thunderbird-conversations/thunderbird-conversations/files/5903206/raw_html.txt)

Here's what I did:

* Save the file as a .eml.
* Used Thunderbird's File -> Open to open it.
* Opened up the Developer Tools and selected the Inspector.
* Used the button next to the three-dot button to switch to `chrome://messenger/content/messageWindow.xhml`.
* Navigated down to the `messagepane` browser and expanded it and the document.
* Selected the <html> element.
* Right-clicked and selected "Copy Outer HTML".

**Comment by siefkenj** [comment]
It turns out it is not an issue in `quoting.js` but a race condition when computing whether or not a block quote is tall enough. PR #1594 should fix it :-)

**Comment by lahvi13** [comment]
thanks both for your investigation and (hope) solution:)
Is it possible to try/download your latest merged version as install package? Or when it should be available in [AMO](https://addons.thunderbird.net/thunderbird/addon/gmail-conversation-view/), please?

**Comment by lahvi13** [comment]
thank you, everything works like a charm again! :)
