### ISSUE TITLE
[Feature Request] Message Preview Pane in its own Window so it can be moved to a second screen

### ISSUE THREAD

**Issue by samazer** [thunderbird-conversations/thunderbird-conversations#1595]
More and more people these days have a second monitor as I have. I'm thinking there must be lots of people who, like me, would like to be able to undock the current Message Pane and move it to a second monitor.

Currently, when double-clicking on a message, the message appears in a tab in the main Thunderbird Window. It would be nice if it were possible to move the tabs between windows (ie: between the main Thunderbird window and a second Message Pane window.)

Note that Thunderbird is already able to create New Windows where it's possible to open the Today Pane, the Tasks tab and the Calendar Tab - so there's no real problem with these items. The only real problem is the Message Preview Pane which must be linked to a folder in the main Thunderbird window. It would be nice, though, if they (Today pane, Tasks & Calendars tabs) could be moved from the main Thunderbird Window to their own windows or if the Today pane could appear within a window containing the Message Preview Pane.

Thank you.

**Comment by Standard8** [comment]
Hi,

I'm sorry but this is outside the scope of the Conversations add-on, which is mainly about what is displayed within the preview pane.

You could file a request for Thunderbird to include it, their bug reporting system is at https://bugzilla.mozilla.org/

**Comment by samazer** [comment]
Very sorry - too many windows open - thanks and sorry again.
