### ISSUE TITLE
Message snippet always `...`

### ISSUE THREAD

**Issue by siefkenj** [thunderbird-conversations/thunderbird-conversations#1597]
It appears that on master the `message.snippet` is always `"..."`. Perhaps somethings not working with https://github.com/thunderbird-conversations/thunderbird-conversations/blob/f6065e238938162e42ff4e9d8a0568eb83c9e7d3/addon/content/modules/message.js#L695-L697  ?

**Comment by Standard8** [comment]
I'm not seeing this. Are you sure the messages were downloaded & indexed?

Sometimes there can be a delay for indexing newly received/downloaded messages.

**Comment by siefkenj** [comment]
Very interesting. It is working now. It was weird because I could see the content of the message, it's just that there was no snippet. I remember this persisting for days...

In any case, it works now; could have been a weird indexer thing.
