### ISSUE TITLE
Message zoom doesn't work properly - zooms conversations UI but not the message

### ISSUE THREAD

**Issue by Tueffl** [thunderbird-conversations/thunderbird-conversations#1600]
Just the text of conversations zooms. The message-text keeps its size.
Thanks Tueffl

**Comment by glensc** [comment]
Indeed. This makes the theme totally unusable for accessibility people.

zoom original

![image](https://user-images.githubusercontent.com/199095/118279163-7f31c780-b4d3-11eb-8084-6a9d5c258449.png)


zoom maximum

![image](https://user-images.githubusercontent.com/199095/118279217-8c4eb680-b4d3-11eb-8ee9-e29f89576a23.png)

**Comment by Standard8** [comment]
I did some investigations today and determined that this is actually [an issue in Thunderbird itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1718865) - it just isn't seen there as Thunderbird doesn't use a similar setup to Conversations.

The good news is that I've now got a fix for it, I'm just running it through the automated tests, but hopefully will get it up later today. The bad news is that as it is a Thunderbird fix, it won't be until Thunderbird 91 is released that we'll have the fix. Hopefully TB 91 will come out around August so we shouldn't have too long to wait.

**Comment by thommierother** [comment]
@Standard8 **Many many thanks** for finding a fix for this !!!

**Comment by Standard8** [comment]
Thunderbird 91 is now out & is starting to roll out via automatic updates to some users, I believe it is available to all users using the manual update mechanism (via help -> about). If not, then it should be within the next couple of weeks.
