### ISSUE TITLE
Vcards version 4.0

### ISSUE THREAD

**Issue by romain46** [thunderbird-conversations/thunderbird-conversations#1602]
Hi there !

I came across this issue while working on a project of mine. It's something critical but I thought it was worth reporting it.

* **Thunderbird version:**78.7.1 (64-bit)
* * **Thunderbird conversation:** -
* **Operating System:** Linux 5.10.15-1-MANJARO KDE

**What did you do?** Import a Vcard (Version 4.0)

**What did you expect to happen?** UTF8 non-ASCII characters (éàè,...) to be imported properly

**What actually happened?** There are still encoding problems (é -> Ã©). The issue was the same on Windows (version number unkown)

**Comment by Standard8** [comment]
Sorry, importing a vcard is nothing to do with Thunderbird Conversations - Thunderbird handles the import. You need to file it at https://bugzilla.mozilla.org/
