### ISSUE TITLE
email sender is replaced by "..." in conversations view

### ISSUE THREAD

**Issue by eli-schwartz** [thunderbird-conversations/thunderbird-conversations#1615]
* **Thunderbird version:** 78.8.1
* **Thunderbird Conversation version:**  Version 3.2.12 
* **Operating System:** Arch Linux

**What did you do?**

Opened a mailing list thread for arch-general@lists.archlinux.org

**What did you expect to happen?**

I should see the headers in an email as "(GG) Giancarlo Razzolini via arch-general <arch-general@lists.archlinux.org>"

**What actually happened?**

![image](https://user-images.githubusercontent.com/6551424/111364047-24acf400-8667-11eb-8917-6d469dea18ff.png)

Downgrading to https://addons.thunderbird.net/en-US/thunderbird/addon/gmail-conversation-view/versions/3.2.11 and restarting Thunderbird fixes the problem.

**Comment by Standard8** [comment]
Thank you for the report, it seems that we are collapsing the whole contact if it is too wide for the display, rather than displaying most of it and only showing an ellipsis at the end.

I'll see if I can track down what's happening.

**Comment by eli-schwartz** [comment]
Aha, I was wondering why it generally only happened on this mailing list and not even other mailing lists. It's because this is the only one adding "via list-name" which causes the length to overflow the relatively tight space I have here.

Thanks for the prompt reply. Looking forward to a fix. :)

**Comment by Standard8** [comment]
I've landed the fix, and put up a new version for approval, it may be a day or two before it gets approved.
