### ISSUE TITLE
Add native theme support (& dark mode) to the Search Page

### ISSUE THREAD

**Issue by RM-0454** [thunderbird-conversations/thunderbird-conversations#1616]
Likely related to #1608 #1610 and #1611 

* **Thunderbird version:** 78.8.1
* **Operating System:** Windows 7

**What did you do?**
I am a new user to thunderbird. I installed this week and set up the native dark theme and the darkreader add-on. A few days later, I then searched my inbox for the first time

**What did you expect to happen?**
To find relevant search results

**What actually happened?**
I was blinded by a sudden onslaught of mean-spirited illumination

A well implemented dark theme is practically a requirement for me. Please don't make me go back to outlook....

**Comment by Standard8** [comment]
How did you search your inbox? Did you use the quick filter bar, or the global search on the main toolbar?

Either way, that doesn't sound like something Conversations controls.

**Comment by RM-0454** [comment]
Global search bar. My bad, I didn't realize there was a distinction between the Conversations and Vanilla Thunderbid
