### ISSUE TITLE
"Archive this conversation" and "Delete this conversation" buttons stop working when the add-on updates in background

### ISSUE THREAD

**Issue by Guillaume-Savaton-ESEO** [thunderbird-conversations/thunderbird-conversations#1618]
* **Thunderbird version:** 78.7.1
* **Thunderbird Conversation version:** 3.2.14
* **Operating System:** Ubuntu 20.04, 64-bit

**What did you do?**

Open a message or a conversation by single-clicking in the message list.
Then click on the "Archive this conversation" or "Delete this conversation" in the toolbar above the conversation.

**What did you expect to happen?**

The conversation should be archived or deleted.

**What actually happened?**

The conversation is neither archived, nor deleted.
The error console shows these exceptions:

```
TypeError: self._browserListener is undefined
    get chrome://conversations/content/modules/browserSim.js:119
    deleteConversation chrome://conversations/content/stub.bundle.js:453

Uncaught (in promise) TypeError: self._browserListener is undefined
    get chrome://conversations/content/modules/browserSim.js:119
    archiveConversation chrome://conversations/content/stub.bundle.js:431
```

Two other observations:

* The delete and archive buttons work when the message is opened in a new tab.
* Restarting Thunderbird can make these buttons work again temporarily.

**Comment by Standard8** [comment]
I suspect this is around the time the add-on updates. It updates in the background, unfortunately one of the things I haven't worked out how to do yet is to reopen the message pane when this happens, which will fix the issue.

Rather than restarting, you can switch folders or deselect messages (ctrl-click on the selected message I think) and then reselect them again.

**Comment by Guillaume-Savaton-ESEO** [comment]
> Rather than restarting, you can switch folders or deselect messages (ctrl-click on the selected message I think) and then reselect them again.

Thanks for the tip. Switching folders worked for me.

**Comment by Standard8** [comment]
I believe I've just fixed this - it will be included in the next version that will hopefully get approved in a few days.

One thing to note is that on upgrade, we reload the message view - so the scroll position may change. However, it will keep on working. We can't do much about the scroll position, we need to reload the view, and trying to keep it would be difficult.
