### ISSUE TITLE
When draft is saved, only the draft message is shown in the conversation pane

### ISSUE THREAD

**Issue by Slater91** [thunderbird-conversations/thunderbird-conversations#1622]
* **Thunderbird version:** 78.8.1
* **Thunderbird Conversation version:** 3.2.16
* **Operating System:** KDE Neon (based on Ubuntu 20.04)

**What did you do?**
I received a message and clicked on "reply", then started typing my message. A draft was saved.

**What did you expect to happen?**
I expected the conversation pane not to change the message I was looking at when a draft is saved.

**What actually happened?**
The conversation pane stopped showing the message I was replying to, instead showing my draft preceded by another draft. The message I was replying to was not accessible until I selected another conversation and then the desired conversation again. See screenshot below:
![Screenshot_20210406_232732_2](https://user-images.githubusercontent.com/11941225/113786739-ad342700-9731-11eb-9a08-d8ff4ec46526.png)
This happens every single time a draft is saved.

**Comment by Standard8** [comment]
Thank you for the report, I'd been seeing this as well but hadn't had time to look at it. Turns out it was a simple typo.

I've now fixed it and will hopefully have time to push out a new release in the next day or so (but it may take a few of days to be reviewed).

**Comment by Slater91** [comment]
Thank you for the quick fix! I look forward to trying out the new version. Have a great weekend!
