### ISSUE TITLE
No way of knowing that a new message added to a thread

### ISSUE THREAD

**Issue by aonafedspoi** [thunderbird-conversations/thunderbird-conversations#1623]
* **Thunderbird version: 78.9.0
* **Thunderbird Conversation version: 3.2.16
* **Operating System: Windows 10

**What did you do?  Received a new message within a thread with the thread closed

**What did you expect to happen?  The thread listing in the inbox would go bold

**What actually happened?  Didn't go bold

**Comment by Standard8** [comment]
This is working for me - note that when a new message comes into a closed thread, Thunderbird adds an underline to that thread in the message list, rather than making the text bold, for example, this is what I see:

<img width="226" alt="Screenshot 2021-04-11 at 08 29 36" src="https://user-images.githubusercontent.com/520844/114295892-199b8700-9aa0-11eb-8d1d-720eb34740ad.png">

Are you not seeing the underline?

**Comment by Standard8** [comment]
I should also say, that the message should be added to the message preview pane, and when you scroll down to the end of the message, it'll mark it as read.

**Comment by aonafedspoi** [comment]
It's possible that I didn't notice the underline.  I'll have to watch for
it when another message comes in to an existing thread.

Thanks.

**Comment by Standard8** [comment]
Thanks, I'll close this one out for now.

**Comment by timonsku** [comment]
Is there a reason why thread receive only a subtle underline? I constantly miss e-mails because of this behaviour.
Having the main thread show as bold would greatly help, even if its just an option.

**Comment by Standard8** [comment]
> Is there a reason why thread receive only a subtle underline? I constantly miss e-mails because of this behaviour. Having the main thread show as bold would greatly help, even if its just an option.

This is standard behaviour for Thunderbird which is not controlled/altered by Conversations. If you want to suggest something, you'll need to file an enhancement request at https://bugzilla.mozilla.org/ for Thunderbird.

**Comment by timonsku** [comment]
Ah I was not aware, I only started seeing it with this addon. Will do thanks!
