### ISSUE TITLE
Follow-ups to contact rework

### ISSUE THREAD

**Issue by Standard8** [thunderbird-conversations/thunderbird-conversations#1624]
These are follow-ups that we'd said we would do after moving contacts retrieval to the background process (#1614).

- [x] Move the functions out of utils.js into separate places for background/stub code. I think they can go alongside the code where they are used, and can be exported. Should still be testable this way.
- [x] Change ContactManager to return just the contact, and have the front-end formulate the name.
- [x] Add tests for ContactManager and if we can for the front-end code, so that we can ensure we're ending with the right display.
- [x] Add listening to address book updates & updating cache.
- [x] Limit size of cache.

The above are what we need to do to make it `main` shippable again. The below is performance improvement.

- [ ] Contact requests happening in async fashion alongside the rest of message loading.

**Comment by siefkenj** [comment]
What is the cache limiting strategy? To have a finite size and kick out the old emails whenever they exceed the size? To have a finite size and an "max overflow" and batch cache shrinking only when "max overflow" is reached? Is there a limit to the number of emails that can be included in one message? Do we risk someone getting an email with 10000 recipients and the software getting stuck in a loop of loading emails and kicking the old ones out?

**Comment by Standard8** [comment]
> What is the cache limiting strategy? To have a finite size and kick out the old emails whenever they exceed the size? To have a finite size and an "max overflow" and batch cache shrinking only when "max overflow" is reached?

I think my biggest concern is that this is now a session based cache. If you leave TB open for a few weeks at a time, you'll potentially keep memory occupied unnecessarily. I'm not sure how much that would be, it might be worth some measurements. If 10000 emails is < 1MB, maybe that's ok.

> Is there a limit to the number of emails that can be included in one message? Do we risk someone getting an email with 10000 recipients and the software getting stuck in a loop of loading emails and kicking the old ones out?

The other option would be to limit based on time as well, e.g. if there's more than 10000 in the cache, expire anything older than one hour.

**Comment by Standard8** [comment]
@siefkenj are you working on any of these at the moment? (or have patches in progress)

**Comment by siefkenj** [comment]
I've started a little bit, but haven't had much time in the last few months...

**Comment by Standard8** [comment]
Ok, I was pondering about picking some up, so that I can get main back into a good shape for shipping again.

Maybe I can look at the address book listeners / limiting size of the cache?

Let me know though if you want to do more sometime.

**Comment by siefkenj** [comment]
Please, tackle any that you want. I was working on extracting the contacts out of the `message` object an into their own redux store that would then be injected into the `message` object with a selector, but I haven't gotten very far.

**Comment by Standard8** [comment]
I've now landed all the changes that I thought we'd need to be able to release this. I've been trying it for the last day or so and it seems to work fine afaict.

Regarding the possible perf improvement for "Contact requests happening in async fashion alongside the rest of message loading.": I think we should delay this for now.

At the moment it doesn't make much sense as fetching the contact details is happening just before the message display. Making that happen in parallel, and then doing a second update of the display is possibly worse.

I think when we move the conversation/message fetching into the stub code, that's when we should look at doing these in parallel. Then we can be analysing and fetching extra message details whilst hopefully also fetching the contacts.

Hence closing this as "fixed".
