### ISSUE TITLE
Encryption detail in message view is missing (can't import public keys)

### ISSUE THREAD

**Issue by almereyda** [thunderbird-conversations/thunderbird-conversations#1633]
* **Thunderbird version:** 78.7.1
* **Thunderbird Conversation version:** 3.2.17
* **Operating System:** Fedora 33

**What did you do?**

Open a message with Autocrypt header.

**What did you expect to happen?**

See the OpenPGP button to import the attached public key.

**What actually happened?**

The OpenPGP button does not appear.

**Comment by Standard8** [comment]
This had been working in the Thunderbird 78.x stable series as I remember testing it. Unfortunately in [Thunderbird 78.4](https://bugzilla.mozilla.org/show_bug.cgi?id=1647039) they changed Thunderbird's UI, without any announcement or warning, which broke conversations.

I'm not sure if there's an easy fix here, we could potentially re-implement the Thunderbird UI, but we need to be able to get the appropriate information from Thunderbird as well. That code is also due for a rewrite, so maybe now is the time to do it.

I'll have to think about this for a bit and see what the options are.

**Comment by Standard8** [comment]
I'm not entirely sure, but I think I fixed this a while back and forgot to update the issue :( There may be a banner displayed for this case, alternately there may be a pill that states about the encryption status that you can click on.
