### ISSUE TITLE
Contact popup "send mail" doesn't work in local folders

### ISSUE THREAD

**Issue by despecial** [thunderbird-conversations/thunderbird-conversations#1651]
* **Thunderbird version:** 78.10.2 (64-Bit)
* **Thunderbird Conversation version:** 3.2.17
* **Operating System:** MacOS Mojave 10.14.6

**What did you do?**
Hover over a recipients name

**What did you expect to happen?**
Popup (working) with button to send mail to (not working)

**What actually happened?**
nothing

**Comment by Standard8** [comment]
This seems to be working for me, please can you go to Tools -> Developer Tools -> Error Console and then try again, and see if any messages appear when you click the button?

**Comment by despecial** [comment]
sure @Standard8 
<img width="892" alt="thunderbird-error-console" src="https://user-images.githubusercontent.com/4135109/120107028-9cb39200-c15f-11eb-9e4a-6dc95f78f624.png">

**Comment by Standard8** [comment]
Thank you for checking that. It would appear that your account doesn't have an identity associated with it, which would seem to be an issue with Thunderbird itself.

What happens if you go into Tools -> Account Settings, select the account on the left. Is that page filled in with appropriate settings?

Also if you click "Manage Identities" on that page? Is there an identity listed?

**Comment by despecial** [comment]
yes, it's filled with all my mail accounts, plus a default account is set.
and if I check "Manage Identities" it shows exactly one.

So everything is set as you asked.

**Comment by despecial** [comment]
Any news on this?

**Comment by despecial** [comment]
Results for the `mail.acc` search: id1 | id2 | id7 | id10 | id9 | id8 | id3 | id5 | id14 | id6
Results for the `mail.identity.id` search: id1 | id10 | id14 | id2 | id3 | id5 | id6 | id7 | id8 | id9

Seems both are identical. How do I see if the accounts are linked correctly?

**Comment by Standard8** [comment]
Good news, in trying to figure out what to ask you for debug, I've just realised this button doesn't work when the message is in the local folders.

When using the send message in that way, Conversations is trying to default to an appropriate identity according to which account the folder is in. However, Local Folders don't have any identities associated with them, and hence it fails - so in that case we need to fallback to the default account / identity combination.

I'll try and get that fix done this weekend, though I'm not sure when we'll release it yet.

**Comment by despecial** [comment]
Great news you could locate the bug. 99% of the time I am working from the global inbox folder
