### ISSUE TITLE
Unusable with Thunderbird 90 beta 1

### ISSUE THREAD

**Issue by jfx2006** [thunderbird-conversations/thunderbird-conversations#1652]
* **Thunderbird version:** 90.0b1
* **Thunderbird Conversation version:** 3.2.17
* **Operating System:** Linux x64 (Manjaro)

**What did you do?**
Selected a message to read (3-pane window)

**What did you expect to happen?**
The message should display in a conversation style

**What actually happened?**
Error displayed:
```
Error encountered while rendering.
[Exception... "Cannot modify properties of a WrappedNative"  nsresult: "0x80570034 (NS_ERROR_XPC_CANT_MODIFY_PROP_ON_WN)"  location: "JS frame :: chrome://conversations/content/common.bundle.js :: componentDidMount :: line 4423"  data: no]

MessageIFrame@chrome://conversations/content/common.bundle.js:4330:5
ErrorBoundary@chrome://conversations/content/common.bundle.js:5194:5
div
li
Message@chrome://conversations/content/common.bundle.js:5229:5
ul
_MessageList@chrome://conversations/content/common.bundle.js:5591:13
ConnectFunction@chrome://conversations/content/common.bundle.js:7477:39
_ConversationWrapper@chrome://conversations/content/common.bundle.js:5660:5
ConnectFunction@chrome://conversations/content/common.bundle.js:7477:39
Provider@chrome://conversations/content/common.bundle.js:7219:15
```

Checked for an update to Conversations, none found. Happens consistently with all messages.

**Comment by lluismontero** [comment]
Same here:

- Thunderbird version: 90.0b1
- Thunderbird Conversation version: 3.2.17
- Operating System: Windows 10 (Windows 10 Pro 21H1 build 19043.1023)

**Comment by Standard8** [comment]
Hi thanks for the comments. As mentioned in the [FAQ](https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/FAQ) we don't guarantee that Conversations will always work with the beta, however we do try if we see things coming.

I'd already partially fixed a couple of issues, but hadn't got round to shipping them yet, so I've just created a new version, but the add-ons site is having issues, so I can't upload it at the moment. I've filed an issue, so hopefully it'll get fixed soon, then it'll be a couple of days before it gets reviewed.

There are still some issues with opening attachments, hopefully I can get those resolved soon as well.

**Comment by mitra42** [comment]
Same problem , and its not related to attachments, even the Github verification message I just received which is text/plain got this error.

**Comment by Standard8** [comment]
> Same problem , and its not related to attachments, even the Github verification message I just received which is text/plain got this error.

The attachment issue is a separate issue, I mentioned this so that people would be aware that it is present. I did not say it was related.

The updated version has been awaiting review - I can't do any more than that, so please be patient.

**Comment by Standard8** [comment]
The updated version has just been approved.

I'll try and take a look at the attachment opening soon, we'll need to get updated & working with the latest for the next major release of Thunderbird anyway.
