### ISSUE TITLE
The "Between" (Co column header keeps appearing every time I start Thunderbird.

### ISSUE THREAD

**Issue by funplayertv** [thunderbird-conversations/thunderbird-conversations#1660]
Thunderbird version: 90.0b1
    Thunderbird Conversation version: 3.2.19
    Operating System: Windows 10 64bit

**What actually happened?**

The "Between" column header keeps appearing every time I start Thunderbird. I unclick it from the menu, but it reappears next time I open Thunderbird. 

After switch off the addon everything is ok.

**Comment by Standard8** [comment]
You could try what I suggested here: https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1426#issuecomment-735392490_
