### ISSUE TITLE
Quoted message parts are not collapsed when a conversation is loaded in a tab

### ISSUE THREAD

**Issue by blackshot** [thunderbird-conversations/thunderbird-conversations#1663]
* **Thunderbird version:** 78.11.0 (32-bit)
* **Thunderbird Conversation version:** 3.2.19
* **Operating System:** Windows 10 Home 64 bits using gmail smtp

**What did you expect to happen?**
as the documentation says, quoted parts should be collapsed or collapsable,
![imagen](https://user-images.githubusercontent.com/3688208/121960119-acbc9b80-cd33-11eb-945b-73c2d3e50ba2.png)

**What actually happened?**
there is no such behavior, all messages stacks and i cannot collapse them 
![imagen](https://user-images.githubusercontent.com/3688208/121961025-dfb35f00-cd34-11eb-8413-5935ae4845cb.png)

**Comment by Standard8** [comment]
From what I can tell, those parts are not "quoted", they're simply included in the email as a complete item that isn't seen as quoted.

Generally, if something is quoted properly, we expect to see something like:

```
-----Original Message-----<br />
```

Or there could be `<blockquote>` in the html source.

Are these messages received via/from a particular system, or are they just from regular people?

I think to look at this properly, I would need to see the source of the message body. You could change the content of the messages - the words, emails, headers etc, but the html and other items would need to stay intact.

**Comment by blackshot** [comment]
here is an example [https://pastebin.com/Rs7vdXgF](https://pastebin.com/Rs7vdXgF), i picked a shorter one, but it's the same, blockquotes are not collapsable

**Comment by Standard8** [comment]
Hmm, `moz-cite-prefix` looks like something internal to Thunderbird that shouldn't be there in normal messages. Are you sure that's from the original source of the message?

Unfortunately I can't see the the pastebin yet, as it is private or awaiting moderation.

**Comment by Standard8** [comment]
@blackshot was that from the original message source? I've taken a look and if I insert that html into a message then it collapses fine. Hence, I'm not quite sure what's happening here.

**Comment by blackshot** [comment]
i'm afraid not, that was taken from "reply to all" converted to html

![imagen](https://user-images.githubusercontent.com/3688208/123545425-e8893500-d725-11eb-8204-0b9ab14c108b.png)

because if i click on "view source of the message" it only shows a bunch of css and js imported

![imagen](https://user-images.githubusercontent.com/3688208/123545268-2fc2f600-d725-11eb-870e-8d4c2148fc61.png)
```html
<!doctype html><html xmlns="http://www.w3.org/1999/xhtml" xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"><head><link rel="stylesheet" href="chrome://messenger/skin/tagColors.css"/><link rel="stylesheet" href="conversation.css"/><link rel="stylesheet" href="quickreply.css"/><link rel="stylesheet" href="tokeninput.css"/><link rel="stylesheet" media="print" href="print.css"/><script src="stubGlobals.js"></script><script defer="defer" src="415.bundle.js"></script><script defer="defer" src="800.bundle.js"></script><script defer="defer" src="50.bundle.js"></script><script defer="defer" src="978.bundle.js"></script><script defer="defer" src="859.bundle.js"></script><script defer="defer" src="stub.bundle.js"></script></head><body><div id="conversationWrapper"></div></body></html>
```
though my replies are correctly formatted they are still uncollapsable.

all replies are collapsable in gmail and outlook but Thunderbird conversations

**Comment by blackshot** [comment]
maybe i could forward you a message, in order to test it, that doesn't contain sensitive information than emails from my organization, and names.

**Comment by blackshot** [comment]
Alright! i found the problem!! it was this addon [Markdown Here](https://addons.thunderbird.net/en-US/thunderbird/addon/markdown-here-xul/) that lets you write in markdown lang then render it with a button. i disabled it and hiding bloquotes started working. (because markdown uses blockquotes for ">" symbol)

**Comment by blackshot** [comment]
alright we are moving forward i realized hide blockquotes works on side email preview
![imagen](https://user-images.githubusercontent.com/3688208/123549329-9270bd80-d736-11eb-965c-2d68e3445062.png)
but not in the full email tab

**Comment by Standard8** [comment]
I just took another look at this. When opening the conversation in a tab, we're not being notified that the message has finished loading. I think it is something to do with the way that loading the conversation in a tab is set up, but I don't quite see the solution at the moment. I'll ask around a bit and see if I can find something.

**Comment by Standard8** [comment]
I'm still not quite sure why this isn't working right in 78, but the good news is that it does work in Thunderbird 91 that has just been released. Users of 78 won't be updated to 91 for a month or two though.

**Comment by Standard8** [comment]
Thunderbird 91 is now out & is starting to roll out via automatic updates to some users, I believe it is available to all users using the manual update mechanism (via help -> about). If not, then it should be within the next couple of weeks.
