### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by raffaem** [thunderbird-conversations/thunderbird-conversations#1666]
* **Thunderbird version:** 78.11
* **Thunderbird Conversation version:** 3.2.21
* **Operating System:** Fedora Workstation 34

**What did you do?**

I installed Thunderbird Conversations

**What did you expect to happen?**

An installation without error

**What actually happened?**

After the installation, another tab opened with an error:
```
File not found

The file jar:file:///home/raffaele/.thunderbird/leep2rae.default-default/extensions/gconversation@xulforum.org.xpi!/background/assistant/assistant.html cannot be found. Please check the location and try again.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.
```

**Comment by Standard8** [comment]
Thank you for the report, we recently changed something which broke this. I've just pushed a fix, we'll get it released soon.

As a work around, you can go back into the add-on manager, and click the spanner symbol next to Conversations, and then at the bottom of that settings page there is a "Start setup assistant" button that will allow you to set things up.
