### ISSUE TITLE
Removing a tag marks message as unread

### ISSUE THREAD

**Issue by Buratinator** [thunderbird-conversations/thunderbird-conversations#1668]
* **Thunderbird version:** 78.11.0 (32-bit)
* **Thunderbird Conversation version:** 3.2.22
* **Operating System:** Windows 10 Home (Version 2004)

**What did you do?** 
Removed a tag from a message by clicking the `x` in the tag pill inside the conversations message pane (underneath the correspondents details at the top of the message).

**What did you expect to happen?** 
The tag would be removed and nothing else

**What actually happened?**
The tag is removed _and_ the message is **marked as unread**

If I remove the tag by using the tag control in the Thunderbird toolbar, the message isn't marked as unread (i.e. works as expected).

This started in the last couple of weeks.

**Comment by Standard8** [comment]
I've tried this a couple of times, and I can't reproduce it. Do you have any other add-ons installed that could be affecting it?

What settings do you have for marking messages as read?

**Comment by Buratinator** [comment]
I have 4 addons enabled:
* importExportTools NG
* Provider for Google Calendar
* Thunderbird Conversations
* Tag Popup - disabling it doesn't help.
* (I have a bunch more disabled, one of them being Tag Sequence Arranger (a legacy addon so can't be enabled)

Regarding Mark Read settings, I have "Automatically Mark Messages as Read" enabled with the option "Immediately on display"

mail.spam.markAsNotJunkMarksUnRead is true (setting to false makes no difference)
mail.spam.markAsReadOnSpam is false
mailnews.ui.junk.manualMarkAsJunkMarksRead is true

**Comment by Standard8** [comment]
Is this still an issue, I think I fixed something recently that was related, and I suspect it could have fixed this as well.

**Comment by Buratinator** [comment]
Indeed, this is fixed 👍 Will close the issue
