### ISSUE TITLE
Different sender name shown in mail than in From header and address book

### ISSUE THREAD

**Issue by vinsiu** [thunderbird-conversations/thunderbird-conversations#1669]
* **Thunderbird version:** 78.8.1 (64bits)
* **Thunderbird Conversation version:** 3.2.22
* **Operating System:** Linux Mint 20.1 Ulyssa

When reading an email from a user which address is sk@... I see the name of the user which has a different email address darsk@...

I expect that the real username is shown, taken from the From header of the email. The name should belong to user sk@... and not darsk@...

Could it be that Thunderbird Conversations is searching for the name of the sender improperly and by some regex it finds the name for darsk@... instead of sk@... ?

Additionaly, when I click the username in the dialog box provided by Thunderbird Conversations and choose to edit the user in the address book, it shows the correct user, not the one with darsk@... email.

**Comment by pmbrandao** [comment]
Same issue here, adding some info that might help:

- addresses chosen seem to _match_ longer prefix (`darsk@` is "preferred"  to `sk@`)
   - I have similar examples in my local addressbook 
- I have one case where the matched address is on the `Personal Address Book` and the correct email is on the `Collected Addresses` and another where both (matched and correct) are on the `Personal Address Book`
- I have one case where `Always prefer name over message header` was checked on both  (matched and correct) and another where it was **not** checked on both

Cases above mean that the issue occurred.

Issues that mention similar problem but I don't think apply are: #646 #642 #370 #7

**Comment by Standard8** [comment]
Thanks for the report, we changed how the address book search worked a while ago, and I hadn't thought of that case. I'll try and get to this soon, should be a simple enough fix.

**Comment by vinsiu** [comment]
That is great news Mark. Thank you very much for your quick response.

Best regards
