### ISSUE TITLE
No way to Detach an attachment - it no longer appears in the UX. 

### ISSUE THREAD

**Issue by mitra42** [thunderbird-conversations/thunderbird-conversations#1670]
* **Thunderbird version:** 90.0-b2
* **Thunderbird Conversation version:** 3.2.22
* **Operating System:** OSX 11.4

**What did you do?**
Open a thread with Attachments, tried toDetach

I expected some control - for example a right-click menu is mentioned in #1414 , but the only option now is an icon to "save", Right clicking on either the Save icon, or the PDF icon gives options to Reload or Select All but no way to "Detach".

**Comment by Standard8** [comment]
I've been taking a bit of a look at this, the functionality we were using for the context menu has been removed from the core code.

I'm therefore thinking of potentially adding some icons that are always present for delete/detach. The other option would be to just add delete all and detech all into the three-dot menu for the message.

**Comment by mitra42** [comment]
Either would work for my workflow, but with the Detach facility missing it means constantly switching into the old reader. 

(between this, and the bug with HTML messages not scrolling all the way down) it means a continuous switch back and forth between conversations and classic reader

**Comment by Standard8** [comment]
I've just implemented an in-message drop-down that replaces the existing context menu. The context menu support has gone away in 91, and this is more discoverable, so I think it makes sense.

**Comment by mitra42** [comment]
Thanks
