### ISSUE TITLE
[OBSOLETE] Keyboard shortcuts not working after restart of TB (overwritten by TB defaults)

### ISSUE THREAD

**Issue by Steff-n** [thunderbird-conversations/thunderbird-conversations#1672]
* **Thunderbird version:** 
*78.11.0  
* **Thunderbird Conversation version:**
* 3.2.23
* **Operating System:**
* Win 10, 64-bit

**What did you do?**

UPDATE: Accidentally posted in the wrong forum - please ignore.

**Comment by Standard8** [comment]
> Shortcuts (S, G) seem to get temporarily overwritten by TB defaults - e.g., when hitting S, messages get starred instead of opening the Conversations input box.

Please can you clarify what you mean by the conversations input box? Also, what is G meant to do?

> After opening TB Conversations' add-on settings (even if not changing anything there) and going backj to the message list pane, Conversations shorcuts are working again.

I'm slightly puzzled - as far as I can tell Conversations has never overridden neither S nor G, and there's no code for it, so I really don't know what's happening here, and it may be the functionality you're seeing is the actual bug.

**Comment by Steff-n** [comment]
Oh gosh, so sorry Mark, I actually posted this in the wrong add-on forum - must have been a long day yesterday ... My add-ons are so many and tightly interacting with each other that I seem to forget at times which one is doing what ;-) 

You can forget about this and close the ticket - sorry once again for any inconvience caused!

**Comment by Standard8** [comment]
Aha, no wonder I was confused! No problem, thank you for the follow-up.
