### ISSUE TITLE
TB crashes when browsing through filtered messages

### ISSUE THREAD

**Issue by despecial** [thunderbird-conversations/thunderbird-conversations#1675]
* **Thunderbird version: 78.11.0 (64-bit)**
* **Thunderbird Conversation version: 3.2.23**
* **Operating System: MacOS Mojave 10.14.6**

**What did you do?**
Go to "Trash" grouped folder. Used the "Filter these messages" option. Scrolled downwards through the mails.

**What did you expect to happen?**
Showing the mail immediately and with proper attachments support.

**What actually happened?**
Sometimes the images were shown as broken (not happening when this ext is disabled).
Thunderbird freezes or crashes completely.

When I disable the extension, everything works as expected.

**Comment by Standard8** [comment]
Is this still happening on the latest Thunderbird / Conversations versions?
