### ISSUE TITLE
Long time taken to load long threads

### ISSUE THREAD

**Issue by mmorandi** [thunderbird-conversations/thunderbird-conversations#1677]
* **Thunderbird version:**  	89.0.2
* **Thunderbird Conversation version:** 3.2.24
* **Operating System:** Linux openSUSE Tumbleweed

**What did you do?**
Use thunderbird-conversation and deal with long threads

**What did you expect to happen?**
When I click on a message of the thread, I'd like to see the text immediately, without any significant slowdown of the
mail client

**What actually happened?**
When I click on any message of the thread, one core start being used at 100% and the message is not displayed for
more than 15 seconds. The mail client becomes unresponsive.

I think there's a quadratic (or worse) algorithm somewhere.

**Comment by Standard8** [comment]
Do you have an LDAP address book set up?

**Comment by mmorandi** [comment]
Only the "Local Address Books" (no external Directory server). Unchecking it in the preference does not seem to improve things.

**Comment by Standard8** [comment]
Roughly how many messages are in the threads that you are loading? (this would be messages from other folders as well).

Conversations does load a lot of message information up-front, so that is most likely the cause. Has this got slower recently?

Please could you also try getting a performance profile - instructions are here: https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/Profiling-Conversation's-Performance

**Comment by mmorandi** [comment]
About 100 messages.
It always used to be slow, since forever, for long threads. Recently it was better, but I don't know whether this was because of a fix or because I was not dealing with long threads. Now I d again have a long thread to deal with, and it's slow again. My impression is that it became significantly slower since one week (say), but I'm not sure about this, and for sure the thread is becoming longer as well.
The profile should be available from https://share.firefox.dev/2TyyEae

**Comment by mmorandi** [comment]
If, on the other hand, by "how many messages are in the threads that you are loading" you mean how many messages I do have in total then this is more like 120000 . And, if this can help, I'm using a maildir store, not a mbox one. But the slowdown is only for long threads, it's pretty snappy for short ones.

**Comment by Standard8** [comment]
@mmorandi thanks for the thread, there's a whole load of repeated ~150ms yank in there, which I think is the message lookups happening.

Would you mind installing version 3.2.23 and comparing the speed of the same thread? I did a few changes in the latest version that I don't think would have significantly affected things, but I'd like to verify that.

You can do something like this:

1. Select the folder with the large thread.
2. Restart Thunderbird.
3. Wait a minute or two for everything to settle.
4. Select the thread and see how long it takes.
5. Select a different thread, wait for it to load, and then select the long thread again and see how long it takes.
5. Then go into add-ons manager, and select the Cog symbol, uncheck "Update add-ons automatically"
6. Search for Thunderbird Conversations (next to find more add-ons), and select the add-on page.
7. Scroll down to the bottom and look for the Version Information section
8. Expand it and select "See complete version history"
9. Select add to Thunderbird and accept the install
10. Close the add-ons page and add-ons manager.
11. Repeat steps 1 to 5.

Don't forget to turn "Update add-ons automatically" back on at some stage.

**Comment by mmorandi** [comment]
I've checked: it's a regression introduced with 2.3.22; 2.3.21 is relatively snappy.

I see no difference of timing wrt 3.2.23 (by looking at my wrist watch , thus consider a +- 1 s tolerance):

> 4. Select the thread and see how long it takes.
~ 20 s
> 5. Select a different thread, wait for it to load, and then select the long thread again and see how long it takes.
~ 19 s

While with 2.3.23 I saw
> 4. Select the thread and see how long it takes.
~ 19 s
> 5. Select a different thread, wait for it to load, and then select the long thread again and see how long it takes.
~ 20 s

Same story with 2.3.22, while 2.3.21 seems to be ok: it takes 1:2 s , that are more than bearable.

**Comment by Standard8** [comment]
> Same story with 2.3.22, while 2.3.21 seems to be ok: it takes 1:2 s , that are more than bearable.

Is that it takes 12 seconds? or 1 to 2 seconds?

**Comment by mmorandi** [comment]
1 to 2 seconds

**Comment by Standard8** [comment]
Ok, that's a bit longer than expected. Do you have lots of accounts and identities or maybe folders?

I think I see why this has maybe got slower - we get account details on each message displayed currently, and 3.2.22 changed things which means we get full account details including folders for each message displayed. With the subsequent work that I've done, I think I can at least cut that down to once per thread switch.

I'll see if I can get some time tonight to investigate that.

**Comment by mmorandi** [comment]
> Do you have lots of accounts and identities or maybe folders?

Only one identity, but 1095 "folders":

marco@spark:~/Maildir> find . -name "*.msf" | wc
   1095    2465   56459
marco@spark:~/Maildir> find . -name "*.sbd" | wc
    207     478    9958

**Comment by Standard8** [comment]
Thank you for the testing and extra information, that's been very helpful. As mentioned above, I spotted an issue where an expensive function call was happening once per message per load. I've been able to cut that out completely as we already had the information elsewhere, so this should go back to 3.2.21 speeds or maybe even ever so slightly better.

**Comment by Standard8** [comment]
Oh, just to clarify, I've landed the fix and pushed a new version of the add-on for review. It normally takes a day or two for it to be reviewed.

**Comment by Standard8** [comment]
@mmorandi 3.2.25 is out now. Places can you check that the speed is better now?

**Comment by mmorandi** [comment]
The speed is back to about 1 or 2 s the first time a message of the long thread is selected. If immediately after that another message of the same thread is selected then it is faster. Changing thread and then going back to the long one needs again the 1 or 2 s delay.
In a nutshell, now it's ok. Thank you!

**Comment by Standard8** [comment]
Great, thank you for confirming.
