### ISSUE TITLE
Starred/Important emails are unstarred/unimporant after double clicking on an email.

### ISSUE THREAD

**Issue by tumpanaios** [thunderbird-conversations/thunderbird-conversations#1681]
* **Thunderbird version:**
*78.11.0
* **Thunderbird Conversation version:**
* 3.2.25 is the buggy version. When we tried on 3.2.17 it worked as expected so we rolled back for now.
* **Operating System:**
* We tried on Archlinux,Windows 10,Debian Bullseye
**What did you do?**
*Double clicked a starred email
**What did you expect to happen?**
*I expected the star to remain and the email to be accessed on a different tab
**What actually happened?**
*The mail was opened on a different tab but the star was removed from the email.

**Comment by Standard8** [comment]
Thank you for the report. I've done a small fix for this, and I've just posted a new version on the add-ons site for review. Hopefully should be approved in the next day or two.
