### ISSUE TITLE
Any type of Attachment can't be visualized using this extension. The addons "Show all body parts" are not available abymore.

### ISSUE THREAD

**Issue by ideamediaweb** [thunderbird-conversations/thunderbird-conversations#1696]
* **Thunderbird version:**
* **Thunderbird Conversation version:**
* **Operating System:**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by Standard8** [comment]
Please file a proper issue with all the requested information, and a proper description of what isn't working, preferably with screenshots. I am not prepared to guess what is actually wrong from a one-line subject.
