### ISSUE TITLE
Message window cannot be maximized

### ISSUE THREAD

**Issue by mwensveen-ebpi** [thunderbird-conversations/thunderbird-conversations#1711]
Thunderbird 78.13.0 (64-bit)
Thunderbird Conversations 3.2.34
Ubuntu 20.04.3 LTS
Gnome 3.36.8

Open a conversation in a new window (either double clicking or using "show this conversation in a new tab" button).
Double click on the top of the window.This should maximize the window, but nothing happens.
Right click on the top window show that maximize and minimize are not available (greyed out).

When disabling this add-on the window can be maximized.

**Comment by Standard8** [comment]
As far as I can tell, this works on Mac, I don't see a reason it wouldn't on Linux. Feel free to reopen if it is still an issue in the latest version.
