### ISSUE TITLE
Attachments to messages are not visible/accessible after enabling Conversations

### ISSUE THREAD

**Issue by rapostolo** [thunderbird-conversations/thunderbird-conversations#1716]
* **Thunderbird version:**
91.2.0

* **Thunderbird Conversation version:**
4.0.0

* **Operating System:**
MacOS

**What did you do?**
Received a mail with an attachement

**What did you expect to happen?**
Be able to see, open or download the attachment

**What actually happened?**
After enabling Conversations, the attachment disappears from the body and is not accessible. 

Here are screenshots:
Conversations disabled
<img width="732" alt="Conversations disabled" src="https://user-images.githubusercontent.com/1399495/136379161-76f4305c-3497-4c0d-ab24-c0217c5fd1cf.png">

Conversations enabled
<img width="732" alt="Conversations enabled" src="https://user-images.githubusercontent.com/1399495/136379164-79262ccf-3292-4e82-975f-1c810390a98e.png">

**Comment by Standard8** [comment]
Please can you try opening the error console via Tools -> Developer Tools -> Error Console and see if you get any error messages appearing whilst selecting the message?

**Comment by Standard8** [comment]
Now I've had the thought about Gloda, I can reproduce this.

Thunderbird doesn't index all folders by default, but also when receiving a message it might not have indexed it before Conversations displays it. That causes Conversations to use a different code path - which is broken for displaying those attachments.

I'll try and get a fix out in the next day or so.
