### ISSUE TITLE
When replying using the compose window, the input focus is not in body field but on the to field

### ISSUE THREAD

**Issue by apuder** [thunderbird-conversations/thunderbird-conversations#1725]
* **Thunderbird version:** TB 91.2
* **Thunderbird Conversation version:** 4.0.1
* **Operating System:** Windows 11

When replying to a message, the "compose reply" window has the address line field with as the default input focus. Usually, the default input focus for the "compose reply" window is where you type the message. This is a little annoying since I'm used to immediately typing the response after hitting "reply". But now I have to do an extra click to move the input focus to the compose message pane.

**Comment by Standard8** [comment]
Hi, this is an issue within Thunderbird itself: https://bugzilla.mozilla.org/show_bug.cgi?id=1732558 - it likely affects any add-on that uses a certain Thunderbird provided API.

The workaround for now is to use shortcuts (e.g. ctrl/cmd-r) or menus from outside of the Conversation pane.

I will try and see if we can get that moved forward.

**Comment by dkapz** [comment]
I have this too - disabling the add-on has fixed it. What you mention above with using ctrl-R only worked intermittently for me. Will keep an eye on this as your add-on is great!

**Comment by Standard8** [comment]
Thunderbird 93.3.1 has now been released and includes the bug fix mentioned above.

**Comment by llavegrifa** [comment]
Hi I'm on 128.8.1esr (64-bit) and still suffer from this bug
LG
