### ISSUE TITLE
PDF: Select to open in preview or external program

### ISSUE THREAD

**Issue by mke83** [thunderbird-conversations/thunderbird-conversations#1744]
* **Thunderbird version:** 91.2.1
* **Thunderbird Conversation version:** 4.0.5
* **Operating System:** Windows 10

**What did you do?**
Since the update to new Version of thunderbird i cannot choice between preview an pdf file ore open in an external program.
**What did you expect to happen?**
The eye symbol is missing to preview. I can set it to open always in thunderbird, but then big and complicated pdf files cant´t be opened in adobe acrobat reader
**What actually happened?**
It opens it always in preview or external. I would like to select every time.

**Comment by Standard8** [comment]
To allow selection each time, go into Options, under the "General" section there is "Files & Attachments", in there change the option next to "Portable Document Format (PDF)" to be "Always Ask".

You'll then be able to choose what you want to do.

This is slightly more steps to open PDFs, but we're trying to be more consistent with the Thunderbird UI flow now that PDF handling is incorporated directly to Thunderbird.

**Comment by mke83** [comment]
I really like the preview function of the new version, as simple documents such as invoices can be easily printed and displayed very quickly.
Large and complicated documents would be great if you could open them with an extra button in Adobe Acrobat Reader.

**Comment by Standard8** [comment]
In the built-in preview, you can easily open or download the pdf. See the top-right of the toolbar, you want the icon that's third from the right:

<img width="174" alt="Screenshot 2021-11-06 at 10 13 19" src="https://user-images.githubusercontent.com/520844/140606047-747305d8-668b-4555-9445-27d31df056fa.png">

**Comment by Standard8** [comment]
@mke83 does the solution above work for you?

**Comment by mke83** [comment]
@Standard8 yes this is working! 
Thank you!
I havent seen this symbol before.

**Comment by Standard8** [comment]
Ok great. I'll close this out, as I don't think we need to change Conversations at this time.
