### ISSUE TITLE
Inbox folders are not combined

### ISSUE THREAD

**Issue by victorbaars** [thunderbird-conversations/thunderbird-conversations#1756]
Hello, Thanks for an amazing product. I use it for years, and now I am updated to Windows 11, and reinstall Thunderbird, once I install Conversations the folders on the left panels, stay the same way as before rather than be combined as All inboxes, All Trash, All sent. Could you let me know how to fix the issue?

* **Thunderbird version: 91.3.2**
* **Thunderbird Conversation version:  4.0.5 **
* **Operating System: Windows 11**

**Initial install of Conversations**

**Inbox folders from different account combined together**

**They didn't**

**Comment by Standard8** [comment]
This is a different folder view that is part of Thunderbird itself and not Conversations. You need to go to the three-bar menu -> View -> Folders -> Unified.

**Comment by victorbaars** [comment]
@Standard8 You are saver! Thank you!
