### ISSUE TITLE
answer and answer to all does not work since 4.0.7

### ISSUE THREAD

**Issue by Siggi0904** [thunderbird-conversations/thunderbird-conversations#1759]
Hi, since update from today at amo (version 4.0.7) the answer and answer to all function does not work.
Only in classical view answering works.

Sorry if the buttons has another wording, I only see german version.

Thanks.

**Comment by Standard8** [comment]
Please can you try going to the three-bar application menu, select Tools -> Developer Tools -> Error Console. Then try clicking on the reply or reply all buttons and see if any errors appear.

If you do get any, please copy and paste them here.

**Comment by Siggi0904** [comment]
Okay, there is the log:

`Uncaught (in promise) TypeError: defaultAccount is null
    getBestIdentityForReply chrome://conversations/content/902.bundle.js:5263
902.bundle.js:5263:30
`

**Comment by Standard8** [comment]
Thank you.

It looks like for some reason your Thunderbird doesn't have a default account set up. Try this:

* Go to the application (3-bar) menu, then Account Settings.
* In the account settings, ensure one of your accounts on the left is selected.
* Under the accounts list there is a "Account Actions" drop-down.
* Select the "Set as Default" option under there.

Then see if that helps, you might need to restart Thunderbird for it to fully take effect.

**Comment by Siggi0904** [comment]
Hi, looks good. Works fine. Thanks.
