### ISSUE TITLE
Unrelated Conversations Being Linked Together

### ISSUE THREAD

**Issue by parkel42** [thunderbird-conversations/thunderbird-conversations#1760]
* **Thunderbird version: 91.3.2**
* **Thunderbird Conversation version: 4.0.8**
* **Operating System: Windows 10 64 bit**

**What did you do?**

Opened a email that's supposed to be unrelated to any other email.

**What did you expect to happen?**

Email should not have a conversation thread. 

**What actually happened?**

Email was linked to another completely unrelated email. See the following screenshots: 

* A newsletter from Humble Bundle was threaded together with an email alert from my bank. 
![Unrelated 1](https://user-images.githubusercontent.com/50959479/144690594-aa549cb1-eb9b-4c24-b986-ec5e6d3da81a.png)

* A newsletter from Fanatical Bundles was threaded together with another completely unrelated email. 
![Unrelated 2](https://user-images.githubusercontent.com/50959479/144690600-5eea9f42-c3d8-498d-a175-7dd8c16ba462.png)

**Comment by Standard8** [comment]
Hi, this is most likely a Thunderbird issue.

Try this:
* Click on the three dots at the right of one of the message headers
* Select "View using the classic reader"
* Then in the new message tab that opens there should be a "More" menu, select "Open in Conversation" from there.

If that shows both messages as well, then this is an issue with the conversation handling within Thunderbird.

**Comment by parkel42** [comment]
Hi, 

Just tried it. It does seem to a be Thunderbird issue. I'll submit a bug report over there instead. 

Thanks!

**Comment by Standard8** [comment]
Thank you for confirming.
