### ISSUE TITLE
The text of the conversations is not opened (even by clicking)

### ISSUE THREAD

**Issue by Rmano** [thunderbird-conversations/thunderbird-conversations#1764]
First of all, thank you for this extension, I find it extremely useful. I have a little problem sometimes for which  I have not been able to find a 100% reliable trigger, although it's quite frequent. 

* **Thunderbird version:** 78.14.0
* **Thunderbird Conversation version:** 3.2.35
* **Operating System:** linux (Ubuntu 20.04) 

**What did you do?** 
While looking at conversation, sometimes (I think it happens when I am cleaning the Inbox, that is, deleting or moving messages) the text in the conversation tabs never expand. For example, I have this view: 

![image](https://user-images.githubusercontent.com/6414907/145017897-df7bcd95-fc7a-4c91-80cc-8658c5f12498.png)

and clicking on the last message just toggles between the header line and this:

![image](https://user-images.githubusercontent.com/6414907/145018081-8886e91c-5956-4244-9103-c1b20ed36508.png)

**What did you expect to happen?**

The clicked message in conversation should expand fully, I think. 

**What actually happened?**

Just the first few words of the message are visible. The fun thing is, if I select "show the message in the traditional viewer", the message correctly open in another tab, and when I switch back to the main "Inbox" tab all is ok

![image](https://user-images.githubusercontent.com/6414907/145018944-71d96b63-ae77-4a33-bb08-db5e402f67a2.png)

Now the extension starts working correctly again. Until, after moving/deleting some other message, it happens again.

It's not a show-stopper by any means, but it slows down reading mails...

**Comment by Lukjan38** [comment]
after clicking on the e-mail list, the e-mail text does not appear, but a white page, you have to click a second time

**Comment by Rmano** [comment]
When it happens --- I click several times on the e-mail, and it simply toggles between the first two images I posted above. The only way to have the full email back is to use "view with the traditional viewer" and then go back...

When it happens again I will try to record an animated git of the thing...

**Comment by Rmano** [comment]
Ok, here a video with the problem (it's only half-blurred, please do not use outside the scope of the bug-report)

https://user-images.githubusercontent.com/6414907/145810049-28f3aa84-f721-4462-a2f5-0a623e3cebdc.mp4

**Comment by Rmano** [comment]
@Standard8 will do, thanks (really I should have thought about it by myself).

**Comment by Rmano** [comment]
Ok, it seems that with the console open I can't trigger it. I do not know if this could be a Heisenbug... nevertheless, I have errors from conversation, and "flashes" on the message that *seems* similar to what happens... but with the console open it seems to work ok. I don't even know if this is possible.

![image](https://user-images.githubusercontent.com/6414907/146540897-4238abdb-abb3-41dd-a980-e2544f8ed869.png)

```
onversations.Conversation: Warning: gloda query returned no messages conversation.js:235:17
Conversations.Message: Streaming the message because Gloda has not indexed it, this is BAD message.js:592:9
Lightning: Couldn't find Romance Standard Time 1 3 CalTimezoneService.jsm:201
NS_ERROR_NOT_AVAILABLE: ActivityManager.jsm:127
TypeError: this._htmlPane.conversationDispatch is not a function
conversation.js:200:22
    dispatch chrome://conversations/content/modules/conversation.js:200
    removeMessage chrome://conversations/content/modules/conversation.js:469
TypeError: this._htmlPane.conversationDispatch is not a function
conversation.js:200:22
    dispatch chrome://conversations/content/modules/conversation.js:200
    removeMessage chrome://conversations/content/modules/conversation.js:469
TypeError: htmlPane is undefined
conversation.js:354:1
TypeError: this._htmlPane.conversationDispatch is not a function
4 conversation.js:200:22
    dispatch chrome://conversations/content/modules/conversation.js:200
    removeMessage chrome://conversations/content/modules/conversation.js:469
TypeError: this._htmlPane.conversationDispatch is not a function
conversation.js:200:22
    dispatch chrome://conversations/content/modules/conversation.js:200
    removeMessage chrome://conversations/content/modules/conversation.js:469
Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. 48.bundle.js:3466:27
TypeError: this._htmlPane.conversationDispatch is not a function
conversation.js:200:22
    dispatch chrome://conversations/content/modules/conversation.js:200
    removeMessage chrome://conversations/content/modules/conversation.js:469
NS_ERROR_NOT_AVAILABLE: ActivityManager.jsm:127
```

**Comment by Rmano** [comment]
Ok, it happened and I have these errors: (but just a couple of times, now I can't trigger them anymore even if the behavior is still the "bad" one).

```
Uncaught (in promise) ReferenceError: Conversations is not defined
    msgStreamMsg chrome://conversations/content/stub.bundle.js:1456
    createThunkMiddleware chrome://conversations/content/928.bundle.js:608
    componentDidUpdate chrome://conversations/content/48.bundle.js:3336
    Yi chrome://conversations/content/415.bundle.js:412
    dk chrome://conversations/content/415.bundle.js:452
    unstable_runWithPriority chrome://conversations/content/415.bundle.js:545
    gg chrome://conversations/content/415.bundle.js:315
    Uj chrome://conversations/content/415.bundle.js:445
    Lj chrome://conversations/content/415.bundle.js:436
    jg chrome://conversations/content/415.bundle.js:316
    unstable_runWithPriority chrome://conversations/content/415.bundle.js:545
    gg chrome://conversations/content/415.bundle.js:315
    jg chrome://conversations/content/415.bundle.js:316
    ig chrome://conversations/content/415.bundle.js:315
    Wj chrome://conversations/content/415.bundle.js:437
    notify chrome://conversations/content/928.bundle.js:399
    notifyNestedSubs chrome://conversations/content/928.bundle.js:470
    handleChangeWrapper chrome://conversations/content/928.bundle.js:475
    dispatch chrome://conversations/content/928.bundle.js:989
    createThunkMiddleware chrome://conversations/content/928.bundle.js:611
    dispatch chrome://conversations/content/928.bundle.js:1339
    updateConversation chrome://conversations/content/48.bundle.js:1215
```
Notice that it happened *without* the error console being opened. I can't manage to have it happen if I previously open the console.

**Comment by Standard8** [comment]
Do you have any idea of the potential triggers leading up to this? For example, was the message pane blank when you selected the message thread, or have you come from a different message thread?

It might also be worth seeing if it reproduces with Conversation's debugging turned on (in Conversation's preferences), and see if you can get a fuller log.

**Comment by Standard8** [comment]
I do have one idea that might fix this, but it'll likely take a bit of a rewrite to be able to do it.

**Comment by Rmano** [comment]
Sorry if I am a bit late --- I was (and still almost am) off the grid. The thing happens more when I am "pruning" conversations --- selecting some of the older messages and moving them to other folders or deleting them. Thanks for looking at it and Happy

**Comment by Standard8** [comment]
Is this still an issue in the 4.0.14 that was released on Thursday? There's quite a few changes for how message loading works, so hopefully that's improved things?

**Comment by Standard8** [comment]
Closing this out as I think it is fixed now.
