### ISSUE TITLE
Clicking links does nothing (when a message is viewed in a new message window)

### ISSUE THREAD

**Issue by brtwrst** [thunderbird-conversations/thunderbird-conversations#1766]
* **Thunderbird version:** 91.4.0
* **Thunderbird Conversation version:** 4.0.8
* **Operating System:** Windows 10

![image](https://user-images.githubusercontent.com/6873862/146176899-92b567a5-22f7-4f53-8ce4-7949cecf55a4.png)

### Settings
I use thunderbird conversations with the recommended setting but in conjunction with the above setting of opening messages in a new message window.

### What is the issue? 
* When I click any link, in an email that is viewed in a "new message window", nothing happens. (the link is however marked as visited by a different color)

#### Observation
* When I click a link (in the same email message) while it is viewed in the "preview pane" or in a "new tab" (so not in a new message window), everything works as expected.
* When I disable the conversations addon links are also followed as normal, even if viewed in a new message window.

**Comment by Standard8** [comment]
Thank you for the report, I've fixed the issue, will hopefully release a new version soon with it in.
