### ISSUE TITLE
blank message box when selected

### ISSUE THREAD

**Issue by Lukjan38** [thunderbird-conversations/thunderbird-conversations#1767]
after selecting an e-mail to read, the window is empty, you need to select it a second time

**Comment by Standard8** [comment]
Please can you confirm your Thunderbird version and Conversations version, as requested by the template, it frequently helps to confirm which version you are on.

Please can you try having the error console open when you are able to reproduce this and see if anything appears on the console when you first click the message, and then when you re-select it.

You can access the error console via the hamburger menu -> Tools -> Developer Tools -> Error Console

**Comment by Lukjan38** [comment]
Unexpected event profile-after-change URLQueryStrippingListService.jsm:224
Unknown Collection "thunderbird/query-stripping" RemoteSettingsClient.jsm:160
Successfully loaded OpenPGP library rnp.dll version 0.15.2+git20210806.dd923a4e.MZLA from C:\Program Files\Mozilla Thunderbird\rnp.dll RNPLib.jsm:92:15
Found 0 public keys and 0 secret keys (0 protected, 0 unprotected) RNPLib.jsm:288:15
[l10nregistry] Attempting to synchronously load file
            resource:///chrome/en-US/locale/en-US/calendar/messenger/otr/otrUI.ftl while it's being loaded asynchronously. L10nRegistry.jsm:597:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no] L10nRegistry.jsm:692:19
Trying to load C:\Program Files\Mozilla Thunderbird\libotr.dll OTRLib.jsm:64:11
Successfully loaded OTR library C:\Program Files\Mozilla Thunderbird\libotr.dll OTRLib.jsm:72:13
services.settings: thunderbird/hijack-blocklists has signature disabled RemoteSettingsClient.jsm:1027

**Comment by Lukjan38** [comment]
Unexpected event profile-after-change URLQueryStrippingListService.jsm:224
Unknown Collection "thunderbird/query-stripping" RemoteSettingsClient.jsm:160
Successfully loaded OpenPGP library rnp.dll version 0.15.2+git20210806.dd923a4e.MZLA from C:\Program Files\Mozilla Thunderbird\rnp.dll RNPLib.jsm:92:15
Found 0 public keys and 0 secret keys (0 protected, 0 unprotected) RNPLib.jsm:288:15
[l10nregistry] Attempting to synchronously load file
            resource:///chrome/en-US/locale/en-US/calendar/messenger/otr/otrUI.ftl while it's being loaded asynchronously. L10nRegistry.jsm:597:19
[Exception... "Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIXPCComponents_Utils.readUTF8URI]"  nsresult: "0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH)"  location: "JS frame :: resource://gre/modules/L10nRegistry.jsm :: L10nRegistry.loadSync :: line 692"  data: no] L10nRegistry.jsm:692:19
Trying to load C:\Program Files\Mozilla Thunderbird\libotr.dll OTRLib.jsm:64:11
Successfully loaded OTR library C:\Program Files\Mozilla Thunderbird\libotr.dll OTRLib.jsm:72:13
services.settings: thunderbird/hijack-blocklists has signature disabled RemoteSettingsClient.jsm:1027
Conversations.Conversation: Warning: gloda query returned no messages conversation.js:230:17
Conversations.Conversation: Streaming the message because Gloda has not indexed it, this will be slower conversation.js:123:7
old dispatch stubGlobals.js:18:13

**Comment by Standard8** [comment]
Thank you for the log, that was just enough to fix what I think was the issue.

In future, it would be appreciated if you include the FULL information requested, that frequently makes it easier when looking at reports.

**Comment by Lukjan38** [comment]
so after the update, will it be okay?
