### ISSUE TITLE
Broken Conversations

### ISSUE THREAD

**Issue by MartinX3** [thunderbird-conversations/thunderbird-conversations#1768]
* **Thunderbird version:** 91.4.1
* **Thunderbird Conversation version:** 4.0.8
* **Operating System:** Arch Linux

**What did you do?**
Open an E-Mail preview

**What did you expect to happen?**
My conversations (my answers and the opponent answers in a row.)

**What actually happened?**
I see only my answers in a row in inbox and only the opponents answers in a row in the sent folder.

**Comment by Standard8** [comment]
Please can you provide more detail, maybe a screenshot?

It sounds like the global indexer isn't working, but I'm not quite sure.

Are you seeing any errors on the error console? You can access it via the hamburger menu -> Tools -> Developer Tools -> Error Console.

**Comment by MartinX3** [comment]
I have 2 laptops with thunderbird (one for my job with only the job account)
The global index is deactivated on both since this week, because thunderbird used a high amount of cpu power while being idle in the background since months.
But on the job laptop the conversations are looking normal, while on the private laptop the conversations are only showing everything from sent or from receive, depending in which folder I look.

My error log says that the gloda (global indexer) query returned no messages 
```Conversations.Conversation: Warning: gloda query returned no messages conversation.js:230:17
Conversations.Conversation: Streaming the message because Gloda has not indexed it, this will be slower conversation.js:123:7
Conversations.Conversation: Warning: gloda query returned no messages conversation.js:230:17
Conversations.Conversation: Streaming the message because Gloda has not indexed it, this will be slower conversation.js:123:7
```

Could it be that conversations caused my indexer to run amok in the background while it should idle?
One of my 2 job accounts have 1500 emails.
In theory the indexer should be silent after it indexed every email, but the cpu usage did never go down.
So I assume it retries to do things everytime?

**Comment by Standard8** [comment]
Conversations relies on the global indexer to work properly - that is where it gets the information about the conversations from, so if you don't have that enabled, then it will only display the selected messages.

As you've already turned indexing off, I'd suggest removing the `global-messages-db.sqlite` from [your profile](https://support.mozilla.org/kb/profiles-where-thunderbird-stores-user-data) (this is the file that stores the index), and then turning indexing back on and see what happens (you may need to restart after turning it back on).

It can take quite a while to index, but I'd have expected no more than a few hours. If the indexer isn't completing, that is most likely a Thunderbird issue - which should be filed at https://bugzilla.mozilla.org/
