### ISSUE TITLE
Conversations in Thunderbird Mac truncates text in messages.

### ISSUE THREAD

**Issue by WinstonBarns** [thunderbird-conversations/thunderbird-conversations#1771]
Thunderbird 91.4.1 in Mac OS 10.15.7
In CONVERSATIONS, often the text in an email in a string is truncated.

**Comment by Standard8** [comment]
I'm a little surprised by this as the email itself is rendered by Thunderbird, and Conversations only adjusts quotations in the message.

Are you sure that it is not hidden by a horizontal scroll?

Please can you provide some examples and screenshots? Especially how it compares to when you view the message in the classic reader.

**Comment by Standard8** [comment]
Without further information, I can't do anything more here.
