### ISSUE TITLE
Master passoword bypass

### ISSUE THREAD

**Issue by Bortex19** [thunderbird-conversations/thunderbird-conversations#1776]
91.5.1
91.5.1
Windows 10

I cancel the pop up to put the Master password for enter in the app

The app should remain closed

The app open and it shows my inbox, fields and more personal info.

**Comment by Standard8** [comment]
This tracker is not for reporting issues with Thunderbird. It is for reporting issues with Thunderbird Conversations, an add-on to Thunderbird.

However, please note that the master password is NOT intended to protect access to your Thunderbird application.

The master password ONLY protects your passwords.

Even if it did stop access to Thunderbird, a user could easily access all the saved data on disk.

You should either not let other users have access to your accounts, or you should use a third party program to effectively sandbox the applications that you don't want other to allow access to.

Please see here for more information: https://support.mozilla.org/kb/protect-your-thunderbird-passwords-master-password
