### ISSUE TITLE
In-line replies lock up at "Sending message..." (OWL add-on installed)

### ISSUE THREAD

**Issue by eraguzin-bnl** [thunderbird-conversations/thunderbird-conversations#1777]
* **Thunderbird version:**91.4.1
* **Thunderbird Conversation version:**4.0.9
* **Operating System:**Manjaro 21.2.1

**What did you do?** Click the reply button in the conversation. I then typed in my reply and clicked "send".

**What did you expect to happen?** The message gets sent.

**What actually happened?** The quick reply window showed "Sending message..." and hung indefinitely (tested for minutes for a short text-only message). I tried responding and sending to multiple correspondences and could not get any messages to send.

For further context, the only other extension I have is OWL, as my email address is connected to an Exchange server. When I switch to a new email folder while the quick reply window is hung, a message comes up saying "This page is asking you to confirm that you want to leave — information you’ve entered may not be saved."

Is there any way I can share logs of any errors or warnings?

**Comment by Standard8** [comment]
Can you try opening Tools -> Developer Tools -> Error Console and see if any messages appear when you try to send a message?

There should be a bunch of logging messages, but there may also be errors as well - all of them would be nice.

There's a trash icon at the top where you can clear the console of current errors. You can also right-click and select-all and then use ctrl-c to copy everything.

**Comment by eraguzin-bnl** [comment]
Yes, the error messages are:

![image](https://user-images.githubusercontent.com/32136565/151674883-a458f50c-aa3c-47e2-b14a-91130a1bcc56.png)

Although it says server is null, I was immediately able to send the same message by clicking the standard Thunderbird "reply" and sending through the popup window.

**Comment by Standard8** [comment]
Thank you for those errors. I suspect this is to do with how OWL are setting up their sending servers. I've checked the Conversations code and I believe I'm doing the right thing. However, as I don't have an exchange server setup, it is hard for me to work out what's happening.

Can I suggest that you get in touch with their support and show this to them? If it needs fixes for Conversations then I'm quite happy to make changes, but I think this needs investigation from their side first.

**Comment by eraguzin-bnl** [comment]
Thanks for the response. I'll get in touch with them and see.

**Comment by eraguzin-bnl** [comment]
They responded that OWL doesn't support other extensions.

**Comment by Standard8** [comment]
Wow, that's sad. Conversations doesn't do particularly well with some issues, but we try to where possible (or at least find out why it isn't possible).

I'll see if I can take another quick look one evening this week. I think it is most likely to do with how OWL are implementing their message sending side, so it is probable we can't work around it, but I'll see if I can figure out what they're changing at least.

You can if you want turn off the display of the quick reply in the add-on settings - seeing as it isn't useful.

**Comment by eraguzin-bnl** [comment]
Thank you very much for the follow up. I'll wait for a notification here, hopefully a positive one!
