### ISSUE TITLE
Message author bubble color disappeared

### ISSUE THREAD

**Issue by adomasven** [thunderbird-conversations/thunderbird-conversations#1778]
* **Thunderbird version:** 91.5.0 (64-bit)
* **Thunderbird Conversation version:** 4.0.9
* **Operating System:** Ubuntu 20.04 with Unity

Hi, after updating Thunderbird (or rather, Ubuntu updating it for me) to version 91.5.0 the author bubble color disappeared.

Example from the AMO store
![image](https://user-images.githubusercontent.com/5899315/151760627-c36bbfc6-0f61-4598-84e2-cd5d6f2f5736.png)

Screenshot from my computer
![image](https://user-images.githubusercontent.com/5899315/151760644-748403c7-c5f5-483c-a9d8-e94f9e0cd722.png)

This is severely reducing the glanceability of the conversation authors.

**Comment by Standard8** [comment]
I have no idea why this would be. Are you sure you don't have a userChrome.css in your profile or something like that?

The colours for these are directly set on the element, so I don't think there would be any conflicts with themes/other colours unless something was specifically messing with that element.

**Comment by Standard8** [comment]
I tried this on Ubuntu and couldn't reproduce. My only thought would be a conflicting userChrome.css file or something.

**Comment by adomasven** [comment]
I've discovered that this is caused by color overriding setting in TB. I don't know why I had those settings changed from default, but if someone else runs into this, here's how to fix it:

Thunderbird Settings -> General -> Fonts & Colors -> Colors...
In the dialog change the bottom select box from "Always" to "Only with High Contrast themes".
