### ISSUE TITLE
Embedded images are blocked in conversation view, shown on "classic view"

### ISSUE THREAD

**Issue by Rmano** [thunderbird-conversations/thunderbird-conversations#1783]
* **Thunderbird version:**

Name 	Thunderbird
Version 	91.5.0
Build ID 	20220106182030
Distribution ID 	
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Thunderbird/91.5.0
OS 	Linux 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022
Application Binary 	/usr/lib/thunderbird/thunderbird
Profile Directory 	
(Local drive)
Build Configuration 	about:buildconfig
Memory Use 	about:memory
Performance 	about:performance
Registered Service Workers 	about:serviceworkers
Multiprocess Windows 	0/0
Fission Windows 	0/0 Disabled by default
Remote Processes 	2
Enterprise Policies 	Inactive
Google Location Service Key 	Missing
Google Safebrowsing Key 	Missing
Mozilla Location Service Key 	Missing
Safe Mode 	false
Profiles 	about:profiles
Telemetry Data 	about:telemetry

* **Thunderbird Conversation version:**
4.0.10

* **Operating System:**
Linux

**What did you do?**
Read messages with embedded images

**What did you expect to happen?**
See the image

**What actually happened?**
The image is not shown --- I have an error in the console. But opening the mail in the classic viewer **will** show the image. 

In conversation:

![image](https://user-images.githubusercontent.com/6414907/152325212-344cc118-956a-46e8-b23e-0cd066888ef5.png)

the error:

![image](https://user-images.githubusercontent.com/6414907/152325303-5f01dece-e85e-4345-a880-29264e63d0d1.png)

But if I "open in classic reader" I *do* see the image and I have no errors:

![image](https://user-images.githubusercontent.com/6414907/152325428-72897d61-7f84-490b-84f7-3fb3aabe5202.png)

**Comment by Standard8** [comment]
Thank you for reporting, this was a regression in 4.0.10 cause by making something too strict.

4.0.11 has just been approved on the add-ons site, so you should be able to update that via the add-ons manager.
