### ISSUE TITLE
Images does not show in messages

### ISSUE THREAD

**Issue by eminaguil** [thunderbird-conversations/thunderbird-conversations#1784]
* **Thunderbird version:**  91.5.1
* **Thunderbird Conversation version:** 4.0.10
* **Operating System:** Linux Debian 10.10

**What did you do?**
Thunderbird and conversation both have been updated

**Issue**
Images are not displayed in convesations, when I disable the plugin they are shown in thunderbird.
I've restarted thundebird, linux, reinstalled the plugin and the images continues not showing with the plugin enabled.

**Comment by Standard8** [comment]
A new version - 4.0.11 was released earlier today. Please update to that.
