### ISSUE TITLE
Encrypted subjects are not decrypted

### ISSUE THREAD

**Issue by MartinX3** [thunderbird-conversations/thunderbird-conversations#1786]
* **Thunderbird version:** 91.5.1
* **Thunderbird Conversation version:** 4.0.11
* **Operating System:** Arch Linux

**What did you do?**
Click on an e-mail

**What did you expect to happen?**
Decrypted subject

**What actually happened?**
I only see ...

**Additional informations**
If I disable the plugin, the subject gets decrypted, if I click on the email.
It happens to single emails without conversation.

Workarounds:
- Open the email in the classic mode
- Disable the addon and use https://support.mozilla.org/en-US/kb/message-threading-thunderbird

**Comment by jkuj6** [comment]
I can confirm this is indeed an issue on my side too.

Thunderbird Conversation version: 4.0.12

**Comment by jkuj6** [comment]
In addition to the subject line not showing or being decrypted issue, the attachment part is doing the same thing. Does not show in Thunderbird Conversations message pane at the bottom where its supposed to have decrypted it so there is nothing there.

It shows up in classic reader though.
