### ISSUE TITLE
Conversations view showing completely different mails as thread

### ISSUE THREAD

**Issue by sriharshachilakapati** [thunderbird-conversations/thunderbird-conversations#1789]
![చిత్రము](https://user-images.githubusercontent.com/4593204/153215112-ac646bb4-bb55-46a3-b69b-508a455e18d7.png)

![చిత్రము](https://user-images.githubusercontent.com/4593204/153216025-75bbbe61-676b-4fdb-83c6-551b4fd72a88.png)

Firefox bug tracker, GitHub Actions Bot and Axis Bank are totally unrelated players to me, and they are grouped together as a single thread. I don't see this threading behaviour in the view tree of inbox in Thunderbird. Only this extension is thinking that they are related.

* **Thunderbird version:** 91.5.1
* **Thunderbird Conversation version:** 4.0.11
* **Operating System:** Windows 11

**Comment by Standard8** [comment]
Hi, whilst the add-on displays the conversations, it is Thunderbird that generates the conversation lists - which messages are grouped together. The add-on only takes that information to use to build the display.

You could try [rebuilding the global database](https://support.mozilla.org/kb/rebuilding-global-database) and see if that helps.

If that doesn't work, please file a bug at https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird

**Comment by Standard8** [comment]
The mail list uses a slightly different mechanism to determine the threading. The indexer can sometimes get it wrong, as it also tries to fix some things where the standard message threading can sometimes be broken.
