### ISSUE TITLE
No longer see allow remote content/allow all remote content from (sender) prompts in message pane

### ISSUE THREAD

**Issue by Bsteener** [thunderbird-conversations/thunderbird-conversations#1792]
Tbird 91.6.0 32-bit
Conversations 4.0.11
Windows 10 Home 21H2

Can no longer allow remote content from the message pane.  Have to open message in Classic Reader, select Options, and allow from there.  Disabling Conversations add-on causes the prompts to show again.  Worked fine until recently, but can't say exactly what update broke it.

**Comment by Bsteener** [comment]
Not sure if it was the recent T-bird update or just disabling and re-enabling, but it is working now.  Please disregard.

**Comment by Standard8** [comment]
Thank you for following up.
