### ISSUE TITLE
Opening a message in a new window makes that message open every time the related inbox is selected

### ISSUE THREAD

**Issue by Slater91** [thunderbird-conversations/thunderbird-conversations#1794]
* **Thunderbird version:** 91.6.0
* **Thunderbird Conversation version:** 4.0.11
* **Operating System:** Linux (Ubuntu 20.04-based distro)

**What did you do?**
I opened a message from a conversation in inbox A in a new window. I then selected another conversation, then switched to inbox B, then came back to inbox A.

**What did you expect to happen?**
I expected inbox A to open without showing any message, or showing the most recent message.

**What actually happened?**
The message I opened in another window keeps on getting selected. This stays true even if I close the new window and keeps on happening unless I restart Thunderbird. This is always reproducible.

**Comment by Standard8** [comment]
I took a look at this earlier and found it is actually a [bug in Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1355195). It shows up more in Conversations because of the way Conversations requires the use of different message views.

**Comment by Standard8** [comment]
I believe this is now fixed in Thunderbird 115.

**Comment by Standard8** [comment]
Note: I think this was fixed as a side-effect of all of Thunderbird's changes in 115.
