### ISSUE TITLE
Replying to a message does not set the IMAP flag "replied"

### ISSUE THREAD

**Issue by almereyda** [thunderbird-conversations/thunderbird-conversations#1797]
* **Thunderbird version:** 91.5.0
* **Thunderbird Conversation version:** 4.0.12
* **Operating System:** Ubuntu 21.10

**What did you do?**

Answer to a message.

**What did you expect to happen?**

The original message gets the nifty *reply* flag that shows me it was already answered.

**What actually happened?**

An answer is sent, but the originating message is not updated with the corresponding IMAP `\Reply` flag.

**Comment by almereyda** [comment]
Thank you for helping me to triage this further.

This was using the inline "Answer All" reply mechanism, and the response correctly goes to sent.

Unfortunately I am currently not with access to the affected machine, but will report back, once back in posession (~ 2 weeks).

**Comment by Standard8** [comment]
Have you been able to try this again?

Could you also check it with Conversations turned off?

**Comment by almereyda** [comment]
Sorry for the delay. I still don't have access to the machine, and might around end of the month. Thanks for waiting.

**Comment by Standard8** [comment]
I've not heard any other reports of this, and without more information I'm unfortunately not going to be able to do anything. Closing this out for now.

**Comment by almereyda** [comment]
Thanks for maintaining this while I was away.

Apparently this happened again, now also on the Thunderbird 115 compatible version.

I will now disable Conversations and report back, in case the described behaviour also occurs then.
