### ISSUE TITLE
"Recent messages" button does not open recent messages list

### ISSUE THREAD

**Issue by Slater91** [thunderbird-conversations/thunderbird-conversations#1799]
* **Thunderbird version:** 91.6.1
* **Thunderbird Conversation version:** 4.0.12
* **Operating System:** Linux (KDE neon, based on Ubuntu 20.04)

**What did you do?**
I clicked on the "recent messages" button in the pop-up that appears when hovering the mouse cursor over the sender's name in a conversation.

**What did you expect to happen?**
I expected the list of recent messages to open.

**What actually happened?**
Nothing. No output is registered in the error console, either.

Weirdly enough, this does work for some senders, but not others. I couldn't infer a rule, neither based on email addresses, nor based on names, it appears to be just random. I can provide a screen recording to the developers under confidentiality terms.

**Comment by Slater91** [comment]
The emails are all in the inbox folder, so I would exclude the issue with folders. I've just tried now and emails a few days old still show the same behaviour.

I've tried typing into the search box and the address of at least one sender that shows this behaviour does show up in the autocomplete options.

**Comment by Standard8** [comment]
Can you also try selecting an email in the autocomplete of the main toolbar search? See if that comes up with results, but the option from Conversations doesn't?

Another thought is to try checking for errors on the error console - go to the three-bar menu -> Tools -> Developer Tools -> Error Console.

**Comment by Standard8** [comment]
@Slater91 were you able to try my comments above?

**Comment by Standard8** [comment]
Closing out, my best guess is this might have something to do with the global indexer, but without more information, I'm not going to be able to help further.

**Comment by Slater91** [comment]
Sorry, I missed the notification emails. Trying to select an email using the autocomplete feature in the main toolbar search does come up with results. Nothing comes up on the error console.
