### ISSUE TITLE
Unable to change text color in new email

### ISSUE THREAD

**Issue by marcoferroha** [thunderbird-conversations/thunderbird-conversations#1801]
* **Thunderbird version:** last
* **Thunderbird Conversation version:** last
* **Operating System:** win 11 64b last

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by Standard8** [comment]
Please can you provide a proper description? Especially where you are creating the new email. If you are using Thunderbird's standard compose window, then you should be filing this with Thunderbird.
