### ISSUE TITLE
Message incorrectly marked as read when expanded in thread

### ISSUE THREAD

**Issue by siefkenj** [thunderbird-conversations/thunderbird-conversations#1807]
* **Thunderbird version:** 91.4
* **Thunderbird Conversation version:** 4.0.12
* **Operating System:** Linux

When the "Automatically mark messages as read" is set to `false` and an unread thread is opened, expanding an item in the thread causes it to be marked as read. It should be left as unread.

**Comment by Standard8** [comment]
Hmm, this was originally introduced ~ 10 years ago in 5a4075caeb445f0087689aeb9228e3369cf66f6b. This makes me a little wary about changing it, though it does seem to be inconsistent with the fact that we turn off marking as read when scrolling if the pref is false.

I think we could probably try changing it and see what feedback we get.

**Comment by siefkenj** [comment]
I think that's the correct behavior unless the user has the `automatically mark messages as read` option set as `false` in the TB settings.
