### ISSUE TITLE
OpenPGP encrypted block shown in Conversations View instead of the decrypted message despite it being decrypted in Classic Reader

### ISSUE THREAD

**Issue by jkuj6** [thunderbird-conversations/thunderbird-conversations#1814]
* **Thunderbird version:** v91.5.0
* **Thunderbird Conversation version:** v4.0.12
* **Operating System:** Ubuntu 18.04

When i receive an encrypted email from a simple bash script, i can view the decrypted email in the Classic Reader, however the only thing that is shown in the Thunderbird Conversations message pane is the PGP encrypted message block instead of the decrypted message.  Any idea why this is?

Is there anyway you could help tell me if there is something specific missing from the headers or fix this issue from your side?

Below is the source headers of the received encrypted email:
```
X-Mozilla-Keys:                                                                                 
Return-Path: 
Delivered-To: 
Received: from 
	by 
	id 
	(envelope-from <>)
	for 
Return-path: 
Envelope-to: 
Delivery-date: 
Received: from 
	by 
	(Exim 4.94.2)
	(envelope-from <>)
	id 
	for 
Received: 
	
Subject: Testing
To: 
Date: 
Message-Id: 
From: 

-----BEGIN PGP MESSAGE-----

1QIMA9qLIHTjjIscAQ//RX20fvpYdvPpFEKsq5G5UVEO2RfOCG4nOk+tVFaod3UT
8508Q6eSxH+Ut4iaAa2i2stbp/uVrAJ/fuNCdmZ9FwZyB+Wa+XuFXRJ3hbU/BSXb
MVQkhLKKcP60srIZBeAnwSVlN+yCiUUXS
YwGxKKS3IvwcDdW9sHVcKJ42yDklvZTBKPNGEfC0J/O659kjZWkTrXr4qZnFlabI
RGD+8yYu9qpf8Fc61Da3X6x9PG/13dlzEXZnPvWXTEjRCJ/Rcwl4IybQlqZRHErd
UdHBQA==
=UDya
-----END PGP MESSAGE-----
```

**Comment by jkuj6** [comment]
Can someone have a look at this and provide a fix please?

Please note that even when disabling the addon, the decrypted message shows perfectly.

@Standard8

**Comment by Standard8** [comment]
Are you closing and opening the message pane, or potentially doing something else to read the emails other than using the standard message pane?

Failing that, taking a look to see if there's any messages on the error console might help (three bar menu -> Tools -> Developer Tools -> Error Console).

**Comment by sha-265** [comment]
Same problem. Some details:
```
Thunderbird version: v115.3.2
Thunderbird Conversation version: v4.1.3
Operating System: Ubuntu 23.04
```
Maybe relevant errors in developer console:
> Uncaught TypeError: MutationObserver.observe: Argument 1 is not an object.
>     <anonymous> chrome://conversations/content/stubWrapper.js:21

**Comment by Standard8** [comment]
The issue in 115 is the pinned issue #2006.

Closing this out as there's not enough information from the original issue to know what the problem was at the time.
