### ISSUE TITLE
"Error encountered while rendering." with thunderbird major release 91.7.0

### ISSUE THREAD

**Issue by Pulsahr** [thunderbird-conversations/thunderbird-conversations#1819]
Hello, I don't see any issue regarding this so I'm creating one.
If I disable the conversation plugin everything goes back to normal without errors (and without conversation view, obviously).

* **Thunderbird version:** 91.7.0. (32 bits)
* **Thunderbird Conversation version:** 3.2.26
* **Operating System:** Windows 10 Pro v. 21H1

**What did you do?**: displayed mail inbox with mail that should be a conversation

**What did you expect to happen?**: a conversation view

**What actually happened?**: 
The sender, title and greyish preview are correctly displayed. 
But in the body message I have "Error encountered while rendering."
The complete message is:

> **Error encountered while rendering.**
> TypeError: setting getter-only property "charset"
> 
> MessageIFrame@chrome://conversations/content/694.bundle.js:2288:5
> ErrorBoundary@chrome://conversations/content/694.bundle.js:3223:5
> div
> li
> Message@chrome://conversations/content/694.bundle.js:3262:5
> ul
> _MessageList@chrome://conversations/content/694.bundle.js:3631:13
> ConnectFunction@chrome://conversations/content/50.bundle.js:244:68
> _ConversationWrapper@chrome://conversations/content/694.bundle.js:3704:5
> ConnectFunction@chrome://conversations/content/50.bundle.js:244:68
> Provider@chrome://conversations/content/800.bundle.js:285:15

**Comment by Standard8** [comment]
Please update your Thunderbird Conversations version, the current version is 4.0.12.

**Comment by Pulsahr** [comment]
Apologies, I should have started by this.
