### ISSUE TITLE
tag assistance

### ISSUE THREAD

**Issue by jodamajster** [thunderbird-conversations/thunderbird-conversations#1822]
While using your module (which is great) i cant access buttons from https://addons.thunderbird.net/pl/thunderbird/addon/tag-toolbar/?src=search
for fast tag adding. i see in your module added tags but i cant access those not added to add them intuitively.

**Comment by Standard8** [comment]
Tag Toolbar uses a custom implementation to specifically extend Thunderbird's display. If that add-on could be re-written to use the new dedicated WebExtensions API, then it is something that Conversations could potentially support in the future (modulo #1665, depending on which API was used).

I'll close this out as this is really on Tag Toolbar's author to move to more supported methods, for find an alternative way.
