### ISSUE TITLE
Incompatible with Dark Reader

### ISSUE THREAD

**Issue by loyukfai** [thunderbird-conversations/thunderbird-conversations#1830]
**Thunderbird version: 91.8.1 (64-bit)
**Thunderbird Conversation version: 4.0.12
**Operating System: Windows 11

**What did you do?**
Enabling both Dark Reader (https://addons.thunderbird.net/en-us/thunderbird/addon/darkreader/) and this add-on

**What did you expect to happen?**
Message pane and tabs in dark mode.

**What actually happened?**
Message pane and tabs not in dark mode.

**Comment by Standard8** [comment]
The dark reader issue is covered by #1609 . You've already found the issue for dark mode support.

**Comment by loyukfai** [comment]
Thanks!

**Comment by loyukfai** [comment]
Just wondering, if the author of Dark Reader is willing, is it possible for him/her/they to adapt DR to work with your add-on?

I vaguely remember that there is a guide when I was looking for information about this but it led to a dead link.

Cheers.
