### ISSUE TITLE
The display of the names of the senders is broken 

### ISSUE THREAD

**Issue by arkadiy44** [thunderbird-conversations/thunderbird-conversations#1835]
After the last update of the add-on the names of the senders are displayed as letters and numbers (the display of the Cyrillic encoding is broken).

**Comment by NoSyu** [comment]
Same issue with Korean characters

![cap_1651902933](https://user-images.githubusercontent.com/2724705/167240749-57de47fe-2aa5-4d98-996f-213b3619f01a.jpg)
Broken sender name when I enable the addon

![cap_1651902963](https://user-images.githubusercontent.com/2724705/167240750-02815a13-b0ae-4c61-a7f3-da322bdc6fd6.jpg)
Original sender name when I disable the addon

**Comment by Standard8** [comment]
Thank you for the report, I've now fixed this in the code and will push a new version up for approval - it may take a couple of days before that gets approved.

**Comment by Standard8** [comment]
4.0.15 has just been approved, so if you update that should fix this now.

**Comment by NoSyu** [comment]
![image](https://user-images.githubusercontent.com/2724705/167414777-6c028ed0-5e15-4298-b988-6aa6f6c42845.png)
Yes, it works well on version 4.0.15
Thank you for quickly fixing the issue.

**Comment by arkadiy44** [comment]
Thank you!
