### ISSUE TITLE
When a draft has multiple receipients, the edit draft button is not shown in the message header

### ISSUE THREAD

**Issue by stratosjl** [thunderbird-conversations/thunderbird-conversations#1848]
* **Thunderbird version:** 91.9.1 (64-bit)
* **Thunderbird Conversation version:** 4.0.16
* **Operating System:** Windows 10

**What did you do?** Saved a draft to edit and send later. I have drafts saved in Local Folders. 

**What did you expect to happen?** When opening the conversation, there should be the option to continue editing the message

**What actually happened?** There was no "Edit" button available, as was the case before activating the addon. 

![Draft before TBConversations](https://user-images.githubusercontent.com/979708/170685555-d11c7589-298a-4b5f-b8bc-5ae0a950beb5.jpg)
![Draft after TBConversations](https://user-images.githubusercontent.com/979708/170685559-bd88552a-9046-4aa5-86a7-ec47cb6243c0.jpg)

**Comment by Standard8** [comment]
There is normally an edit button near the top-right and the bottom-right of the message:

<img width="192" alt="Screenshot 2022-05-27 at 11 53 01" src="https://user-images.githubusercontent.com/520844/170686300-ce2664e2-bbe7-457b-9000-d40a4bc4e4e2.png">

It appears that when multiple recipients are preset Conversations misses the fact it is a draft and hence displays reply all instead - but only at the top-right. The bottom-right is still the edit draft button.

As an alternative, you can also double-click on the message in the message list to edit the draft.

**Comment by stratosjl** [comment]
Thanks for correcting this!
