### ISSUE TITLE
Ctrl + F Find: Finds hidden text in the message summary snippets

### ISSUE THREAD

**Issue by OsadaP** [thunderbird-conversations/thunderbird-conversations#1851]
Thunderbird version: 91.9.1
Thunderbird Conversation version: 4.0.17

We search for text with the find function (Ctrl + F) and go to the next occurrence of this text. For example, if we have 1 expanded message and 20 collapsed messages, the view goes to the next messages but does not expand the message in which the text is located. Because of this it is not clear which message should be expanded in order to see the text.

**Comment by Standard8** [comment]
The find function doesn't exactly search for text within collapsed messages - they aren't normally loaded when a message is collapsed.

Instead it looks like it is searching the summary snippets that are in the collapsed message titles - the snippets are generally longer than what's displayed, so the text is hidden. Thunderbird isn't able to distinguish between text that's hidden and not hidden, and doesn't scroll to it either.

There's some existing issues on Thunderbird about this:
https://bugzilla.mozilla.org/show_bug.cgi?id=1013167
https://bugzilla.mozilla.org/show_bug.cgi?id=407817

Unfortunately there's nothing we can do about this from Conversations - we don't have the ability to monitor what find is doing, and therefore we can't affect that behaviour - this needs to be fixed on the Thunderbird side.
