### ISSUE TITLE
Ctrl+enter not working for sending message

### ISSUE THREAD

**Issue by joomlafun** [thunderbird-conversations/thunderbird-conversations#1854]
Hi, 

This maybe a feature request and not an actual issue, sorry if I posted this in the wrong place. 

* **Thunderbird version:** 91.8.1
* **Thunderbird Conversation version:** 4.0.17
* **Operating System:** kubuntu 20.4

**What did you do?**
CTRL+entering when composing

**What did you expect to happen?**
Send the email

**What actually happened?**
Not sending the email

**Comment by Standard8** [comment]
Duplicate of #1740
