### ISSUE TITLE
it chose wrong identity when i click reply icon 

### ISSUE THREAD

**Issue by nicolat80** [thunderbird-conversations/thunderbird-conversations#1856]
Thunderbird version: Version 91.10.0
Thunderbird Conversation version: 4.0.18
Operating System: win10
using two identities with the same e-mail address, one with my address and one with an alias address.

**What did you do?**
Click on "reply" or" reply all" icon (near the date) 

**What did you expect to happen?**
open up a reply message windows with my e-mail address in "from" field (that is setted as predefined identity)

![2](https://user-images.githubusercontent.com/107248745/173042188-f430d487-1e38-43ea-9d0c-7f05564a9600.png)

**What actually happened?**
sometimes it open a reply message using the second identity with the alias address in "from" field

![1](https://user-images.githubusercontent.com/107248745/173042827-2d7dfdf3-ef98-432c-9d92-c4738de7cdd8.png)

**Comment by Standard8** [comment]
Have you checked the addresses where the original message was sent to?

If you reply to an email, Conversations will look at the email you are replying to - to see which identities it was sent to. If it detects it was sent to your alias, then it will respond with your alias. If it is your main address, then it will use the main address.

**Comment by nicolat80** [comment]
Hi, and thanks for your reply and for your work! Yes I did some tests, even with messages sent directly to my address and without any other address in cc, but the problem still comes up.

**Comment by Standard8** [comment]
> using two identities with the same e-mail address, one with my address and one with an alias address.

To confirm, the two identities have different email addresses, but the account those identities are associated with is the same? If they have the same email addresses, then this would probably be #1750, that I've just fixed.

I think I'm probably going to need specific examples. I don't need exact emails, but it would help to have something like:

Account 1, Identity A, email a@a
Account 1, Identity B, email b@b

Email to a@a -> reply showed identity A
Email to a@a, cc b@b -> reply showed identity B

It might also be useful to know if the email is in a different account section, e.g. local folders.

**Comment by Standard8** [comment]
Please check Conversations v4.0.19 that was released a couple of weeks ago, if that hasn't fixed it, then I will need more details as per my previous comment. For now, I'm closing this out as there isn't enough information to fix it.
