### ISSUE TITLE
Emails composed in Conversations add-on aren't saving to Drafts

### ISSUE THREAD

**Issue by YamiYukiSenpai** [thunderbird-conversations/thunderbird-conversations#1866]
* **Thunderbird version:** 102.0
* **Thunderbird Conversation version:** 4.0.19
* **Operating System:** Kubuntu 22.10

**What did you do?**
I want to be able to save Emails composed through Thunderbird Conversations in the Drafts folder

**What did you expect to happen?**
Unfinished emails would automatically appear in Drafts

**What actually happened?**
Unfinished emails don't appear in Drafts, and doesn't sync with Outlook.

**Comment by Standard8** [comment]
Duplicate of #345
