### ISSUE TITLE
Unable to save to address book

### ISSUE THREAD

**Issue by Normdeb** [thunderbird-conversations/thunderbird-conversations#1876]
Thunderbird Updates
Version = 102.0.3 (64 bit)
Thunderbird is up to date
Windows 11 Pro 
Version = 10.0.22000 build 22000 x64
Intel Core i5-8400 CPU

**What did you do?**
Installed conversations and hovered mouse over the from field and once the window opened I clicked on the + icon to add the address in the from field to my address book.

**What did you expect to happen?**
I expected the address in the from field to be added to my address book.

**What actually happened?**
A very small error window opened and I could not read it.  I had to right click and maximise the window before I could see the error and the name of the window.  The window name was  "Problem loading page".  Inside the window was the error message -:

File not found
The file jar:file:///C:/Program Files/Mozilla Thunderbird/omni.ja!/chrome/messenger/content/messenger/addressbook/abNewCardDialog.xhtml cannot be found. Please check the location and try again.

    Check the file name for capitalisation or other typing errors.
    Check to see if the file was moved, renamed or deleted.

I checked the path/file name and found the directory omni.ja! did not exist.  Therefore none of the directory path or the file existed either.  I manually created the path but I don't know where the file "abNewCardDialog.xhtml" is to copy into the directory to see if that fixes it.

I have no other addons in Thunderbird.  This is now the only one.  I originally posted an error in the Thunderbird pages but after some help troubleshooting, it was then I discovered it was the addon "conversations" that is causing the problem.

I have attached 3 screenshots, 1 just before I click on the + button, 1 after I click on the + button (see small window and can't read the popup) and 1 after I right click on the popup and maximise the error window so I can read it.

hope this helps

regards

Norman

![2022-07-25 (1)](https://user-images.githubusercontent.com/108510700/180678747-f068a5d1-85b0-49ca-a5f3-fee243b2f027.png)
![2022-07-25 (2)](https://user-images.githubusercontent.com/108510700/180678826-50320266-9ee8-4b8f-a577-7395aa34eb59.png)
![2022-07-25 (3)](https://user-images.githubusercontent.com/108510700/180678915-ce3a3c97-6f8d-4207-bf70-ee0159a8069e.png)

**Comment by Normdeb** [comment]
Hmm sorry, for whatever reason the Thunderbird Conversations information appears to be missing from my post.
Allow Automatic updates = Default
Version = 4.0.19
Last Updated = 25July2022
Permissions = Have full, unrestricted access to Thunderbird, and your computer

**Comment by Standard8** [comment]
Thunderbird changed how the address book works in 102, I'll need to update for that. I have some ideas, just need some time.

**Comment by Normdeb** [comment]
Hi  Mark,
             This hasn't been fixed htat I can see.
I have put the latest version of thunderbird on my computer 102.1.1 and it is saying "Thunderbird is up to date".

I have also removed thunderbird conversations from my computer and re-installed it.

I now have version 4.0.19 "last updated" 6 August 2022 and it is doing the same thing, the same problem.

Do I have to do something different to install the fixed version?

thanks

Norman

**Comment by Standard8** [comment]
The fix has landed in this repository but I haven't released a new version yet. I will probably do that in a couple of days, then it will take a few days for it to be approved.
