### ISSUE TITLE
Reply always uses real address instead of existing recipient

### ISSUE THREAD

**Issue by phate89** [thunderbird-conversations/thunderbird-conversations#1877]
Thunderbird version 102.0.3
Conversations version: 4.0.19
Windows 10 21H1

I receive emails from an alias that I have configured, for example: common@mail.com. But my mail is myname@mail.com. In thunderbird if I click reply I automatically get as a sender common@mail.com because thunderbird recognise that the mail is for my alias and adds automatically common@mail.com. Right now the addon uses my real email address (myname@mail.com).
I'm not sure if it's considered a new feature or a bug but it's something you can channge?
The addon is great but this is a needed thing for me and my colleagues...

**Comment by Standard8** [comment]
This is working fine for me. I have an alias defined as a second identity and emails received to that alias the both the reply in the conversation window and the quick reply will default to that identity.

If it is still an issue for you, we'll need to know exactly which reply functions your using, which email address related headers are set in the email, and the email address setup for your accounts & identities.

**Comment by Standard8** [comment]
Unfortunately without more information I'm not going to be able to fix this. I'm closing this out for now, but quite happy to re-open if we can get more information on the setup and the exact steps to repeat.
