### ISSUE TITLE
Thunderbird Conversations is incompatible with Thunderbird 104.0

### ISSUE THREAD

**Issue by Razumain** [thunderbird-conversations/thunderbird-conversations#1879]
I guess you are aware of this.

What is the best strategy?

Roll back to an earlier release of Thunderbird or wait for an update of this add-on ?

**Comment by Standard8** [comment]
I've just bumped it on the add-ons site, so you in theory should be able to use it now. Unfortunately they've made the decision with nightly/beta versions to make add-ons authors bump numbers each month...
