### ISSUE TITLE
Message content not visible since Thunderbird 104.

### ISSUE THREAD

**Issue by Razumain** [thunderbird-conversations/thunderbird-conversations#1880]
* **Thunderbird version:** 104.0b2
* **Thunderbird Conversation version:** 4.0.19
* **Operating System:** Mac OSX 12.3.1

First Thunderbird 1.0.4 complained that it was not compatible with 104. Then when this was bumped so conversations would start again (yesterday) it still does not work. The body of all messages are gone. Only attachments are visible.

**Comment by Standard8** [comment]
Thanks for the note, I'd already fixed this but hadn't published a new version yet. I've just submitted a new version for approval - it may take a few days before that happens.
