### ISSUE TITLE
Collapsed conversation not showing as Unread when the conversation contains an unread email

### ISSUE THREAD

**Issue by arirangz** [thunderbird-conversations/thunderbird-conversations#1896]
* **Thunderbird version:** 102.2.0
* **Thunderbird Conversation version:** 4.0.22
* **Operating System:** Windonws 11

**What did you do?** 
When a conversation is collapsed an contains an unread message, the conversation is shown as read

**What did you expect to happen?**
Show the conversation as unread if it contains at least one unread message.

**What actually happened?**
The conversation is shown as read

**Comment by arirangz** [comment]
Hi,

Thanks for your reply.

Here is a screenshot to be more clear:
![image](https://user-images.githubusercontent.com/1193727/187947694-c15dbc16-f1fc-4308-840e-3d8e317394ac.png)

As you can see, this conversation is not in bold so we don't know there is a new message unread in it.

If I expand, I can see there is an unread message in it:
![image](https://user-images.githubusercontent.com/1193727/187947970-de8fd1ab-d7d3-43f8-ac10-baa8e20b4dfd.png)

My settings for "automatically mark as read" is When displayed.

Thanks

**Comment by Standard8** [comment]
Thunderbird does underline a message thread if there's an unread message that's not the first message in the thread (as shown in your first screenshot).

This behaviour is completely controlled by Thunderbird, Conversations doesn't do anything with the message list itself, hence I'm closing this out. If you want to raise it with Thunderbird, then https://bugzilla.mozilla.org/ is the place to do that.

**Comment by arirangz** [comment]
Ok thanks for your help.

I managed adding a userChrome.css file
