### ISSUE TITLE
Make the thread the same (complete) from every floder view where emails are stored

### ISSUE THREAD

**Issue by OsadaP** [thunderbird-conversations/thunderbird-conversations#1897]
Win 10
TB 102.2.1
TB Conv 4.0.22

Should Thunderbird Conversations show every e-mail related to a given thread?
If so, I have encountered such inaccuracies from time to time. And today it led to a misunderstanding. I thought that the e-mail I read a few minutes earlier and replied immediately with a simple "Thank you" was gone (I was in the "sent" view). So I logged into the browser version of my organization's mail and found it was in inbox after all.

Admittedly, it would be enough to check "received", but in a hurry I did not think about it.

So, on the canvas of this event, I think TB Conv should show the entire thread in all views it appears in (except maybe trash and spam). And I am sure many have experienced similar confusion.

That is why I would like to ask you to develop the add-on in such a way that all e-mails are visible, regardless of the folder from which we read them.

This situation is shown in pictures below:

![SENT-](https://user-images.githubusercontent.com/86242069/188166754-48aafc2e-89ed-4859-9c0b-fb79738dd782.png)
![INBOX-](https://user-images.githubusercontent.com/86242069/188166724-c25c3720-830e-4467-9776-021d935d179d.png)

And Thunderbird Conversations view (inbox and sent):
![TBConv inbox](https://user-images.githubusercontent.com/86242069/188166864-8fed3b9c-7ee9-4e5f-b9c4-53528a610992.png)
![TBConv sent](https://user-images.githubusercontent.com/86242069/188166886-89ba6828-abcf-4d8c-94dd-0fd2f3d12fa9.png)

I also notice the potential possibility of arranging threads into branches of some kind. When we discuss one topic with many people and we want to lead this one thread in many "sub-threads", and then combine any individual threads to converse in any other "sub-threads". Or if we want to separate a new one from the original thread, because, for example, we reply to a third person and change the subject. Perhaps the idea of ​​email may not take this usage into account - I don't know. Additionally, it would need to establish clear rules on how this is supposed to work. And that would require a lot of code work. So let this paragraph be just a futuristic teaser.

**Comment by OsadaP** [comment]
Actually it behaves like this: 
- when selecting mails numbers from 1 to 4 it is a lack of mail nr 5 (last resonse),
- when selecting last response it is a lack of mail nr 4.


![1INbox mail1](https://user-images.githubusercontent.com/86242069/188175028-1ea764d5-3d51-4d65-a0d8-246a06232395.png)
![2INbox mail4](https://user-images.githubusercontent.com/86242069/188174443-edeecf56-9ab8-4b5d-8f1f-6c7320599ae0.png)

![3sent mail2](https://user-images.githubusercontent.com/86242069/188174445-c6cb1da1-cd84-4d17-b074-934206c936cd.png)
![4sent mail3](https://user-images.githubusercontent.com/86242069/188174448-e6345c19-9372-4d22-86e8-2ce734c6986e.png)
![5sent mail5](https://user-images.githubusercontent.com/86242069/188174449-0870308c-86df-4594-b400-3f6fa9d5f1e1.png)

**Comment by Standard8** [comment]
Unfortunately, I'm finding the descriptions quite confusing. Conversations uses Thunderbird's internal functionality to detect message threads, so this is most likely an issue with Thunderbird.

My best guess is that one of the responses from a person is somehow breaking the threading - not all email clients correctly thread messages, especially some mobile ones.

Try putting all the messages in the same folder - does Thunderbird link them up in the message list at the top of the screen? If it doesn't then this is most likely the issue I just mentioned, if not, then Thunderbird could be doing something wrong somewhere.

**Comment by OsadaP** [comment]
I don't know what happened, but today in this thread I see all the emails no matter which folder I open.

Win 10
TB 102.2.2
TB Conv 4.0.22

**Comment by OsadaP** [comment]
I don't know what happened, but today in this thread I see all the emails no matter which folder I open.

Win 10
TB 102.2.2
TB Conv 4.0.22
