### ISSUE TITLE
Thunderbird dont show threads 

### ISSUE THREAD

**Issue by moguai** [thunderbird-conversations/thunderbird-conversations#1898]
Hello
latest version thunderbird 102.2.1 with Thunderbird Conversations dont show answers under all mail messages, there is certainly an answered.
I uninstall Thunderbird Conversations, use assistent with setting, undo customization, but nothing help.

**Comment by Standard8** [comment]
Please can you try this:

* Select one of the messages that has been answered but isn't showing the extra response.
* Select the three dots at the top-right and select "View in classic reader"
* From there, select the "More" button at the top right, followed by "Open in Conversation"

Does the resulting conversation view show all the messages you expect in the top pane?

**Comment by tommasomazzoni** [comment]
Hi,
Same problem here. The sent messages are not displayed in the conversations. 
Thunderbird version 102.2.2 and Conversations version 4.0.22

@Standard8 I tried your steps. I opened a message in the classic reader, but then the "Open in Conversation" button is grayed out and can not be selected.

**Comment by Standard8** [comment]
@tommasomazzoni interesting. That sounds like the global indexer is disabled.

If you go into preferences, near the bottom of the General section there is a "Indexing" section with "Enable Global Search and Indexer". That will need to be ticked for Conversations to work properly.

**Comment by tommasomazzoni** [comment]
@Standard8 Thanks for your quick reply! Unfortunately the Global search indexer was already enabled...

**Comment by Standard8** [comment]
I just took a quick look at Thunderbird's source. The "Open in Conversation" menu option is disabled if:

* Global search & indexer is disabled, or
* The message has not been indexed

So this would imply that the message hasn't been indexed.

I'm assuming this is not a new profile (sometimes it can take a while for messages to be indexed, though normally it is pretty quick).

Maybe you could check the folder properties for the message the folder is located, and check that "Include messages in this folder in Global Search Results" is ticked.

If that is already ticked, then I think this is an issue with Thunderbird itself, which will probably need raising at https://bugzilla.mozilla.org/

**Comment by tommasomazzoni** [comment]
That's it! Indeed the "Include messages in this folder in Global Search Results" wasn't ticked by default. After checking this parameter and compacted the folders now the sent messages are displayed in the conversation tab.
Thanks for your help!

**Comment by Standard8** [comment]
@tommasomazzoni that's great news.

@moguai does any of the above help with your issue?

**Comment by Standard8** [comment]
Unfortunately no response from @moguai, so I'm closing this out.
