### ISSUE TITLE
OpenPGP self signature not recognized

### ISSUE THREAD

**Issue by pkampkam** [thunderbird-conversations/thunderbird-conversations#1899]
* **Thunderbird version: 91.13.0
* **Thunderbird Conversation version: 4.0.22
* **Operating System: Linux

My sent messages are OpenPGP signed. Reader shows yellow mark with "unknown good signature" hint and message "This message contains a digital signature, but you have previously decided to reject the signer key." after being clicked.

The signature is OK in classic reader.

**Comment by Standard8** [comment]
Unfortunately I can't reproduce this. I took a look through the code and I can't see anything obviously wrong.

Have you double-checked under the OpenPGP key manager that the certificates are valid and haven't been rejected?

**Comment by Standard8** [comment]
Would need more information here, also worth trying on Thunderbird 102.x series to see if anything is different.
