### ISSUE TITLE
Thunderbird Conversations is incompatible with Thunderbird 106.0

### ISSUE THREAD

**Issue by Razumain** [thunderbird-conversations/thunderbird-conversations#1904]
Didn't see any issues on this so submitting one.
I guess supported Thunderbird version need to be upgraded.

Right now conversations is disabled.

**Comment by Standard8** [comment]
Sigh, that's "Thunderbird's we won't let extensions mark themselves as compatible for the next ESR" policy kicking in again.

I've just bumped this on AMO, better go and set some reminders
