### ISSUE TITLE
Clicking on edit contact in address book no reaction

### ISSUE THREAD

**Issue by amourchaleur** [thunderbird-conversations/thunderbird-conversations#1906]
* **Thunderbird version:** 102.3.1 
* **Thunderbird Conversation version:** 4.0.22
* **Operating System:** Windows 11

**What did you do?** Click on "Edit Contact in Address Book" when we hover over a contact

**What did you expect to happen?** Address book should pop up with the contact

**What actually happened?** Nothing happened. 
![Screenshot 2022-10-06 113036](https://user-images.githubusercontent.com/16366455/194208167-fc18cc0c-6f7d-453a-af6a-57cfb5276ba1.png)

Thanks!

**Comment by Standard8** [comment]
Thank you for the report, looks like Thunderbird replaced a function that Conversations depends on [whilst fixing a performance issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1782725). I'll see if we can start using the new one.
