### ISSUE TITLE
Accepting an invitation does't create the event in the calendar

### ISSUE THREAD

**Issue by christophehenry** [thunderbird-conversations/thunderbird-conversations#1912]
* **Thunderbird version:** 102.3.1
* **Thunderbird Conversation version:** 4.0.22
* **Operating System:** Linux (Fedora 36 kernel 5.19.12)

**What did you do?**
* On an email that contains an invitation to an event, I click on *Accept**
* Thunderbird ask me to which calendar to add the event
* I select the desired calendar to add the event to

**What did you expect to happen?**
* The event should be added to the selected calendar

**What actually happened?**
* Nothing happens, the event is not added

This is a TB conversation bug as, if I open the email in the classic reader and click on *Accept*, Thunderbird correctly add the event to the selected calendar and asks me which email adress to answer with.

I have multiple calendars and multiple email accounts in my setup.

**Comment by brtwrst** [comment]
I have the same Problem
Version: 4.0.25
TB: 102.6.1

Pretty sure it also doesn't send the Response Email to the Creator of the event.

**Comment by Standard8** [comment]
I think I've now fixed this. I've just posted 4.0.26 for approval, so hopefully that will be released in a few days.
