### ISSUE TITLE
Displays mixed up information (homescreen with emails information) on startup if there are emails on opened tabs

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#1924]
* **Thunderbird version:**102.4.2
* **Thunderbird Conversation version:**4.0.24
* **Operating System:**ArchLinux

**What did you do?**
Open Thunderbird

**What did you expect to happen?**
To open it without elements that shouldn't be there.

**What actually happened?**
The two parts on top and on bottom (for attachments) of the emails on the main window loads emails opened and loading in separate tabs at the load of thunderbird, leading to have the homescreen along with information from unrelated emails, see this screenshot:

![Screenshot from 2022-11-05 10-36-53](https://user-images.githubusercontent.com/709500/200113794-8fed46c5-fc7d-4705-9097-48795411c665.png)

PS : Another issue that might be related but I'm still unsure if it's due to Conversations addon or a base Thunderbird bug (I didn't reproduced it without the addon as of now, but I don't use it much without the add-on, and startup is also much slower with the addon): quite often Thunderbird on startup seems to re-do the last quick search that was done, even if it was a long time before Thunderbird was closed, and therefore re-filter the emails list and reopen it within the Conversations addon.

Can open another issue if you think that other startup issue have this addon to blame for.

**Comment by Standard8** [comment]
This is an issue with Thunderbird itself. Due to the way their tabs work, the message pane is shared across the tabs - on startup they all get loaded at the same time, even though that's wrong.

Unfortunately there's nothing that Conversations can do about this. Thunderbird is working on moving away from the existing tab model to a better one, but I suspect it might be a year or two before that arrives.

**Comment by Porkepix** [comment]
> This is an issue with Thunderbird itself. Due to the way their tabs work, the message pane is shared across the tabs - on startup they all get loaded at the same time, even though that's wrong.
> 
> Unfortunately there's nothing that Conversations can do about this. Thunderbird is working on moving away from the existing tab model to a better one, but I suspect it might be a year or two before that arrives.

I've no such issue without the addon, but then I guess that's a side-effect of Conversations making the load and display of emails slower than the basic display of bare Thunderbird?

Also, got an idea about the search issue could be related to Conversations in any way or not?

**Comment by Standard8** [comment]
> I've no such issue without the addon, but then I guess that's a side-effect of Conversations making the load and display of emails slower than the basic display of bare Thunderbird?

It is probably a mixture of things, but I suspect Thunderbird itself just gets away with it.. due to the timing.

> Also, got an idea about the search issue could be related to Conversations in any way or not?

Quite possibly a similar or same issue. I don't think either is likely to be able to be resolved until Thunderbird makes their changes to tabs.

**Comment by Porkepix** [comment]
> > Also, got an idea about the search issue could be related to Conversations in any way or not?
> 
> Quite possibly a similar or same issue. I don't think either is likely to be able to be resolved until Thunderbird makes their changes to tabs.

For the search, it relates to quick search/filters, so nothing to deal with tabs, right?

**Comment by Standard8** [comment]
Thunderbird has made changes so this should no longer be an issue in Thunderbird 115, which will probably be released in the next month or so.

Note that Conversations does not yet work with it (xref #1959).
