### ISSUE TITLE
Adressbook avatars / contact images are not shown in TB Conversations

### ISSUE THREAD

**Issue by eigenstil** [thunderbird-conversations/thunderbird-conversations#1929]
* **Thunderbird version:** 102.5.0
* **Thunderbird Conversation version:** 4.0.24
* **Operating System:** Windows 11
* **Using the carddav feature for contacts**

**What did you do?**
Looked at the Conversation View in the right pane

**What did you expect to happen?**
I expect TB conversations to show me the contact images / avatars, that I saved inside of my contacts, if an image is saved in the specific contact. I expect it to see it in the little round preview and in the detail view, when hovering over the senders name.

Contact image / avatar saved in the contact
<img width="764" alt="Screenshot 2022-11-17 111158" src="https://user-images.githubusercontent.com/37832701/202418861-a289e4fc-e2d2-4793-b0fc-3a0ac57d09eb.png">

**What actually happened?**
It shows just the two letters, like on all the contacts, that don't have a contact image / avatar. And it doesn't show the image neither in the detail view, when hovering with the mouse over the sender
<img width="282" alt="Screenshot 2022-11-17 111519" src="https://user-images.githubusercontent.com/37832701/202419600-700450ad-afd7-4025-8877-f971dc4a47b1.png">

**Or am I missing something, where I have to turn on something like "use contact images instead of initials" ?**

**Comment by Standard8** [comment]
This is a [Thunderbird issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1617490), the functionality isn't currently available in 102, although they have fixed it in the later test versions. I'll give them a poke and see if it can get fixed in 102 as we../

**Comment by Standard8** [comment]
Unfortunately the Thunderbird issue never got fixed in 102 because it was too complex. However, it is now fixed in 115, so this should hopefully be working again.
