### ISSUE TITLE
Unread email within conversation gets treated as if it was read

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [thunderbird-conversations/thunderbird-conversations#1931]
* **Thunderbird version:** 102.5.0 (64-bit)
* **Thunderbird Conversation version:** 4.0.25
* **Operating System:** Windows 11 64-bit

**What did you do?**
Used the plugin with conversations

**What did you expect to happen?** 
When I get a new email that belongs to some conversation, I expect either the whole group to be marked as read, or when I order mails by read / unread I expect the whole group to be placed among the unread emails

**What actually happened?**
I lose emails because of the ordering, they are treated as unread even if there's some unread email in the conversation. I even have the option 'by default expand:' set to all messages but it doesn't expand conversations and therefore they are not ordered

**Comment by Standard8** [comment]
Please can you provide some examples? I'm slightly confused as to what you are describing.

The "what actually happened" implies that you are expecting Conversations to affect the message list - which is something that Conversations doesn't do. It only affects the message view area.

**Comment by gabriele-ricci-kyklos** [comment]
@Standard8 yes it is something at first I didn't uderstand, I'll close the issue
