### ISSUE TITLE
'Send' button in quick reply box appears with grey text on white background in dark theme

### ISSUE THREAD

**Issue by Kyogre** [thunderbird-conversations/thunderbird-conversations#1933]
* **Thunderbird version:** 102.5.1
* **Thunderbird Conversation version:** 4.0.25
* **Operating System:** Windows 10

**What did you do?**
Enabled dark theme in TB.

**What actually happened?**
"Send" button in quick reply box appears with grey text on white background, making it unreadable:

![send button is grey on white](https://user-images.githubusercontent.com/2260980/205457730-70587a2b-1046-4c9d-ae6c-63395ac051af.png)

**What did you expect to happen?**
"Send" button in quick reply box appears with readable text color.
If I enable colors substitute in Thunderbird settings button appears with readable text color:
![send button is readable](https://user-images.githubusercontent.com/2260980/205457755-9ee9e927-c763-4c48-aaaf-e20f81f64a23.png)

**Comment by mcmikecreations** [comment]
I have the same issue
