### ISSUE TITLE
Unrelated messages added to a conversation

### ISSUE THREAD

**Issue by ChaiTRex** [thunderbird-conversations/thunderbird-conversations#1939]
* **Thunderbird version:** 102.4.2 (64-bit)
* **Thunderbird Conversation version:** 4.0.25
* **Operating System:** Linux

**What did you do?**
I used this addon.

**What did you expect to happen?**
Messages are considered part of a conversation only when they're part of that conversation.

**What actually happened?**
I couldn't find a message in the conversation list because it was included as one of the e-mails in a conversation it had nothing to do with. It had no shared conversation participants other than me, it had no shared subject line text, and it had no quoted text that matched earlier messages in the conversation.

**Comment by Standard8** [comment]
This is most likely a Thunderbird issue.

If you right-click the message in the main message list, and select "Open in Conversation", is the incorrect message listed there as well?

If so, that is a Thunderbird issue as Conversations only displays what Thunderbird tells it is related. Please file a issue at https://bugzilla.mozilla.org/ if this is the case.

**Comment by ChaiTRex** [comment]
It worked properly immediately when I turned off the addon.

**Comment by Standard8** [comment]
Please can you explain further? What worked properly when you turned off the add-on?

Thunderbird doesn't group messages in the message pane without the add-on, and generally it doesn't use the conversation grouping at all.

**Comment by koekie** [comment]
I actually have the same issue.

In a lot of e-mails I have a wrong thread/conversation added to the e-mail. Thunderbird doesn't identify it as a thread, but the conversation add-on somehow does add a whole conversation to it.
When I selected the "Open in conversation" the old conversation is opened without the message I selected and did an "Open in conversation" on.

* **Thunderbird version**: 102.4.2 (64-bit)
* **Thunderbird Conversation version**: 4.0.26
* **Operating System**: Ubuntu 22.04 LTS

**Comment by stevemadden940** [comment]
When I click NEW MESSAGE, Thunderbird adds a totally unrelated prior email string to the new email every time. It does it on ALL replies as well. I need this resolved as the string it is adding is to NON-DISCLOSURE agreement. THE WORST POSSIBLE STRING TO ADD. I can't post it because of that reason...

PLEASE I NEED HELP... THANK YOU SO MUCH.

**Comment by stevemadden940** [comment]
Thunderbird 102.10.0 (64bit)

**Comment by wyattwhiting** [comment]
I am having this same issue. I have a folder where I keep emails from a particular class of sender. When I try to view individual conversations which have been put in that folder, it will often mix in other senders' messages. I.e., if person A and I have two or three email thread, and I try to view this in conversation view, it will also display unrelated messages from person B who was not involved in the thread whatsoever. 

TB: 102.13.0 (64-bit)
TB Convo: 4.0.26
OS: Linux Mint 20.1

**Comment by Standard8** [comment]
As mentioned previously, I think this is most likely a Thunderbird issue. Thunderbird does the association for conversations, the Conversations' add-on simply uses that association.

As mentioned above, if you are seeing this you should try this:

> If you right-click the message in the main message list, and select "Open in Conversation", is the incorrect message listed there as well?
> 
> If so, that is a Thunderbird issue as Conversations only displays what Thunderbird tells it is related. Please file a issue at https://bugzilla.mozilla.org/ if this is the case.

Closing this out, as I think it is actually a Thunderbird issue.
