### ISSUE TITLE
Not compatible with Thunderbird 115.x

### ISSUE THREAD

**Issue by Razumain** [thunderbird-conversations/thunderbird-conversations#1959]
Conversations does no longer work with version 111.x
I guess you need to update supported releases.

**Comment by Standard8** [comment]
Thunderbird has made some significant changes with their latest beta version - in particular, tabs are now independent of each other, whereas previously they all shared the same items, but pretended to be different.

The changes mean that we also need significant changes in Conversations. I've started working on them and got Conversations to a semi-usable state, but there's still a lot of breakage. Additionally, there's at least two issues in Thunderbird that will need to be resolved for Conversations to work properly.

At the moment, I can't give a timeline for when I'll be in a position to release a version for the latest betas. If it is causing you issues, I'd recommend switching to their current release versions.

**Comment by ImaCrea** [comment]
Hey there, thanks for the info. I'm experiencing same issue and I'll wait.
I wanted to support you but I only found a paypal link and the fees are ridiculous. Have you considered using https://liberapay.com/ ?

**Comment by Razumain** [comment]
Do you have any updates on this? Not to stress the issue. Just curious if there is hope for an update in a foreseeable future?

**Comment by Standard8** [comment]
I suspect it'll be another month or two yet. There's at least one fix required in Thunderbird itself, maybe more. Unfortunately I also haven't had much time to spare recently, so I only get to do a little here and there.

**Comment by Standard8** [comment]
Short progress update: I've just merged my latest fixes to main, however there's still quite a bit not working, especially calendar invites handling, pgp and remote content warnings doesn't work right either. The remote content warnings is waiting a Thunderbird fix, the rest just needs time to work on it and figure it out.

**Comment by Standard8** [comment]
Oh and that's right, message selection doesn't work the first time in a folder (when nothing selected previously), because Thunderbird changed the API for the case I was using and I haven't figured out the best work around yet.

**Comment by mejoebob** [comment]
Just echoing Razumain's comment - your attention/commitment to this is much appreciated.

**Comment by Standard8** [comment]
Unfortunately it is going to be a while longer yet. There are still major parts to rewrite, and I've had almost zero spare time over the last month to work on this.

**Comment by mejoebob** [comment]
> Unfortunately it is going to be a while longer yet. There are still major parts to rewrite, and I've had almost zero spare time over the last month to work on this.

Thanks for replying, and certainly it's understandable. I'm sorry if my comment seemed pushy, but it wasn't meant to be. It was meant to just say that we appreciate your work on this - *whenever* you can do it. I recognize that this is volunteer work and I certainly enjoy how TB has streamlined my email communications. And I believe that I've donated already, but it's certainly worth a few more dollars ;-). (actually way more than just a few). Thanks again.

**Comment by Standard8** [comment]
An update:

I think I now have most of the basic support restored in that you can read emails and do normal actions etc. However, there are still some large-ish pieces of work:

* calendar invite handling
* encrypted email handling
* printing
* between column

The between column currently can't be fixed due to Thunderbird lacking support for it - see #1993. I'm not sure yet if I'll block creating a 115-capable version add-on of this before Thunderbird fixes that it might depend on when Thunderbird enables auto-updates (see notes in that issue).

**Comment by reaseno** [comment]
Since the winget autoupdate, I am facing the problem that Conversations no longer works. Somehow I would have expected that the feature would also come as standard in Thunderbird, if one has the claim to modernise the operation.

My question now is whether I can get a beta of Conversations for TB 115 somewhere? As far as I can see, the cases that are still open do not affect me.

**Comment by Standard8** [comment]
Sorry, I've just been away for a week, hoping to do some more on it this weekend.

> Since the winget autoupdate, I am facing the problem that Conversations no longer works.

I don't know what you mean by "winget autoupdate". As far as I'm aware, Thunderbird has only made the new version available for new users at the moment, no updates have been published, so this generally shouldn't be being hit. The only case that I can think of that might be different would be Linux distributions, or maybe some other distribution type that doesn't auto-update. 
 
> My question now is whether I can get a beta of Conversations for TB 115 somewhere? As far as I can see, the cases that are still open do not affect me.

If you know how to build software you can follow the instructions for this repository. The latest main is the semi-working version. I'm not going to publish betas as they are complicated to maintain and ensure that everyone gets back onto the normal releases later.

**Comment by reaseno** [comment]
> I don't know what you mean by "winget autoupdate". As far as I'm aware, Thunderbird has only made the new version available for new users at the moment, no updates have been published, so this generally shouldn't be being hit. The only case that I can think of that might be different would be Linux distributions, or maybe some other distribution type that doesn't auto-update.

winget is the package manager supplied with Windows. Just like under Linux, it always provides the latest version of the installed software, if possible.

> If you know how to build software you can follow the instructions for this repository.

Not really. I will wait :)

**Comment by tuxayo** [comment]
> The only case that I can think of that might be different would be Linux distributions

Linux distributions are starting to get 115

https://repology.org/project/thunderbird/history

No big worry, it's only the cutting edge distros like Arch and Gentoo that roll Thunderbird to their stable repos so early.

**Comment by domharrington** [comment]
For what it's worth (and I know this was mentioned above too!), I recently started using Thunderbird on macOS and the version Homebrew is v115:

https://github.com/Homebrew/homebrew-cask/blob/ee81489d0484883fa536d089e70230127972d75c/Casks/thunderbird.rb

```sh
$ brew info thunderbird
==> thunderbird: 115.0 (auto_updates)
https://www.thunderbird.net/
/opt/homebrew/Caskroom/thunderbird/115.0 (125B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/thunderbird.rb
==> Name
Mozilla Thunderbird
==> Description
Customizable email client
==> Languages
cs, de, en-GB, en, fr, gl, it, ja, nl, pl, pt, pt-BR, ru, uk, zh-TW, zh
==> Artifacts
Thunderbird.app (App)
==> Analytics
install: 0 (30 days), 0 (90 days), 0 (365 days)
```

Subscribed to this issue to try out this plugin when support is shipped! One of the only things I miss so far from web UI's is a consistent threading experience.

**Comment by ghalse** [comment]
> As far as I'm aware, Thunderbird has only made the new version available for new users at the moment, no updates have been published, so this generally shouldn't be being hit.

My Thunderbird (64-bit on Windows 11) automatically updated to 115.0.1 about a week ago, breaking Conversations with it. It did that on two different machines. So it has definitely been released via at least some update channels.

As far as I know, I have the default update settings:
![image](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/7996633/2dccb796-6876-49b7-9412-8358a520f8d8)
However, I did not specifically choose to install the update (indeed, I had been pre-warned by a colleague who had got it before me). It happened when Windows Update forced a reboot, restarting my Thunderbird.

**Comment by amosonn** [comment]
Hi, is there any way to help with this?

**Comment by andrearesti** [comment]
Just a quick line to thank you for the work you do to keep this great addon updated. I will look for the paypal link to support your work.

**Comment by Standard8** [comment]
> Hi, is there any way to help with this?

Unfortunately, unless you have detailed prior knowledge of Thunderbird's internals, it is probably more work to get you ramped up, than it is to fix it.

At the moment, re-implementing the last missing parts is basically figuring out what Thunderbird is doing, which parts are applicable to Conversations and porting those across into Thunderbird's UI. Unfortunately most of Thunderbird is still built around the assumption that there's only one message displayed per window (and now tab), which additionally complicates things.

I'm making a bit of progress here, I've just been lacking time. Hope to get a bit more this week.

**Comment by reaseno** [comment]
Are you in contact with Thunderbird on the subject?

**Comment by dbonner** [comment]
I really value your work @Standard8 on this extensions.  I just donated.

**Comment by vaclavgreif** [comment]
I just built the extension from source, installed it and the basic funcionality seems to work great. Until the official update is released, I'll use the dev version. For anyone interested to try (or just without the dev setup ready), I uploaded the built version here: https://drive.yotlix.cz/index.php/s/X6rMsgp4KPpjr8H

**Comment by amosonn** [comment]
Thanks @vaclavgreif for this build!

And thanks @Standard8 for all your work!

**Comment by DerXteMensch** [comment]
I tried the build from @vaclavgreif. Most functionalities seem to work, however it doesn't work to save or open attachments. If you click on the attachment buttons, nothing happens. For these functionalities, currently you always have to switch to the classic view. Besides, with conversations installed, you can only print or save emails by right-clicking in the email list, as these options are not part of the main Thunderbird menu anymore and the conversations menus doesn't have these options.

**Comment by vaclavgreif** [comment]
@DerXteMensch Yup, I have the same issue for some type of attachments - for now I learned to live with that. Hopefully @Standard8 will make progress soon and bring us all the awesomeness back soon.. :-)

**Comment by TheModernWizard** [comment]
Thank you @Standard8 ! Keep up the good work!

**Comment by Standard8** [comment]
The new version (4.1.0) is out now. If your Thunderbird hasn't picked it up yet, you should be able to get it by going to the three-bar menu -> Add-ons and Themes -> Extensions, then selecting the Cog symbol followed by "Check for updates".

If you installed the test version that someone posted earlier please ensure that you're now on the official version (worst case, you might have to re-installed it from the add-ons site, but hopefully not).

I did notice that I'd missed the fact that showing "Recent Conversations" for a user was also broken - there's a 4.1.1 going through the approval system now which fixes that as well.

Closing this out, as mentioned in the previous comment, the remaining significant issues will be tracked by themselves (please also file anything else as new issues).

**Comment by DerXteMensch** [comment]
I had the test version installed and the update within Thunderbird to the new version worked flawlessly. Thanks a lot, @Standard8
