### ISSUE TITLE
Printing dialog not working after installing the extension

### ISSUE THREAD

**Issue by cjdg** [thunderbird-conversations/thunderbird-conversations#1972]
* **Thunderbird version: 102.10.0 (64 bits)**
* **Thunderbird Conversation version:4.0.26**
* **Operating System:Ubuntu 22.04

When you install the extension, the printing dialog doesnt appear or even work, disabling/uninstalling the extension fixes the problem

**Comment by Standard8** [comment]
Printing works for me in exactly the same way as it does for Thunderbird. You have to make sure that you have a single message selected.

Does that help?

**Comment by Standard8** [comment]
Without more details, there's not much I can do here.
