### ISSUE TITLE
[help] How can I set default all mails display to expanded state?

### ISSUE THREAD

**Issue by avatar-lavventura** [thunderbird-conversations/thunderbird-conversations#1976]
In the thunderbird conversation single mail is expanded  and all the others are collapesed.

By default is it possible to expand all threads? I just want to see all mails expanded.

**Comment by Standard8** [comment]
Go into the Add-ons Manager (three-bar menu -> Add-ons and Themes), ensure Extensions is selected at the side. In the Thunderbird Conversations entry, there will be a spanner symbol which is "Add-on options".

In there the first option listed is "By default, expand:".

**Comment by avatar-lavventura** [comment]
@Standard8  Thanks!
