### ISSUE TITLE
"Print this conversation" Prints a duplicate of each message in the printout

### ISSUE THREAD

**Issue by rthfhgyhy567** [thunderbird-conversations/thunderbird-conversations#1986]
**Thunderbird version:**
91.6.1
**Thunderbird Conversation version:**
4.0.26
**Operating System:**
Windows 10

**What did you do?**
Selecting "print this conversation" at the bottom of the conversation pane generates a printout of the conversation, but with each message displayed TWICE.  In order to export a bunch of emails into a pdf and send it to someone (e.g. when I have to send email transcripts in occasionally) I have to manually edit the pdf to remove the redundant messages.  REALLY ANNOYING FOLKS.  Hope this isn't an intentional design because if so, I'm uninstalling.

![image](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/104237805/91b0c7c1-b5e7-4eef-b650-65552d5d7e94)

![242360208-2a3d9263-0a41-464a-a8a3-54c33c5628f4](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/104237805/4e6a8524-0597-4a99-b07c-c84f885218df)

**Comment by Standard8** [comment]
It is a bit hard to tell from the screenshots, but I think that there's a couple of possible options.

One is that the message being duplicated has the other messages quoted within it. Conversations will print what is displayed including quoted sections. Conversations won't clean up quoted sections for you, as sometimes the quotations are important to understanding the individual messages and responses.

A different possibility is that Thunderbird is somehow corrupt and collapsing messages together or somehow duplicating them. Viewing in the classic view should clarify if that's what is happening or not.

**Comment by Standard8** [comment]
I'm going to close this out. Conversations is printing the entire conversation. Unfortunately there's not much we can do about quoted sections, especially if they are not actually quoted. It is possible that Conversations could remove quoted sections, but then in some cases, quoted sections would be required, so I don't think there is much we can easily do here.
