### ISSUE TITLE
Messages from Sent folder not shown

### ISSUE THREAD

**Issue by imtrobin** [thunderbird-conversations/thunderbird-conversations#1988]
Hi, the messages from the Sent folder are not in the conservation.

I have 

"Enable  Global Search and Indexer" enabled
As per this thread, "Include messages in this folder in Global Search Results" enabled in Sent folder

https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1898

What else could it be?

* **Thunderbird version:** 102.10.1 portable
* **Thunderbird Conversation version:**  4.0.26
* **Operating System:** win10 64

**Comment by KOMA-Elektronik** [comment]
I have the same issue. I have some folders in which Conversation simply either does not show my replies at all or it mixes it up with other conversations. I tried repairing all involved folders and indexing is on as well.

Thunderbird version: 115.3.1
Thunderbird Conversation version: 4.1.3
Operating System: Ubuntu 22.04

**Comment by Standard8** [comment]
Conversations' gets its information about what is in a conversation from Thunderbird's "Global Search and Indexer".

You could try hovering over the supplier's name and selecting the "Recent Conversations" button, and then seeing if the recent messages appear in there.

If it does not, then this is likely a problem with Thunderbird's database. You could try [rebuilding that database](https://support.mozilla.org/kb/rebuilding-global-database), but be aware that may take quite a few hours to complete depending on your system/amount of emails. It does run in the background though, so it shouldn't affect performance too much.

**Comment by Standard8** [comment]
Without more information, I'm probably not going to be able to do much here. As I said in the previous comment, it is most likely Thunderbird's issue. So check its built-in "Recent Conversations", and see if it shows up there as well.

If so, then it isn't an issue with the Conversation add-on, but with Thunderbird itself.

**Comment by KOMA-Elektronik** [comment]
Sorry for not answering earlier. Indeed, it turned out to be an issue with Thunderbird itself. I had to [rebuild the global database](https://github.com/thunderbird-conversations/thunderbird-conversations/issues/2028#issuecomment-1783841755).
