### ISSUE TITLE
No `Preferences` for remote content blocking

### ISSUE THREAD

**Issue by Lippiece** [thunderbird-conversations/thunderbird-conversations#1992]
* **Thunderbird version: 102.12.0 (64-bit)**
* **Thunderbird Conversation version: 4.0.26**
* **Operating System: EndeavourOS**

**What did you do?**
Open any message

**What did you expect to happen?**
![image](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/47634624/bb4c42b7-aadf-438f-a6e6-5b61d3e1f0e8)

**What actually happened?**
![image](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/47634624/69921dd5-8749-4383-b55b-5b6b9d2c7c19)

May be related to #1453.

**Comment by Standard8** [comment]
What specific functionality from the preferences menu are you missing? I'm not sure if it is something that I'd change or not.

**Comment by Lippiece** [comment]
This was because one of the extensions, can't remember which one.
