### ISSUE TITLE
Extend compiled add-on from source to 117.0b

### ISSUE THREAD

**Issue by Razumain** [thunderbird-conversations/thunderbird-conversations#2001]
Thanks for your recent great work. I successfully built the add-on from source and applied it to version 116.

It works great for me. The small stuff that still does not work does not affect me.

However. Today I upgraded to 117.0b1 and now it it no longer possible to load the latest compiled version as temporary add-on. Attempting to do so produce the error:

"Add-on gconversation@xulforum.org is not compatible with application version. add-on minVersion: 114.0a1. add-on maxVersion: 117.0a1."

Is it possible to bump this version?

**Comment by Razumain** [comment]
Actually. I just tried to run the script **update-max-version.sh** and that made wonders. My problem is solved. But perhaps it would be worth committing a new version to main anyway :)

Thanks again for your great work!

**Comment by Standard8** [comment]
Yeah, I normally do it fairly frequently, just been busy. I've done it for now, though PRs welcome ;)

**Comment by Razumain** [comment]
I've made a fork. Next time I'll give you a PR!
