### ISSUE TITLE
"Not junk" link does not work: "win.JunkSelectedMessages is not a function"

### ISSUE THREAD

**Issue by cpmsmith** [thunderbird-conversations/thunderbird-conversations#2012]
* **Thunderbird version:** 115.2.0
* **Thunderbird Conversation version:** 4.1.1
* **Operating System:** macOS Monterey

**What did you do?**
With Conversations enabled, opened a message which Thunderbird has flagged as junk, and clicked the "Not junk" link:
<img width="204" alt="image" src="https://github.com/thunderbird-conversations/thunderbird-conversations/assets/9437625/0bdcd28a-8c67-46a3-811f-f4a748ff8a13">

**What did you expect to happen?**
The message should no longer be flagged as junk

**What actually happened?**
The banner goes away, but in the message list, the message is still marked as junk. If I navigate to a different message and back, the banner returns.

Console log/stack trace here:

```
TypeError: win.JunkSelectedMessages is not a function
    markSelectedAsJunk jar:file:///[MY PROFILE DIRECTORY]/extensions/gconversation@xulforum.org.xpi!/experiment-api/api.js:304
    markAsJunk chrome://conversations/content/stub.bundle.js:436
    middleware chrome://conversations/content/899.bundle.js:503
    onClick chrome://conversations/content/362.bundle.js:2756
    Nb chrome://conversations/content/116.bundle.js:172
    Tb chrome://conversations/content/116.bundle.js:172
    Ub chrome://conversations/content/116.bundle.js:173
    nf chrome://conversations/content/116.bundle.js:223
    se chrome://conversations/content/116.bundle.js:224
    hd chrome://conversations/content/116.bundle.js:235
    Rk chrome://conversations/content/116.bundle.js:392
    Jb chrome://conversations/content/116.bundle.js:170
    hd chrome://conversations/content/116.bundle.js:227
    fd chrome://conversations/content/116.bundle.js:192
    ed chrome://conversations/content/116.bundle.js:191
```

If I disable Thunderbird Conversations or open the message in the classic reader and use this "Not Junk" button instead, it does work:
<img width="439" alt="image" src="https://github.com/thunderbird-conversations/thunderbird-conversations/assets/9437625/bef0535d-0a04-432f-9e4c-213a3623cb10">

**Comment by cpmsmith** [comment]
[This patch to Thunderbird](https://phabricator.services.mozilla.com/D170018) looks relevant. Seems like the `JunkSelectedMessages` function got removed at some point, and this is where they switched to `commandController.doCommand("cmd_markAsNotJunk")` (or `"cmd_markAsJunk"`)

**Comment by Standard8** [comment]
Thank you, I've just fixed it in the repository.

I also just found a couple more that are similar (going to a message in a different folder, sending unsent), I'll try and find time to fix them tomorrow and then publish a new release.
