### ISSUE TITLE
Convert to Event or Task in TB115.2.2 does not work with Thunderbird Conversation version 4.1.2

### ISSUE THREAD

**Issue by p-palai** [thunderbird-conversations/thunderbird-conversations#2014]
Thunderbird version: 115.2.2 (32bit)
Thunderbird Conversation version:4.1.2
Operating System: Win10

From the mail list, right click after selecting a mail and use Convert to Event or Task from drop down menu does not create an Event/Task.

Disable the Thunderbird Conversation version 4.1.2 extension, repeat the above procedure, Event/Task is successfully created.

**Comment by Standard8** [comment]
This is primarily a Thunderbird issue - when converting to events/tasks there's some wrong assumptions about how to get the selected message. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1855843 about this and posted a possible patch.

**Comment by Standard8** [comment]
The fix was landed in Thunderbird 115.3.3.
