### ISSUE TITLE
[meta] Thunderbird 115.x regressions

### ISSUE THREAD

**Issue by MLopez-Ibanez** [thunderbird-conversations/thunderbird-conversations#2021]
This is a meta-issue to track known regressions when upgrading to Thunderbird 115.x. Before updating to TB 115 and having to downgrade (with all the risks that involves), it may be a good idea to check if you can live with the following regressions:

- [X]  #2007 
- [x] #2014 
- [ ] #2006 
- [ ] #1993 
- [X] #2009 (?)
- [x] #2015 (?)

**Comment by Standard8** [comment]
TBH, I don't really like metas in github as that gives yet another thing to keep updated. The issues I've pinned at the top of the issue are IMO the main blockers that someone might consider not upgrading.

**Comment by MLopez-Ibanez** [comment]
I do not expect you to keep this updated. I am happy to do it myself or close it as soon as it becomes outdated.

I think the blockers my depend on the particular user: I do not use the "Between" column nor encryption, so those are not blockers for me. But #2014 and #2009 are.

**Comment by Standard8** [comment]
Closing this out, it has been enough time, and the last two issues are pinned.
