### ISSUE TITLE
Add-On "Manually sort Folders" Disabled by Thunderbird 115.3.1 Update! 

### ISSUE THREAD

**Issue by VideoPod** [thunderbird-conversations/thunderbird-conversations#2023]
Just sent an email to Johnathan about the Thunderbird 115.3.1 Update disabling his "Manually Sort Folders" Add-On.  
I see he has over 160,000 Users so I'm sure others will be chiming in.  I don't mind donating to his work if this can
be updated to work with Thunderbird 115.3.1, furthermore, if he's working on a new version I'd be interested in that
as well.  Again, Let's Support this work. 
Thank You. Murph

**Comment by MLopez-Ibanez** [comment]
Nothing to do with Thunderbird Conversations. I think you are looking for: https://github.com/protz/Manually-Sort-Folders/issues/204
