### ISSUE TITLE
Conversations stopped tracking / recognizing my sent messages in early June

### ISSUE THREAD

**Issue by KOMA-Elektronik** [thunderbird-conversations/thunderbird-conversations#2028]
- Thunderbird version: 115.3.1
- Thunderbird Conversation version: 4.1.3
- Operating System: Ubuntu 22.04

**What did you do?**
Nothing specific of which I'm aware of.

**What did you expect to happen?**
Conversations to keep working like it was for years.

**What actually happened?**
Since a while now in some folders my replies are not shown anymore in conversations. I can somewhat even pin point the date, it's somewhere early June. For example, I have one conversation with a supplier that already is going since 2018, going back and forth. I can see all messages including my replies but from some point in early June on only my supplier's messages are shown and mine are not shown. It looks like this:

![Bildschirmfoto vom 2023-10-08 21-22-30](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/891776/e73eee93-16e2-48ce-b32d-2c8fc344879f)

This is a local folder but I have this happening in other types of folders. I have tried to:

- repair all involved folders (in fact ALL folders)
- disable / re-enable Conversations
- remove and re-install Conversations

Sometimes it also seems like Conversations mixes up different threads.

I'm out of luck. What can I do?

**Comment by Standard8** [comment]
Conversations' gets its information about what is in a conversation from Thunderbird's "Global Search and Indexer".

You could try hovering over the supplier's name and selecting the "Recent Conversations" button, and then seeing if the recent messages appear in there.

If it does not, then this is likely a problem with Thunderbird's database. You could try [rebuilding that database](https://support.mozilla.org/kb/rebuilding-global-database), but be aware that may take quite a few hours to complete depending on your system/amount of emails. It does run in the background though, so it shouldn't affect performance too much.

**Comment by KOMA-Elektronik** [comment]
Thank you so much for  your answer @Standard8 . Finally something I can try :) Is rebuilding the Thunderbird database akin to "repairing" a single folder? Because I did that several times already and it didn't help.

**Comment by Standard8** [comment]
> Is rebuilding the Thunderbird database akin to "repairing" a single folder? Because I did that several times already and it didn't help.

No, the global database is separate to the folder information.

**Comment by KOMA-Elektronik** [comment]
Great, that's good news for me. Thank you.

**Comment by Standard8** [comment]
Has rebuilding the global search database helped?

**Comment by KOMA-Elektronik** [comment]
I tried it (moved the sqlite file to another folder) but TB doesn't seem to re-index by itself. No such file (_global-messages-db.sqlite_ in my default profile folder) exists now and also the activity manager shows no indexing activity... The same issue as described in my initial post remains.

**Comment by KOMA-Elektronik** [comment]
Magic! This did the trick. It seems, all my conversations are correct again now. Oh my god, thank you so much! It was very tiresome working with what I know now to be a broken database. I was clicking through single e-mails like a digital Neanderthal from the early 2000s. Thank you so much!
