### ISSUE TITLE
Copy Email Address not available in headers

### ISSUE THREAD

**Issue by t4k** [thunderbird-conversations/thunderbird-conversations#2032]
* **Thunderbird version:** 115.3.2 (64-bit)
* **Thunderbird Conversation version:** 4.1.3
* **Operating System:** macOS Sonoma 14.0

**What did you do?** Tried to select a “from” email address in the message header by clicking and dragging to select and right clicking to look for something like “copy email address”.

**What did you expect to happen?** That I would be able to select and copy the email address to my clipboard.

**What actually happened?** When selecting by clicking and dragging the selection across an email address, it highlights as expected, but when I release the mouse/trackpad button, the current message just collapses and redraws without my selection so I cannot copy it. Additionally, there is no context/right click option available for “copy email address”.

I found a tedious way to select the from address: I must click the show details icon :information_source: to display more message headers, and then I must click and drag to select the email address. This is far too cumbersome.

**Comment by Standard8** [comment]
If you hover over the name/email on the collapsed view, a pop-up should appear and there's a copy button next to the email address.
