### ISSUE TITLE
Sometimes after restarting Thunderbird post-upgrade, emails list is empty

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#2035]
* **Thunderbird version:** 115.3.3
* **Thunderbird Conversation version:** 4.1.3
* **Operating System:** Linux

**What did you do?**

Upgrade Thunderbird with package manager and restart it to run the new version

**What did you expect to happen?**

Nothing, for it to work as usual

**What actually happened?**

Emails list was empty, as though I had no mails at all, but the left column had the right numbers.

This is the second time it happens, and restarting Thunderbird doesn't fix the issue. The only fix found is to disable thunderbird-conversations, restart TB without: no issue, then re-enable it and restart again TB: issue is gone.

**Comment by Standard8** [comment]
Given this was a one/two off just after upgrading Thunderbird, I'm going to close this out as there's not enough information to do anything, and I've not heard of other reports.

Pretty sure this wouldn't have been an issue with Conversations, but probably with Thunderbird itself. Disabling Conversations probably caused a cache or something to be cleared which was enough to get it working again.
