### ISSUE TITLE
unable to generate a task or an event from a message via the toolbar

### ISSUE THREAD

**Issue by js32** [thunderbird-conversations/thunderbird-conversations#2044]
![dassa](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/48951041/fa5e1302-437b-4cf6-9e60-99836488742c)

* **Thunderbird version:**
115.4.1 (64-Bit)

* **Thunderbird Conversation version:**
4.1.5

* **Operating System:**
macOS 14.1 (23B74) (M1)

**What did you do?**
I'm trying to convert a message to an event or a task from the icon toolbar.

**What did you expect to happen?**
w/o the plugin, those icons are clickable.

**What actually happened?**
icons are grayed out, adding a task or an event from the context menu works as expected.

**Comment by Standard8** [comment]
I just took a look and this is a Thunderbird issue that they are working towards a fix for:

https://bugzilla.mozilla.org/show_bug.cgi?id=1857835

The fix has landed in the development builds, I've just asked for it to be backported to the current release series.

**Comment by js32** [comment]
Hey, thanks for your fast reply. I'm not quite sure it's the same issue, though.

If I convert a message by context menu it works with or without your plugin enabled. 

The only issue I have is that the icons in the toolbar don't work if the plugin is enabled.

**Comment by Standard8** [comment]
Yes it is the same. Thunderbird has a broken assumption about when to enable the convert to functions - it is expecting a message in the message pane which it loaded there. That's why it doesn't work if the message pane is collapsed (as per that bug). Conversations uses its own message display so the assumption breaks down there as well.

**Comment by js32** [comment]
Alright, thank you! Let's wait and see what the thunderbird team does.

**Comment by Standard8** [comment]
I believe this is now working with the latest Thunderbird.

**Comment by js32** [comment]
Thank you!
