### ISSUE TITLE
e-mail attachments no longer delete or detach 

### ISSUE THREAD

**Issue by dumascon** [thunderbird-conversations/thunderbird-conversations#2050]
* **Thunderbird version: 115.4.1 (64-bit) **
* **Thunderbird Conversation version:**
* **Operating System: Linux Mate Mate v. 20.3**

**What did you do? - Can no longer Delete nor Detach files from an e-mail message. - Only 'Save' files works correctly**

**What did you expect to happen? - Dialog with list of attachments asks to confirm delete (or detach) and then to execute the choice. **

**What actually happened? - Dialog to confirm list of attachments to delete (or detach), but nothing happens, however below at Status Bar, appears: "Moved [NUMBER] messages from Sent to Sent" .  Then in the Sent Items are new extra copies of the e-mail message still containing all the attachments.  **

**Comment by Standard8** [comment]
This seems to be an issue with Thunderbird itself. I just tried using the Thunderbird UI (via the three-dots on the message and "Use Classic Reader"), and then deleting from there, and got duplicate messages.

Please can you file this at https://bugzilla.mozilla.org/
