### ISSUE TITLE
custom message with userChrome.css

### ISSUE THREAD

**Issue by suaide** [thunderbird-conversations/thunderbird-conversations#2052]
* **Thunderbird version: 115.5.0
* **Thunderbird Conversation version: 4.1.5
* **Operating System: Linux Ubuntu

I am trying to set a round border around conversation messages with userChrome.css. Added the following lines in userChrome.css

.message {
  margin: 5px 10px 1px !important;
  border-radius: 15px !important;
}

but doesn´t work. Any hint?

**Comment by Standard8** [comment]
I'm sorry, but I don't support userChrome.css changes, especially as they tend to break the UI when the app or add-on changes. You're welcome to try, but I don't get enough time to work on the add-on as it is.
