### ISSUE TITLE
Delete message doesn't close tab

### ISSUE THREAD

**Issue by maxtimbo** [thunderbird-conversations/thunderbird-conversations#2064]
* **Thunderbird version:** 
   * 115.5.0
* **Thunderbird Conversation version:**
  * 4.1.5
* **Operating System:**
  * Pop!_OS 22.04 LTS x86_64

**What did you do?**
Double click a message in inbox -> opens new tab to display the message -> click the trash can icon -> message is deleted but shows blank tab

**What did you expect to happen?**
delete the message and close the tab

**What actually happened?**
the message is deleted but the tab remains open

**Comment by Standard8** [comment]
Thank you for filing. I hadn't noticed this. Something had changed in Thunderbird & had to adapt to it.
