### ISSUE TITLE
Feature suggestion: save conversation as zip

### ISSUE THREAD

**Issue by rain1** [thunderbird-conversations/thunderbird-conversations#2065]
Hi!

Would it be possible to add feature to save entire conversation as a zip of eml files? I have multiple messages in conversation with attachments. Some are sent by me, some are sent by others to me.  I need every message saved individually so that it would be possible to tell which attachments belong to which message. You already have view message source option. Now you just need to add something that would automate the process of clicking each one of them and saving them.

**Comment by Standard8** [comment]
Saving is not a focus of this add-on, so I'm sorry, but this isn't something I would incorporate. View source isn't quite the same thing. There's plenty of other add-ons that already deal with saving, and this would probably be better handled by one of those.
