### ISSUE TITLE
New replies not shown in conversations

### ISSUE THREAD

**Issue by marco-venuti** [thunderbird-conversations/thunderbird-conversations#2072]
* **Thunderbird version:** 115.6.0
* **Thunderbird Conversation version:** 4.1.5
* **Operating System:** Fedora 39

I used to use conversations on pre-115 Thunderbird on Debian.
When I used to reply in a thread, my message would be shown along with all the others as a conversation in the inbox, tagged as `In sent items` (No copy of sent messages was created in the inbox).

I then migrated the `~/.thunderbird` directory to Fedora, which only offers TB 115.
Now I still see my **old** replies in old threads (i.e. those created with the old TB), but not so anymore for messages sent after I migrated to TB 115 (regardless of whether they were sent from TB itself or from outlook web, my email remote server).
My new replies to threads are instead all gathered in a separate conversation thread which is only visible in the `Sent items` folder (and contains my messages only).

I understand I can get this to work with the TB "unified folders", but I'd like to avoid this for simplicity. And still, I don't understand why old conversations are fine, and the newer ones are not.
I checked the messages sources and the `In-Reply-To` headers match with the `Message-ID` headers correctly, both in the new and old emails.

I guess the expected behaviour is to have a natural conversation view (i.e. with messages by all parties involved) by default.

**Comment by Standard8** [comment]
I strongly suspect that this is a Thunderbird issue. Conversations' gets its information about what is in a conversation from Thunderbird's "Global Search and Indexer".

You could try hovering over the person's name and selecting the "Recent Conversations" button, and then seeing if the recent messages appear in there.

If it does not, then this is likely a problem with Thunderbird's database. You could try [rebuilding that database](https://support.mozilla.org/kb/rebuilding-global-database), but be aware that may take quite a few hours to complete depending on your system/amount of emails. It does run in the background though, so it shouldn't affect performance too much.

You might also want to file this with Thunderbird first at https://bugzilla.mozilla.org/ and see if they want any extra information before you rebuild it.
