### ISSUE TITLE
Messages are failing to be marked as read when clicked on

### ISSUE THREAD

**Issue by poperigby** [thunderbird-conversations/thunderbird-conversations#2073]
* **Thunderbird version:** 122.0b2
* **Thunderbird Conversation version:** 4.1.5
* **Operating System:** Flatpak (on Fedora Kinoite 39)

**What did you do?**

I clicked on a message

**What did you expect to happen?**

I expected the message to be marked as read (it is with the add-on disabled)

**What actually happened?**

The message failed to be marked as read.

**Comment by poperigby** [comment]
This doesn't seem to happen in 115.5.2

**Comment by reyhard** [comment]
I noticed same issue and this issue seems to be exclusive to 122 version. After I've reverted to 121 ( https://archive.mozilla.org/pub/thunderbird/releases/121.0b6/win64/ ) marking messages as read was working again
