### ISSUE TITLE
Ctrl-F / Find in this message doesn't work on email thread preview (only in opened chrome tab view)

### ISSUE THREAD

**Issue by hsandt** [thunderbird-conversations/thunderbird-conversations#2079]
* **Thunderbird version:** 115.6.0 (64-bit)
* **Thunderbird Conversation version:** 4.1.6
* **Operating System:** Ubuntu 22.04

**What did you do?**

Try to Ctrl-F / Find in this message on thread preview (just after clicking email once in the list)

**What did you expect to happen?**

The search bar opens

**What actually happened?**

Nothing. If I go to Edit > Find > Find In This Message... I see that the menu item is grayed out.

Workaround: double-click on email to open thread in chrome tab view and it will work

Related but different issues:
- https://github.com/thunderbird-conversations/thunderbird-conversations/issues/241 was initially about Ctrl-F failing completely for both thread preview and chrome tabs. It was closed, but now thread preview issue is back.
- https://github.com/thunderbird-conversations/thunderbird-conversations/issues/1712 is different because I cannot open the search bar *at all*

**Comment by Standard8** [comment]
Unfortunately this is yet another Thunderbird regression in 115 to do with menu option handling. It is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1839005

There's not much I can do from within conversations.

**Comment by alexisju** [comment]
I have the same issue now with the Thunderbird bin package from Archlinux repository v 115.8.1 (64 bits)

**Comment by Standard8** [comment]
As mentioned in my previous comment, this is a Thunderbird issue. There's nothing I can reasonably do. The issue here is for tracking on the Conversations side only.

They have started work on a fix though it isn't a simple problem, but hopefully they'll complete it soon.

**Comment by Standard8** [comment]
The Thunderbird team have fixed this in Thunderbird 128 which is starting to be released at the moment.
