### ISSUE TITLE
Replies to top of a lot of quote text

### ISSUE THREAD

**Issue by snowbound** [thunderbird-conversations/thunderbird-conversations#2120]
* **Thunderbird version:**115.12.2 
* **Thunderbird Conversation version:**4.1.7
* **Operating System:**Windows 10

**What did you do?** Have conversations with quoted text 

**What did you expect to happen?** I should see all the replies

**What actually happened?** I fail to see a short reply

I am constantly failing to see a short reply on top of a prior back and forth conversation.  I boosted Q**uotes higher than this number of lines will be collapsed.** to 9000 which more than covered the amount of text in the last reply from the person. Yet I fail to see their short one sentence reply on top of that quoted text. I have to open that single message in a new tab!

**Comment by Standard8** [comment]
Please can you attach a screenshot or two?

**Comment by snowbound** [comment]
Quotes higher than this number of lines will be collapsed. to 9000. I looked through most of my conversations and could not find the message that the recipient had replied on top with a max of single-line reply and I could not see that reply. When it was happening all I saw was some of the quoted text. I had to open the reply up in a separate tab to see what they had post reply wise.

**Comment by Standard8** [comment]
Unfortunately without a specific example, it is going to be pretty hard for me to guess what was wrong. I suspect the quoting may have been wrong or something like that. I'm going to close this for now, though I'm quite happy to reopen if we can find specific examples.
