### ISSUE TITLE
Sometimes when selecting a thread with a new message, the new message doesn't show and only a slim white line is visible

### ISSUE THREAD

**Issue by Porkepix** [thunderbird-conversations/thunderbird-conversations#2121]
* **Thunderbird version:** 115.12.2-1
* **Thunderbird Conversation version:** 4.1.7
* **Operating System:** Linux

**What did you do?**
Select the thread with a new message

**What did you expect to happen?**
Shows the new message in the thread.

**What actually happened?**
A visual glitch only shows a slim white line.

The issue appears regularly but not 100% of the times, probably not even 25-50%.
Selecting another thread and coming back to that thread displays the message correctly.

<details>
<summary>
Screenshot
</summary>

![Screenshot from 2024-06-29 13-47-05](https://github.com/thunderbird-conversations/thunderbird-conversations/assets/709500/c953833d-87bb-4b1c-9462-2ffba998ed15)

</details>

**Comment by carlospintosoares** [comment]
I have the same problem on TB version 128.2.2esr (64-bit), conversation version 4.2.2, OS: mac
additional extensions: dark plain text, quicktext, send later, tbsync

**Comment by Standard8** [comment]
Are there any errors displayed on the error console when this happens? You can access the error console by pressing ctrl-shift-J (or cmd-shift-J on Mac).

**Comment by Standard8** [comment]
I've just pushed a fix to increase that timeout, so hopefully that will solve the issue. The fix will be released in the next version, which will hopefully be soon once I've sorted out some build issues.

**Comment by Standard8** [comment]
Sorry for the delay in releasing the fix, 4.2.4 has just been released with the fix.
