### ISSUE TITLE
Sent messages originating on another computer are ignored.

### ISSUE THREAD

**Issue by GrantEdwards** [thunderbird-conversations/thunderbird-conversations#2124]
* **Thunderbird version: 115.13.0 (64-bit)**
* **Thunderbird Conversation version: 4.1.7**
* **Operating System: Linux**

**What did you do?**

I use Thunderbird from two different Linux machines both using the same Exchange Server account (using the OWL plugin).
Both inbox and sent folders reside on the server and show the same list of messages on both computers.

**What did you expect to happen?**

I expect that the threading for a given "conversation" will show the same set of messages on both computers and will contain all received and sent messages for that thread.  

**What actually happened?**

Both computers include all received messages (from inbox) in the conversion. On computer A, only messages sent from computer A are included in the conversation. On computer B, only messages sent from computer B are included in the conversation.  Again, the contents of the "inbox" and "sent" folders are identical for both computers.

**Comment by Standard8** [comment]
My strong suspicion is that this is something to do with Thunderbird's global search & indexer.

In the broken state, if you hover over one of the contacts and select "recent conversations", do the missing messages show up there?

If they are not showing, then this would either be to do with the OWL add-on somehow not letting those messages be indexed/triggering them for indexing, or Thunderbird's global search & indexer not indexing them for some reason.

**Comment by GrantEdwards** [comment]
> In the broken state, if you hover over one of the contacts and select "recent conversations", do the missing messages show up there?

Hovering over a contact (anywhere) and clicking "recent conversations" brings up a new, completely empty tab.

**Comment by GrantEdwards** [comment]
> Hovering over a contact (anywhere) and clicking "recent conversations" brings up a new, completely empty tab.

Oh, I guess I didn't wait long enough.  For some contacts, if I wait a couple minutes,  A list of messages/conversations do show up.  For some contacts, nothing ever shows up (or maybe I still haven't waited long enough).

For the contacts where the "recent conversations" does show something, the replies sent by me on the "other" computer do not appear.

**Comment by GrantEdwards** [comment]
>[...] For some contacts, nothing ever shows up (or maybe I still haven't waited long enough).

I hadn't waited long enough.  Recent conversations does work for all contacts if I wait long enough. But, messages sent from the other computer never show up. 

I tried repairing the folder index for the sent folder, and that didn't make any difference.  Global search and indexing is enabled.  I also tried "get all messages" while "in" the sent folder, and that didn't have any effect. If I go into the sent folder, messages from the other computer are there, and when I click on one it is displayed — but it's "alone" and not part of a conversation.

**Comment by Standard8** [comment]
> > Hovering over a contact (anywhere) and clicking "recent conversations" brings up a new, completely empty tab.
> 
> Oh, I guess I didn't wait long enough. For some contacts, if I wait a couple minutes, A list of messages/conversations do show up. For some contacts, nothing ever shows up (or maybe I still haven't waited long enough).
> 
> For the contacts where the "recent conversations" does show something, the replies sent by me on the "other" computer do not appear.

This shows that for some reason Thunderbird isn't handling those messages correctly. Unfortunately there isn't anything Conversations can do about that, as all the information comes from Thunderbird.

If this is still a problem in the latest Thunderbird, you can file it at https://bugzilla.mozilla.org/
