### ISSUE TITLE
Nested conversations do not work with Outlook inbox

### ISSUE THREAD

**Issue by majhi33** [thunderbird-conversations/thunderbird-conversations#2133]
* **Thunderbird version:** 128.0.1esr (64 bits)
* **Thunderbird Conversation version:** 4.2.1
* **Operating System:** Windows 10 Pro

**What did you do?**
Used an Outlook / Office365 email address with Thunderbird

**What did you expect to happen?**
Have nested conversations

**What actually happened?**
The conversation functionality does not nest conversations into threads and emails in the same thread are listed individually. This functionality works as expected with Gmail accounts and replies appear as threads. You can see in this screenshot what it looks like with my Outlook inbox.
![test](https://github.com/user-attachments/assets/6d9d95e7-54f9-47c5-a201-11f8505e603c)

**Comment by Standard8** [comment]
This is probably a bug in Thunderbird. Conversations does not affect the thread pane only the message display. If they're not grouped in the thread pane then you've either not got threading turned on or there's an issue which means Thunderbird isn't grouping them.

Filing a bug at https://bugzilla.mozilla.org is probably the best place to go next.
