### ISSUE TITLE
Collapsed messages no longer show first line of message

### ISSUE THREAD

**Issue by cs96and** [thunderbird-conversations/thunderbird-conversations#2141]
* **Thunderbird version:** 128.2.0esr
* **Thunderbird Conversation version:** 4.2.1
* **Operating System:** Linux (Debian 12)

**What did you do?**
Viewed a conversation with multiple messages.  Looked at the older messages which are collapsed.  (I'm also using the Owl plugin).

**What did you expect to happen?**
To see the first line of the message in the collapsed view.  E.g. Here is the view from Thunderbird 115.14.0 / Conversations 4.1.7...
![image](https://github.com/user-attachments/assets/fcd4d9d7-d9aa-4d31-af1d-2024095c2d65)

**What actually happened?**
The first line of the message is no longer displayed...
![image](https://github.com/user-attachments/assets/103696fa-a508-4a5a-9da4-6f2d743631ee)

**Comment by Standard8** [comment]
This is now fixed, I'll push a release out soon.
