### ISSUE TITLE
Ctrl-F is broken

### ISSUE THREAD

**Issue by protz** [thunderbird-conversations/thunderbird-conversations#241]
This should popup the search bar. It isn't enabled for the multimessage or the chrome tabs. The reason is, the Find bar is designed for content, not chrome, so it ends up searching the whole window...

**Comment by MLopez-Ibanez** [comment]
The obvious work-around is to switch to the classical reader and search there. Could this happen automagically when pressing Ctrl+F or Find in the menu? I think it would be a bit surprising but less surprising that trying to figure out why Find is disabled in the menu and Ctrl+F does nothing.

(Thanks for the addon! if it didn't exist, I would stop using Thunderbird.)

**Comment by protz** [comment]
I think that's a good idea and I would welcome a pull request to that 
effect :)

**Comment by Standard8** [comment]
I wonder if it'd be possible to move the existing findbar from the current location in the dom to our conversation view... might depend on what toolkit is actually looking for when it looks for the findbar.

**Comment by MLopez-Ibanez** [comment]
With the new React interface and the push for WebExtensions, maybe this is possible now?

**Comment by Standard8** [comment]
Unfortunately this really is a Thunderbird architecture issue - for example, find doesn't work when you have multiple messages selected.

I have some ideas to change it within Thunderbird, I'll have to see how practical they are.

**Comment by Standard8** [comment]
Having touched on some other issues with the multi-message pane in Thunderbird recently, I took another look at this and found a solution.

I've just [filed a patch for it](https://bugzilla.mozilla.org/show_bug.cgi?id=1719100), so hopefully it should get accepted soon.

It is a Thunderbird issue, and one that I can't patch from Conversations, so we'll need to wait until the next major release for it to be released - this should be 91 which is due for release in August.

**Comment by Standard8** [comment]
Just to note there is one issue I haven't figured out yet. If the text is found in the areas surrounding a message, then doing repeated ctrl/cmd-f to go through the highlighted entries doesn't work. If the text is only found in the message, then it works fine.

That'll probably need a Thunderbird change, but I've no idea what might be causing it at this time, a similar thing works fine in Firefox which uses pretty much the same code base.

**Comment by Standard8** [comment]
Thunderbird 91 is now out & is starting to roll out via automatic updates to some users, I believe it is available to all users using the manual update mechanism (via help -> about). If not, then it should be within the next couple of weeks.

I've split the remaining issue out to #1712.
