### ISSUE TITLE
Changing layouts breaks the conversation view

### ISSUE THREAD

**Issue by protz** [thunderbird-conversations/thunderbird-conversations#534]
The workaround is to restart Thunderbird after changing the layout.

**Comment by rapgro** [comment]
I can reproduce this with Thunderbird 31.7.0 and Conversations 2.8.1

**Comment by Standard8** [comment]
I believe this is now fixed, and should be in the next release (4.0.18) that is currently in the approval queue.

The scroll position will likely change, but I think that would probably happen anyway, given the big layout changes that are happening.
