### ISSUE TITLE
ReferenceError: Conversations is not defined (MailSummaries incompatibility)

### ISSUE THREAD

**Issue by wagnerand** [thunderbird-conversations/thunderbird-conversations#699]
I don't exactly know how to reproduce this but I can say that this happens several times a day: When I try to delete a conversation via the button in the message pane, I get the following error:

Error: ReferenceError: Conversations is not defined
Source file: chrome://conversations/content/stub.xhtml
Line: 341

Seems like the global somehow gets garbage collected or something.
The only thing I can do to fix it is to restart Thunderbird.

TB 18, Conversations 2.6

**Comment by Standard8** [comment]
MailSummaries appears to be no longer supported unfortunately.

I've not heard other reports of this recently, so I'll close it out. If mail summaries pops up again, we can take another look.
