### ISSUE TITLE
do not preserve quick reply session if no changes was made here

### ISSUE THREAD

**Issue by yurks** [thunderbird-conversations/thunderbird-conversations#771]
Given:
  message viewing with a plugin
and
  user clicks on quick-reply area
and
  edit mode entering as expected.

If
  user don't write anything here
and
  open another message for viewing
and
  going back
then
  quick reply still opening like there is some saved draft

**Comment by Standard8** [comment]
This shouldn't happen in the 4.0.0 version that I've just pushed for review & will hopefully be approved in a few days.
