### ISSUE TITLE
Limited number of tabs

### ISSUE THREAD

**Issue by trife** [thunderbird-conversations/thunderbird-conversations#809]
Is there a hard-coded limit to the number of tabs a user can open using Conversation View? I can only open ten tabs that use the Conversation View. I can open additional tabs using the default message interface.

**Comment by phil-s** [comment]
FWIW, I stopped using Conversations a long time ago on account of this.

Not only does this seem like an entirely arbitrary restriction, but 10 tabs is a crazily small number! Just as with a web browser, I want to be able to open tabs for all the things which I want to attend to in the near future, and it might take me several days to get around to some of them. I was hitting this restriction on an extremely regular basis, and it was a deal-breaker.

I'm a bit sad to see that it's still a going concern, but I never made the effort to report it myself, so I can't complain. I will certainly add my voice to this request that the limitation be lifted, however. I guess we need to open a Thunderbird issue?

**Comment by sahil48** [comment]
I wanted to follow up on this issue. What I found out is that you can open additional thunderbird messages in additional tabs using the classic reader. Once the 10 tab hard limit is reached, could Thunderbird Conversation default to opening additional messages in new tabs using the classic reader? This would be an amazing improvement to cope with this terrible restriction.

**Comment by sahil48** [comment]
As an alternative, could a setting be provided where opening a conversation use the standard Thunderbird message viewer when there is only one email in the conversation, and opt into the thunderbird conversations viewer when there is more than one email in the conversation?

**Comment by Standard8** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1772756 on Thunderbird to adjust the behaviour. When we first implemented it there the limit was mainly arbitrary, and I no longer think it should be there.

I'm closing this out as I don't think there's anything Conversations should do here - we need to get Thunderbird itself fixed.
