### ISSUE TITLE
plugin hardcodes to "Sent" folder?

### ISSUE THREAD

**Issue by zzzeek** [thunderbird-conversations/thunderbird-conversations#937]
it seems like when I use the "reply" feature of the Conversations window, sent messages are hardcoded to go into a folder called "Sent".   If the folder does not exist, it gets created.  This is all in conflict with my established preferences to send "sent" messages to a folder specifically named "Sent Messages".  When I use the Conversations tab to send, I actually get two "sent" folder icons to the same account in my left toolbar.

When I write an email using traditional File->New->Message and send, the sent message goes correctly to my custom-configured "Sent Messages" folder.

I'm using TB 38.0b1 on OSX; I've upgraded Conversations to the nightly for 20150330 and it still occurs.

**Comment by protz** [comment]
Thanks for reporting. I'm inclined to believe that there is, indeed, a bug in this area.

**Comment by lkraav** [comment]
@zzzeek does this bug still occur in recent versions?

**Comment by Standard8** [comment]
I've just pushed a Conversations 4.0.0 for review and should be out in the next few days. Testing it locally, this works fine now.
